// Dutch (nl)

let strings_nl: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "INLOGGEN!",
    "SIGN UP!": "REGISTREREN!",
    "Account": "Account",
    "Email": "E-mail",
    "Password": "Wachtwoord",
    "Profile": "Profiel",
    "Age": "Leeftijd",
    "Timezone (e.g., %@)": "Tijdzone (bijv. %@)",
    "LOADING!": "LADEN!",
    "Log In": "Inloggen",
    "Create Account": "Account aanmaken",
    "Need an account?": "Nog geen account?",
    "Have an account?": "Heb je al een account?",
    "Sign Up": "Registreren",

    // MARK: - Content / Main
    "No dreams match your search": "Geen dromen komen overeen met je zoekopdracht",
    "Dreams": "Dromen",
    "Search dreams...": "Dromen zoeken...",
    "Welcome, Dreamer!": "Welkom, Dromer!",
    "DREAM ON!": "DROOM VERDER!",
    "Record your first dream to begin your comic journey!": "Neem je eerste droom op om je stripreis te beginnen!",
    "Capture a Dream": "Een droom vastleggen",
    "DELETE": "VERWIJDEREN",

    // MARK: - New Dream
    "What did you dream?": "Wat heb je gedroomd?",
    "Describe your dream or nightmare...": "Beschrijf je droom of nachtmerrie...",
    "Stop Recording": "Opname stoppen",
    "Record Dream": "Droom opnemen",
    "Tap to stop voice recording": "Tik om de spraakopname te stoppen",
    "Tap to start describing your dream with your voice": "Tik om je droom met je stem te beschrijven",
    "Listening...": "Luisteren...",
    "When did you see this dream?": "Wanneer had je deze droom?",
    "Save Dream": "Droom opslaan",
    "New Dream": "Nieuwe droom",

    // MARK: - Common Actions
    "Cancel": "Annuleren",
    "Save": "Opslaan",
    "Edit": "Bewerken",
    "Delete": "Verwijderen",
    "Done": "Klaar",
    "Try Again": "Opnieuw proberen",
    "Retry": "Opnieuw",
    "Add": "Toevoegen",
    "View": "Bekijken",

    // MARK: - Dream Detail
    "Dream date": "Droomdatum",
    "Original Dream": "Oorspronkelijke droom",
    "Dream Analysis": "Droomanalyse",
    "ANALYZING!": "ANALYSEREN!",
    "Rewritten Dream (%@)": "Herschreven droom (%@)",
    "Stop": "Stop",
    "Play Story": "Verhaal afspelen",
    "Tap to stop reading the story": "Tik om het voorlezen te stoppen",
    "Tap to hear the story read aloud": "Tik om het verhaal hardop te horen voorlezen",
    "Try a Different Tone?": "Een andere toon proberen?",
    "How Should This Dream Feel?": "Hoe moet deze droom aanvoelen?",
    "Narrating!": "Vertellen!",
    "Narrate Again": "Opnieuw vertellen",
    "Narrate": "Vertellen",
    "Delete Dream": "Droom verwijderen",
    "Dream": "Droom",
    "Delete this dream?": "Deze droom verwijderen?",
    "This will permanently remove this dream and all its content.": "Dit verwijdert deze droom en al zijn inhoud permanent.",

    // MARK: - Tones
    "Happy": "Blij",
    "Funny": "Grappig",
    "Hopeful": "Hoopvol",
    "Calm": "Kalm",
    "Positive": "Positief",

    // MARK: - Dream Analysis
    "Time Period": "Tijdsperiode",
    "Period": "Periode",
    "Emotion Trends": "Emotietrends",
    "Loading trends...": "Trends laden...",
    "Loading summary...": "Samenvatting laden...",
    "Summary": "Samenvatting",
    "Most Common Feeling": "Meest voorkomend gevoel",
    "Average intensity: %.0f%%": "Gemiddelde intensiteit: %.0f%%",
    "dreams": "dromen",
    "Suggested Moods": "Voorgestelde stemmingen",
    "Activity": "Activiteit",
    "Keep logging dreams to see trends": "Blijf dromen opschrijven om trends te zien",
    "Record your first dream to start tracking your emotions": "Neem je eerste droom op om je emoties bij te houden",
    "ZAP!": "ZAP!",
    "OOPS!": "OEPS!",

    // MARK: - Settings
    "Signed in": "Ingelogd",
    "Cloud sync enabled": "Cloudsynchronisatie ingeschakeld",
    "Sign In / Sign Up": "Inloggen / Registreren",
    "Create an account to sync dreams and AI content.": "Maak een account aan om dromen en AI-inhoud te synchroniseren.",
    "Notifications": "Meldingen",
    "Notification Settings": "Meldinginstellingen",
    "Settings": "Instellingen",
    "Dream Character": "Droomkarakter",
    "These details personalize your dream comics": "Deze details personaliseren je droomstrips",
    "Sign Out": "Uitloggen",
    "Gender": "Geslacht",
    "Male": "Man",
    "Female": "Vrouw",
    "Non-binary": "Non-binair",
    "Prefer not to say": "Zeg ik liever niet",
    "Language": "Taal",

    // MARK: - Dream Visualization
    "Dream Visualization": "Droomvisualisatie",
    "AI creates a comic page from your dream": "AI maakt een strippagina van je droom",
    "Include my likeness": "Mijn gelijkenis opnemen",
    "OFFLINE!": "OFFLINE!",
    "Image generation requires Apple Silicon or sign-in.": "Beeldgeneratie vereist Apple Silicon of inloggen.",
    "Draw my dream!": "Teken mijn droom!",
    "Redraw my dream!": "Herteken mijn droom!",
    "Regenerate as Comic Page": "Opnieuw genereren als strippagina",
    "CREATING!": "MAKEN!",
    "Painting your dream...": "Je droom wordt geschilderd...",
    "Add your details in Profile to appear in your dreams!": "Voeg je gegevens toe in Profiel om in je dromen te verschijnen!",
    "Scene %d": "Sc\u{00E8}ne %d",
    "Save your dreams!": "Bewaar je dromen!",
    "Sign up to sync rewrites and comics across devices.": "Registreer je om herschrijvingen en strips op al je apparaten te synchroniseren.",
    "Dream Sequence": "Droomsequentie",
    "Dream Comic Page": "Droomstrippagina",

    // MARK: - Notifications
    "Notifications Enabled": "Meldingen ingeschakeld",
    "Enable Notifications": "Meldingen inschakelen",
    "Permission": "Toestemming",
    "Allow notifications to receive reminders and follow-ups.": "Sta meldingen toe om herinneringen en opvolgingen te ontvangen.",
    "Notification Types": "Meldingstypen",
    "Configure each notification type independently with its own schedule.": "Configureer elk meldingstype onafhankelijk met een eigen schema.",
    "Permission Required": "Toestemming vereist",
    "Open Settings": "Instellingen openen",
    "Please enable notifications in Settings to receive reminders.": "Schakel meldingen in bij Instellingen om herinneringen te ontvangen.",
    "When to Notify": "Wanneer melden",
    "Time of Day": "Tijdstip",
    "Day of Week": "Dag van de week",
    "Select Days": "Dagen selecteren",
    "Preview": "Voorbeeld",
    "Frequency": "Frequentie",
    "Time": "Tijd",
    "Day": "Dag",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Je ontvangt dagelijks een melding om %@.",
    "You'll receive notifications Monday through Friday at %@.": "Je ontvangt meldingen van maandag tot en met vrijdag om %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Je ontvangt meldingen op zaterdag en zondag om %@.",
    "You'll receive a notification every %@ at %@.": "Je ontvangt elke %@ een melding om %@.",
    "Select at least one day to receive notifications.": "Selecteer minstens \u{00E9}\u{00E9}n dag om meldingen te ontvangen.",
    "You'll receive notifications on %@ at %@.": "Je ontvangt meldingen op %@ om %@.",

    // MARK: - Dream Reminders
    "Reminders": "Herinneringen",
    "No reminders set": "Geen herinneringen ingesteld",
    "Add a reminder to revisit this dream": "Voeg een herinnering toe om deze droom te herbezoeken",
    "EXPIRED": "VERLOPEN",
    "REMINDER TYPE": "HERINNERINGSTYPE",
    "WHEN": "WANNEER",
    "PREVIEW": "VOORBEELD",
    "Custom": "Aangepast",
    "Add Reminder": "Herinnering toevoegen",
    "Date & Time": "Datum & tijd",
    "1 hour": "1 uur",
    "6 hours": "6 uur",
    "Tomorrow": "Morgen",
    "2 days": "2 dagen",
    "1 week": "1 week",
    "You'll receive a \"%@\" reminder on %@": "Je ontvangt een \"%@\"-herinnering op %@",

    // MARK: - Avatar
    "Use This Photo": "Deze foto gebruiken",
    "Use Memoji": "Memoji gebruiken",
    "Choose Photo": "Foto kiezen",
    "Take Photo": "Foto maken",
    "Remove Avatar": "Avatar verwijderen",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Je foto maakt een tekstbeschrijving van je uiterlijk. De foto zelf wordt niet gedeeld met AI-diensten.",
    "Profile Picture": "Profielfoto",
    "Paste Your Memoji": "Plak je Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Tik op het tekstveld hieronder\n2. Schakel over naar het Memoji-toetsenbord\n3. Tik op je favoriete Memoji-sticker",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Tik hier en plak dan Memoji...",
    "Uploading...": "Uploaden...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "We stellen voor dit te herschrijven als een ",
    " dream": " droom",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Angst",
    "Sadness": "Verdriet",
    "Anger": "Woede",
    "Anxiety": "Bezorgdheid",
    "Stress": "Stress",
    "Loneliness": "Eenzaamheid",
    "Helplessness": "Hulpeloosheid",
    "Shame": "Schaamte",
    "Grief": "Rouw",
    "Confusion": "Verwarring",
    "Joy": "Vreugde",
    "Love": "Liefde",
    "Surprise": "Verrassing",
    "Disgust": "Walging",
    "Trust": "Vertrouwen",
    "Anticipation": "Verwachting",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Vredig",
    "Serene": "Sereen",
    "Humorous": "Humoristisch",
    "Lighthearted": "Luchtig",
    "Empowering": "Versterkend",
    "Confident": "Zelfverzekerd",
    "Optimistic": "Optimistisch",
    "Inspiring": "Inspirerend",
    "Joyful": "Blij",
    "Cheerful": "Opgewekt",
    "Neutral": "Neutraal",

    // MARK: - Trend Directions
    "Improving": "Verbeterend",
    "Worsening": "Verslechterend",
    "Stable": "Stabiel",

    // MARK: - Analysis Periods
    "7 Days": "7 dagen",
    "30 Days": "30 dagen",
    "90 Days": "90 dagen",
    "All": "Alles",

    // MARK: - Notification Categories
    "Daily Check-in": "Dagelijkse check-in",
    "Dream Reflection": "Droomreflectie",
    "Nightmare Follow-up": "Nachtmerrie-opvolging",
    "Weekly Digest": "Wekelijks overzicht",
    "Gentle reminder to log your dreams": "Vriendelijke herinnering om je dromen op te schrijven",
    "Reflect on dreams you've recorded": "Reflecteer op dromen die je hebt opgenomen",
    "Check in after rewriting a nightmare": "Inchecken na het herschrijven van een nachtmerrie",
    "Weekly summary of your dream journey": "Wekelijkse samenvatting van je droomreis",

    // MARK: - Notification Frequencies
    "Every Day": "Elke dag",
    "Weekdays Only": "Alleen doordeweeks",
    "Weekends Only": "Alleen weekenden",
    "Once a Week": "Eenmaal per week",
    "Custom Days": "Aangepaste dagen",

    // MARK: - Day Names
    "Sun": "Zo",
    "Mon": "Ma",
    "Tue": "Di",
    "Wed": "Wo",
    "Thu": "Do",
    "Fri": "Vr",
    "Sat": "Za",

    // MARK: - Notification Templates
    "Good morning!": "Goedemorgen!",
    "Dream Journal Time": "Droomdagboektijd",
    "Remember Your Dreams?": "Herinner je je dromen?",
    "Start Your Day Mindfully": "Begin je dag bewust",
    "Did you dream last night? Take a moment to record it.": "Heb je vannacht gedroomd? Neem even de tijd om het op te schrijven.",
    "Your dreams are waiting to be captured.": "Je dromen wachten om vastgelegd te worden.",
    "A few minutes to log your dreams can make a big difference.": "Een paar minuten om je dromen op te schrijven kan een groot verschil maken.",
    "Dreams fade quickly - save yours now.": "Dromen vervagen snel \u{2013} bewaar de jouwe nu.",
    "Time to Reflect": "Tijd om te reflecteren",
    "Dream Insight": "Droominzicht",
    "Look Back": "Terugblik",
    "Your Dream Journey": "Jouw droomreis",
    "Revisit a dream you recorded and see how it makes you feel now.": "Herbekijk een droom die je hebt opgenomen en kijk hoe het je nu doet voelen.",
    "Your past dreams might hold insights for today.": "Je eerdere dromen bevatten misschien inzichten voor vandaag.",
    "Take a moment to reflect on your dream patterns.": "Neem even de tijd om na te denken over je droompatronen.",
    "What have your dreams been telling you lately?": "Wat hebben je dromen je de laatste tijd verteld?",
    "How Are You Feeling?": "Hoe voel je je?",
    "Gentle Check-in": "Vriendelijke check-in",
    "You're Doing Great": "Je doet het geweldig",
    "Healing Journey": "Helingsreis",
    "How did the rewritten dream make you feel? Consider reading it again.": "Hoe voelde de herschreven droom? Overweeg het nog eens te lezen.",
    "Remember, you have the power to reshape your dreams.": "Onthoud, jij hebt de kracht om je dromen te hervormen.",
    "Take a moment to revisit your peaceful dream version.": "Neem even de tijd om je vredige droomversie opnieuw te bekijken.",
    "Your healing journey continues. We're here for you.": "Je helingsreis gaat verder. We zijn er voor je.",
    "Your Week in Dreams": "Je week in dromen",
    "Weekly Reflection": "Wekelijkse reflectie",
    "Dream Summary": "Droomsamenvatting",
    "This Week's Journey": "De reis van deze week",
    "See how your dream patterns evolved this week.": "Bekijk hoe je droompatronen deze week zijn ge\u{00EB}volueerd.",
    "Time for your weekly dream check-in.": "Tijd voor je wekelijkse droom-check-in.",
    "Reflect on your dream journey this week.": "Reflecteer op je droomreis deze week.",
    "A week of dreams - what stories did they tell?": "Een week vol dromen \u{2013} welke verhalen vertelden ze?",
]
