// French (fr)

let strings_fr: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "CONNEXION !",
    "SIGN UP!": "INSCRIPTION !",
    "Account": "Compte",
    "Email": "E-mail",
    "Password": "Mot de passe",
    "Profile": "Profil",
    "Age": "Âge",
    "Timezone (e.g., %@)": "Fuseau horaire (ex., %@)",
    "LOADING!": "CHARGEMENT !",
    "Log In": "Se Connecter",
    "Create Account": "Créer un Compte",
    "Need an account?": "Besoin d'un compte ?",
    "Have an account?": "Vous avez un compte ?",
    "Sign Up": "S'inscrire",

    // MARK: - Content / Main
    "No dreams match your search": "Aucun rêve ne correspond à votre recherche",
    "Dreams": "Rêves",
    "Search dreams...": "Rechercher des rêves...",
    "Welcome, Dreamer!": "Bienvenue, Rêveur !",
    "DREAM ON!": "RÊVEZ !",
    "Record your first dream to begin your comic journey!": "Enregistrez votre premier rêve pour commencer votre aventure en bande dessinée !",
    "Capture a Dream": "Capturer un Rêve",
    "DELETE": "SUPPRIMER",

    // MARK: - New Dream
    "What did you dream?": "Qu'avez-vous rêvé ?",
    "Describe your dream or nightmare...": "Décrivez votre rêve ou cauchemar...",
    "Stop Recording": "Arrêter l'Enregistrement",
    "Record Dream": "Enregistrer le Rêve",
    "Tap to stop voice recording": "Touchez pour arrêter l'enregistrement vocal",
    "Tap to start describing your dream with your voice": "Touchez pour commencer à décrire votre rêve avec votre voix",
    "Listening...": "Écoute en cours...",
    "When did you see this dream?": "Quand avez-vous fait ce rêve ?",
    "Save Dream": "Sauvegarder le Rêve",
    "New Dream": "Nouveau Rêve",

    // MARK: - Common Actions
    "Cancel": "Annuler",
    "Save": "Sauvegarder",
    "Edit": "Modifier",
    "Delete": "Supprimer",
    "Done": "Terminé",
    "Try Again": "Réessayer",
    "Retry": "Réessayer",
    "Add": "Ajouter",
    "View": "Voir",

    // MARK: - Dream Detail
    "Dream date": "Date du rêve",
    "Original Dream": "Rêve Original",
    "Dream Analysis": "Analyse du Rêve",
    "ANALYZING!": "ANALYSE !",
    "Rewritten Dream (%@)": "Rêve Réécrit (%@)",
    "Stop": "Arrêter",
    "Play Story": "Lire l'Histoire",
    "Tap to stop reading the story": "Touchez pour arrêter la lecture de l'histoire",
    "Tap to hear the story read aloud": "Touchez pour écouter l'histoire à voix haute",
    "Try a Different Tone?": "Essayer un Ton Différent ?",
    "How Should This Dream Feel?": "Quelle Ambiance pour ce Rêve ?",
    "Narrating!": "Narration !",
    "Narrate Again": "Raconter à Nouveau",
    "Narrate": "Raconter",
    "Delete Dream": "Supprimer le Rêve",
    "Dream": "Rêve",
    "Delete this dream?": "Supprimer ce rêve ?",
    "This will permanently remove this dream and all its content.": "Cela supprimera définitivement ce rêve et tout son contenu.",

    // MARK: - Tones
    "Happy": "Joyeux",
    "Funny": "Drôle",
    "Hopeful": "Plein d'espoir",
    "Calm": "Calme",
    "Positive": "Positif",

    // MARK: - Dream Analysis
    "Time Period": "Période",
    "Period": "Période",
    "Emotion Trends": "Tendances Émotionnelles",
    "Loading trends...": "Chargement des tendances...",
    "Loading summary...": "Chargement du résumé...",
    "Summary": "Résumé",
    "Most Common Feeling": "Émotion la Plus Fréquente",
    "Average intensity: %.0f%%": "Intensité moyenne : %.0f%%",
    "dreams": "rêves",
    "Suggested Moods": "Ambiances Suggérées",
    "Activity": "Activité",
    "Keep logging dreams to see trends": "Continuez à enregistrer vos rêves pour voir les tendances",
    "Record your first dream to start tracking your emotions": "Enregistrez votre premier rêve pour commencer à suivre vos émotions",
    "ZAP!": "ZAP !",
    "OOPS!": "OUPS !",

    // MARK: - Settings
    "Signed in": "Connecté",
    "Cloud sync enabled": "Synchronisation cloud activée",
    "Sign In / Sign Up": "Se Connecter / S'inscrire",
    "Create an account to sync dreams and AI content.": "Créez un compte pour synchroniser vos rêves et contenus IA.",
    "Notifications": "Notifications",
    "Notification Settings": "Paramètres de Notifications",
    "Settings": "Paramètres",
    "Dream Character": "Personnage du Rêve",
    "These details personalize your dream comics": "Ces détails personnalisent vos bandes dessinées de rêves",
    "Sign Out": "Se Déconnecter",
    "Gender": "Genre",
    "Male": "Homme",
    "Female": "Femme",
    "Non-binary": "Non binaire",
    "Prefer not to say": "Préfère ne pas dire",
    "Language": "Langue",

    // MARK: - Dream Visualization
    "Dream Visualization": "Visualisation du Rêve",
    "AI creates a comic page from your dream": "L'IA crée une page de BD à partir de votre rêve",
    "Include my likeness": "Inclure mon apparence",
    "OFFLINE!": "HORS LIGNE !",
    "Image generation requires Apple Silicon or sign-in.": "La génération d'images nécessite Apple Silicon ou une connexion.",
    "Draw my dream!": "Dessine mon rêve !",
    "Redraw my dream!": "Redessine mon rêve !",
    "Regenerate as Comic Page": "Régénérer en Page de BD",
    "CREATING!": "CRÉATION !",
    "Painting your dream...": "Peinture de votre rêve...",
    "Add your details in Profile to appear in your dreams!": "Ajoutez vos détails dans le Profil pour apparaître dans vos rêves !",
    "Scene %d": "Scène %d",
    "Save your dreams!": "Sauvegardez vos rêves !",
    "Sign up to sync rewrites and comics across devices.": "Inscrivez-vous pour synchroniser les réécritures et BD sur tous vos appareils.",
    "Dream Sequence": "Séquence de Rêve",
    "Dream Comic Page": "Page BD du Rêve",

    // MARK: - Notifications
    "Notifications Enabled": "Notifications Activées",
    "Enable Notifications": "Activer les Notifications",
    "Permission": "Permission",
    "Allow notifications to receive reminders and follow-ups.": "Autorisez les notifications pour recevoir des rappels et des suivis.",
    "Notification Types": "Types de Notifications",
    "Configure each notification type independently with its own schedule.": "Configurez chaque type de notification indépendamment avec son propre calendrier.",
    "Permission Required": "Permission Requise",
    "Open Settings": "Ouvrir les Paramètres",
    "Please enable notifications in Settings to receive reminders.": "Veuillez activer les notifications dans les Paramètres pour recevoir des rappels.",
    "When to Notify": "Quand Notifier",
    "Time of Day": "Heure du Jour",
    "Day of Week": "Jour de la Semaine",
    "Select Days": "Sélectionner les Jours",
    "Preview": "Aperçu",
    "Frequency": "Fréquence",
    "Time": "Heure",
    "Day": "Jour",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Vous recevrez une notification chaque jour à %@.",
    "You'll receive notifications Monday through Friday at %@.": "Vous recevrez des notifications du lundi au vendredi à %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Vous recevrez des notifications samedi et dimanche à %@.",
    "You'll receive a notification every %@ at %@.": "Vous recevrez une notification chaque %@ à %@.",
    "Select at least one day to receive notifications.": "Sélectionnez au moins un jour pour recevoir des notifications.",
    "You'll receive notifications on %@ at %@.": "Vous recevrez des notifications le %@ à %@.",

    // MARK: - Dream Reminders
    "Reminders": "Rappels",
    "No reminders set": "Aucun rappel défini",
    "Add a reminder to revisit this dream": "Ajoutez un rappel pour revisiter ce rêve",
    "EXPIRED": "EXPIRÉ",
    "REMINDER TYPE": "TYPE DE RAPPEL",
    "WHEN": "QUAND",
    "PREVIEW": "APERÇU",
    "Custom": "Personnalisé",
    "Add Reminder": "Ajouter un Rappel",
    "Date & Time": "Date et Heure",
    "1 hour": "1 heure",
    "6 hours": "6 heures",
    "Tomorrow": "Demain",
    "2 days": "2 jours",
    "1 week": "1 semaine",
    "You'll receive a \"%@\" reminder on %@": "Vous recevrez un rappel \"%@\" le %@",

    // MARK: - Avatar
    "Use This Photo": "Utiliser Cette Photo",
    "Use Memoji": "Utiliser Memoji",
    "Choose Photo": "Choisir une Photo",
    "Take Photo": "Prendre une Photo",
    "Remove Avatar": "Supprimer l'Avatar",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Votre photo crée une description textuelle de votre apparence. La photo elle-même n'est pas partagée avec les services IA.",
    "Profile Picture": "Photo de Profil",
    "Paste Your Memoji": "Collez Votre Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Touchez le champ de texte ci-dessous\n2. Passez au clavier Memoji\n3. Touchez votre autocollant Memoji préféré",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Touchez ici, puis collez Memoji...",
    "Uploading...": "Envoi en cours...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Nous suggérons de réécrire ceci comme un rêve ",
    " dream": "",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Peur",
    "Sadness": "Tristesse",
    "Anger": "Colère",
    "Anxiety": "Anxiété",
    "Stress": "Stress",
    "Loneliness": "Solitude",
    "Helplessness": "Impuissance",
    "Shame": "Honte",
    "Grief": "Deuil",
    "Confusion": "Confusion",
    "Joy": "Joie",
    "Love": "Amour",
    "Surprise": "Surprise",
    "Disgust": "Dégoût",
    "Trust": "Confiance",
    "Anticipation": "Anticipation",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Paisible",
    "Serene": "Serein",
    "Humorous": "Humoristique",
    "Lighthearted": "Léger",
    "Empowering": "Stimulant",
    "Confident": "Confiant",
    "Optimistic": "Optimiste",
    "Inspiring": "Inspirant",
    "Joyful": "Joyeux",
    "Cheerful": "Enjoué",
    "Neutral": "Neutre",

    // MARK: - Trend Directions
    "Improving": "En amélioration",
    "Worsening": "En détérioration",
    "Stable": "Stable",

    // MARK: - Analysis Periods
    "7 Days": "7 Jours",
    "30 Days": "30 Jours",
    "90 Days": "90 Jours",
    "All": "Tout",

    // MARK: - Notification Categories
    "Daily Check-in": "Bilan Quotidien",
    "Dream Reflection": "Réflexion sur les Rêves",
    "Nightmare Follow-up": "Suivi des Cauchemars",
    "Weekly Digest": "Résumé Hebdomadaire",
    "Gentle reminder to log your dreams": "Rappel amical pour enregistrer vos rêves",
    "Reflect on dreams you've recorded": "Réfléchissez aux rêves que vous avez enregistrés",
    "Check in after rewriting a nightmare": "Faites le point après avoir réécrit un cauchemar",
    "Weekly summary of your dream journey": "Résumé hebdomadaire de votre parcours onirique",

    // MARK: - Notification Frequencies
    "Every Day": "Chaque Jour",
    "Weekdays Only": "Jours de Semaine Uniquement",
    "Weekends Only": "Week-ends Uniquement",
    "Once a Week": "Une Fois par Semaine",
    "Custom Days": "Jours Personnalisés",

    // MARK: - Day Names
    "Sun": "Dim",
    "Mon": "Lun",
    "Tue": "Mar",
    "Wed": "Mer",
    "Thu": "Jeu",
    "Fri": "Ven",
    "Sat": "Sam",

    // MARK: - Notification Templates
    "Good morning!": "Bonjour !",
    "Dream Journal Time": "L'Heure du Journal des Rêves",
    "Remember Your Dreams?": "Vous Souvenez-vous de vos Rêves ?",
    "Start Your Day Mindfully": "Commencez Votre Journée en Pleine Conscience",
    "Did you dream last night? Take a moment to record it.": "Avez-vous rêvé la nuit dernière ? Prenez un moment pour l'enregistrer.",
    "Your dreams are waiting to be captured.": "Vos rêves attendent d'être capturés.",
    "A few minutes to log your dreams can make a big difference.": "Quelques minutes pour enregistrer vos rêves peuvent faire une grande différence.",
    "Dreams fade quickly - save yours now.": "Les rêves s'estompent vite - sauvegardez les vôtres maintenant.",
    "Time to Reflect": "Temps de Réfléchir",
    "Dream Insight": "Aperçu Onirique",
    "Look Back": "Regard en Arrière",
    "Your Dream Journey": "Votre Parcours Onirique",
    "Revisit a dream you recorded and see how it makes you feel now.": "Revisitez un rêve que vous avez enregistré et voyez comment il vous fait sentir maintenant.",
    "Your past dreams might hold insights for today.": "Vos rêves passés pourraient contenir des révélations pour aujourd'hui.",
    "Take a moment to reflect on your dream patterns.": "Prenez un moment pour réfléchir à vos schémas oniriques.",
    "What have your dreams been telling you lately?": "Que vous ont raconté vos rêves dernièrement ?",
    "How Are You Feeling?": "Comment Vous Sentez-vous ?",
    "Gentle Check-in": "Bilan en Douceur",
    "You're Doing Great": "Vous Vous en Sortez Très Bien",
    "Healing Journey": "Parcours de Guérison",
    "How did the rewritten dream make you feel? Consider reading it again.": "Comment le rêve réécrit vous a-t-il fait sentir ? Pensez à le relire.",
    "Remember, you have the power to reshape your dreams.": "Rappelez-vous, vous avez le pouvoir de transformer vos rêves.",
    "Take a moment to revisit your peaceful dream version.": "Prenez un moment pour revisiter la version paisible de votre rêve.",
    "Your healing journey continues. We're here for you.": "Votre parcours de guérison continue. Nous sommes là pour vous.",
    "Your Week in Dreams": "Votre Semaine en Rêves",
    "Weekly Reflection": "Réflexion Hebdomadaire",
    "Dream Summary": "Résumé des Rêves",
    "This Week's Journey": "Le Parcours de Cette Semaine",
    "See how your dream patterns evolved this week.": "Découvrez comment vos schémas oniriques ont évolué cette semaine.",
    "Time for your weekly dream check-in.": "C'est l'heure de votre bilan hebdomadaire des rêves.",
    "Reflect on your dream journey this week.": "Réfléchissez à votre parcours onirique cette semaine.",
    "A week of dreams - what stories did they tell?": "Une semaine de rêves - quelles histoires ont-ils racontées ?",
]
