// Persian (fa)

let strings_fa: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "ورود!",
    "SIGN UP!": "ثبت‌نام!",
    "Account": "حساب کاربری",
    "Email": "ایمیل",
    "Password": "رمز عبور",
    "Profile": "پروفایل",
    "Age": "سن",
    "Timezone (e.g., %@)": "منطقه زمانی (مثلاً %@)",
    "LOADING!": "در حال بارگذاری!",
    "Log In": "ورود",
    "Create Account": "ایجاد حساب کاربری",
    "Need an account?": "به حساب کاربری نیاز دارید؟",
    "Have an account?": "حساب کاربری دارید؟",
    "Sign Up": "ثبت‌نام",

    // MARK: - Content / Main
    "No dreams match your search": "هیچ رویایی با جستجوی شما مطابقت ندارد",
    "Dreams": "رویاها",
    "Search dreams...": "جستجوی رویاها...",
    "Welcome, Dreamer!": "خوش آمدید، رویاپرداز!",
    "DREAM ON!": "به رویاپردازی ادامه بده!",
    "Record your first dream to begin your comic journey!": "اولین رویای خود را ثبت کنید تا سفر داستان مصور شما آغاز شود!",
    "Capture a Dream": "ثبت یک رویا",
    "DELETE": "حذف",

    // MARK: - New Dream
    "What did you dream?": "چه رویایی دیدید؟",
    "Describe your dream or nightmare...": "رویا یا کابوس خود را توصیف کنید...",
    "Stop Recording": "توقف ضبط",
    "Record Dream": "ضبط رویا",
    "Tap to stop voice recording": "برای توقف ضبط صدا لمس کنید",
    "Tap to start describing your dream with your voice": "برای شروع توصیف رویای خود با صدایتان لمس کنید",
    "Listening...": "در حال شنیدن...",
    "When did you see this dream?": "این رویا را چه زمانی دیدید؟",
    "Save Dream": "ذخیره رویا",
    "New Dream": "رویای جدید",

    // MARK: - Common Actions
    "Cancel": "لغو",
    "Save": "ذخیره",
    "Edit": "ویرایش",
    "Delete": "حذف",
    "Done": "انجام شد",
    "Try Again": "دوباره تلاش کنید",
    "Retry": "تلاش مجدد",
    "Add": "افزودن",
    "View": "مشاهده",

    // MARK: - Dream Detail
    "Dream date": "تاریخ رویا",
    "Original Dream": "رویای اصلی",
    "Dream Analysis": "تحلیل رویا",
    "ANALYZING!": "در حال تحلیل!",
    "Rewritten Dream (%@)": "رویای بازنویسی‌شده (%@)",
    "Stop": "توقف",
    "Play Story": "پخش داستان",
    "Tap to stop reading the story": "برای توقف خواندن داستان لمس کنید",
    "Tap to hear the story read aloud": "برای شنیدن داستان با صدای بلند لمس کنید",
    "Try a Different Tone?": "می‌خواهید لحن دیگری امتحان کنید؟",
    "How Should This Dream Feel?": "این رویا چه حسی باید داشته باشد؟",
    "Narrating!": "در حال روایت!",
    "Narrate Again": "روایت مجدد",
    "Narrate": "روایت",
    "Delete Dream": "حذف رویا",
    "Dream": "رویا",
    "Delete this dream?": "آیا این رویا حذف شود؟",
    "This will permanently remove this dream and all its content.": "این کار رویا و تمام محتوای آن را برای همیشه حذف خواهد کرد.",

    // MARK: - Tones
    "Happy": "شاد",
    "Funny": "خنده‌دار",
    "Hopeful": "امیدوارکننده",
    "Calm": "آرام",
    "Positive": "مثبت",

    // MARK: - Dream Analysis
    "Time Period": "بازه زمانی",
    "Period": "دوره",
    "Emotion Trends": "روند احساسات",
    "Loading trends...": "در حال بارگذاری روندها...",
    "Loading summary...": "در حال بارگذاری خلاصه...",
    "Summary": "خلاصه",
    "Most Common Feeling": "رایج‌ترین احساس",
    "Average intensity: %.0f%%": "میانگین شدت: %.0f%%",
    "dreams": "رویاها",
    "Suggested Moods": "حالات پیشنهادی",
    "Activity": "فعالیت",
    "Keep logging dreams to see trends": "به ثبت رویاها ادامه دهید تا روندها را ببینید",
    "Record your first dream to start tracking your emotions": "اولین رویای خود را ثبت کنید تا ردیابی احساسات شما آغاز شود",
    "ZAP!": "زاپ!",
    "OOPS!": "اوه!",

    // MARK: - Settings
    "Signed in": "وارد شده‌اید",
    "Cloud sync enabled": "همگام‌سازی ابری فعال است",
    "Sign In / Sign Up": "ورود / ثبت‌نام",
    "Create an account to sync dreams and AI content.": "یک حساب کاربری بسازید تا رویاها و محتوای هوش مصنوعی همگام‌سازی شوند.",
    "Notifications": "اعلان‌ها",
    "Notification Settings": "تنظیمات اعلان‌ها",
    "Settings": "تنظیمات",
    "Dream Character": "شخصیت رویا",
    "These details personalize your dream comics": "این جزئیات داستان‌های مصور رویای شما را شخصی‌سازی می‌کنند",
    "Sign Out": "خروج",
    "Gender": "جنسیت",
    "Male": "مرد",
    "Female": "زن",
    "Non-binary": "غیردودویی",
    "Prefer not to say": "ترجیح می‌دهم نگویم",
    "Language": "زبان",

    // MARK: - Dream Visualization
    "Dream Visualization": "تصویرسازی رویا",
    "AI creates a comic page from your dream": "هوش مصنوعی یک صفحه داستان مصور از رویای شما می‌سازد",
    "Include my likeness": "شامل چهره من باشد",
    "OFFLINE!": "آفلاین!",
    "Image generation requires Apple Silicon or sign-in.": "ساخت تصویر به پردازنده Apple Silicon یا ورود به حساب نیاز دارد.",
    "Draw my dream!": "رویای مرا بکش!",
    "Redraw my dream!": "رویای مرا دوباره بکش!",
    "Regenerate as Comic Page": "بازسازی به صورت صفحه مصور",
    "CREATING!": "در حال ساخت!",
    "Painting your dream...": "در حال نقاشی رویای شما...",
    "Add your details in Profile to appear in your dreams!": "جزئیات خود را در پروفایل اضافه کنید تا در رویاهایتان ظاهر شوید!",
    "Scene %d": "صحنه %d",
    "Save your dreams!": "رویاهایتان را ذخیره کنید!",
    "Sign up to sync rewrites and comics across devices.": "ثبت‌نام کنید تا بازنویسی‌ها و داستان‌های مصور در همه دستگاه‌ها همگام‌سازی شوند.",
    "Dream Sequence": "توالی رویا",
    "Dream Comic Page": "صفحه مصور رویا",

    // MARK: - Notifications
    "Notifications Enabled": "اعلان‌ها فعال هستند",
    "Enable Notifications": "فعال‌سازی اعلان‌ها",
    "Permission": "مجوز",
    "Allow notifications to receive reminders and follow-ups.": "اعلان‌ها را مجاز کنید تا یادآوری‌ها و پیگیری‌ها را دریافت کنید.",
    "Notification Types": "انواع اعلان‌ها",
    "Configure each notification type independently with its own schedule.": "هر نوع اعلان را به صورت مستقل با زمان‌بندی خاص خود تنظیم کنید.",
    "Permission Required": "مجوز لازم است",
    "Open Settings": "باز کردن تنظیمات",
    "Please enable notifications in Settings to receive reminders.": "لطفاً اعلان‌ها را در تنظیمات فعال کنید تا یادآوری‌ها را دریافت کنید.",
    "When to Notify": "زمان اعلان",
    "Time of Day": "ساعت روز",
    "Day of Week": "روز هفته",
    "Select Days": "انتخاب روزها",
    "Preview": "پیش‌نمایش",
    "Frequency": "تکرار",
    "Time": "زمان",
    "Day": "روز",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "هر روز در ساعت %@ یک اعلان دریافت خواهید کرد.",
    "You'll receive notifications Monday through Friday at %@.": "از دوشنبه تا جمعه در ساعت %@ اعلان دریافت خواهید کرد.",
    "You'll receive notifications on Saturday and Sunday at %@.": "شنبه و یکشنبه در ساعت %@ اعلان دریافت خواهید کرد.",
    "You'll receive a notification every %@ at %@.": "هر %@ در ساعت %@ یک اعلان دریافت خواهید کرد.",
    "Select at least one day to receive notifications.": "حداقل یک روز را برای دریافت اعلان انتخاب کنید.",
    "You'll receive notifications on %@ at %@.": "روز %@ در ساعت %@ اعلان دریافت خواهید کرد.",

    // MARK: - Dream Reminders
    "Reminders": "یادآوری‌ها",
    "No reminders set": "یادآوری تنظیم نشده است",
    "Add a reminder to revisit this dream": "یک یادآوری اضافه کنید تا به این رویا بازگردید",
    "EXPIRED": "منقضی شده",
    "REMINDER TYPE": "نوع یادآوری",
    "WHEN": "چه زمانی",
    "PREVIEW": "پیش‌نمایش",
    "Custom": "سفارشی",
    "Add Reminder": "افزودن یادآوری",
    "Date & Time": "تاریخ و زمان",
    "1 hour": "۱ ساعت",
    "6 hours": "۶ ساعت",
    "Tomorrow": "فردا",
    "2 days": "۲ روز",
    "1 week": "۱ هفته",
    "You'll receive a \"%@\" reminder on %@": "یادآوری \"%@\" را در %@ دریافت خواهید کرد",

    // MARK: - Avatar
    "Use This Photo": "استفاده از این عکس",
    "Use Memoji": "استفاده از Memoji",
    "Choose Photo": "انتخاب عکس",
    "Take Photo": "گرفتن عکس",
    "Remove Avatar": "حذف تصویر نمایه",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "عکس شما یک توصیف متنی از ظاهرتان ایجاد می‌کند. خود عکس با خدمات هوش مصنوعی به اشتراک گذاشته نمی‌شود.",
    "Profile Picture": "تصویر پروفایل",
    "Paste Your Memoji": "Memoji خود را بچسبانید",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. روی فیلد متنی زیر لمس کنید\n2. به صفحه‌کلید Memoji بروید\n3. برچسب Memoji مورد علاقه خود را لمس کنید",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "اینجا لمس کنید، سپس Memoji بچسبانید...",
    "Uploading...": "در حال بارگذاری...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "پیشنهاد می‌کنیم این را به صورت یک رویای ",
    " dream": " بازنویسی کنید",

    // MARK: - Emotions (from backend analysis)
    "Fear": "ترس",
    "Sadness": "غم",
    "Anger": "خشم",
    "Anxiety": "اضطراب",
    "Stress": "استرس",
    "Loneliness": "تنهایی",
    "Helplessness": "درماندگی",
    "Shame": "شرم",
    "Grief": "سوگ",
    "Confusion": "سردرگمی",
    "Joy": "شادی",
    "Love": "عشق",
    "Surprise": "شگفتی",
    "Disgust": "انزجار",
    "Trust": "اعتماد",
    "Anticipation": "پیش‌بینی",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "آرام",
    "Serene": "آسوده",
    "Humorous": "طنزآمیز",
    "Lighthearted": "سبک‌دل",
    "Empowering": "توانمندساز",
    "Confident": "مطمئن",
    "Optimistic": "خوش‌بین",
    "Inspiring": "الهام‌بخش",
    "Joyful": "شادمان",
    "Cheerful": "سرحال",
    "Neutral": "خنثی",

    // MARK: - Trend Directions
    "Improving": "در حال بهبود",
    "Worsening": "در حال بدتر شدن",
    "Stable": "پایدار",

    // MARK: - Analysis Periods
    "7 Days": "۷ روز",
    "30 Days": "۳۰ روز",
    "90 Days": "۹۰ روز",
    "All": "همه",

    // MARK: - Notification Categories
    "Daily Check-in": "گزارش روزانه",
    "Dream Reflection": "تأمل در رویاها",
    "Nightmare Follow-up": "پیگیری کابوس",
    "Weekly Digest": "خلاصه هفتگی",
    "Gentle reminder to log your dreams": "یادآوری ملایم برای ثبت رویاهایتان",
    "Reflect on dreams you've recorded": "در رویاهایی که ثبت کرده‌اید تأمل کنید",
    "Check in after rewriting a nightmare": "پس از بازنویسی یک کابوس وضعیت خود را بررسی کنید",
    "Weekly summary of your dream journey": "خلاصه هفتگی سفر رویایی شما",

    // MARK: - Notification Frequencies
    "Every Day": "هر روز",
    "Weekdays Only": "فقط روزهای کاری",
    "Weekends Only": "فقط آخر هفته",
    "Once a Week": "هفته‌ای یک بار",
    "Custom Days": "روزهای سفارشی",

    // MARK: - Day Names
    "Sun": "یک",
    "Mon": "دو",
    "Tue": "سه",
    "Wed": "چها",
    "Thu": "پنج",
    "Fri": "جمع",
    "Sat": "شنب",

    // MARK: - Notification Templates
    "Good morning!": "صبح بخیر!",
    "Dream Journal Time": "زمان دفتر خاطرات رویا",
    "Remember Your Dreams?": "رویاهایتان را به یاد دارید؟",
    "Start Your Day Mindfully": "روز خود را با آگاهی آغاز کنید",
    "Did you dream last night? Take a moment to record it.": "دیشب رویایی دیدید؟ لحظه‌ای وقت بگذارید و آن را ثبت کنید.",
    "Your dreams are waiting to be captured.": "رویاهای شما منتظر ثبت شدن هستند.",
    "A few minutes to log your dreams can make a big difference.": "چند دقیقه برای ثبت رویاهایتان می‌تواند تفاوت بزرگی ایجاد کند.",
    "Dreams fade quickly - save yours now.": "رویاها به سرعت محو می‌شوند - همین الان رویاهایتان را ذخیره کنید.",
    "Time to Reflect": "زمان تأمل",
    "Dream Insight": "بینش رویا",
    "Look Back": "نگاهی به گذشته",
    "Your Dream Journey": "سفر رویایی شما",
    "Revisit a dream you recorded and see how it makes you feel now.": "به رویایی که ثبت کرده‌اید بازگردید و ببینید الان چه حسی به شما می‌دهد.",
    "Your past dreams might hold insights for today.": "رویاهای گذشته شما ممکن است بینش‌هایی برای امروز داشته باشند.",
    "Take a moment to reflect on your dream patterns.": "لحظه‌ای وقت بگذارید و در الگوهای رویاهایتان تأمل کنید.",
    "What have your dreams been telling you lately?": "رویاهایتان اخیراً چه چیزی به شما می‌گویند؟",
    "How Are You Feeling?": "حالتان چطور است؟",
    "Gentle Check-in": "احوال‌پرسی ملایم",
    "You're Doing Great": "عالی پیش می‌روید",
    "Healing Journey": "سفر شفا",
    "How did the rewritten dream make you feel? Consider reading it again.": "رویای بازنویسی‌شده چه حسی به شما داد؟ دوباره خواندن آن را در نظر بگیرید.",
    "Remember, you have the power to reshape your dreams.": "به یاد داشته باشید، شما قدرت بازآفرینی رویاهایتان را دارید.",
    "Take a moment to revisit your peaceful dream version.": "لحظه‌ای وقت بگذارید و نسخه آرام رویایتان را دوباره بخوانید.",
    "Your healing journey continues. We're here for you.": "سفر شفای شما ادامه دارد. ما در کنار شما هستیم.",
    "Your Week in Dreams": "هفته شما در رویاها",
    "Weekly Reflection": "تأمل هفتگی",
    "Dream Summary": "خلاصه رویاها",
    "This Week's Journey": "سفر این هفته",
    "See how your dream patterns evolved this week.": "ببینید الگوهای رویاهایتان این هفته چگونه تغییر کرده‌اند.",
    "Time for your weekly dream check-in.": "زمان بررسی هفتگی رویاهای شماست.",
    "Reflect on your dream journey this week.": "در سفر رویایی خود این هفته تأمل کنید.",
    "A week of dreams - what stories did they tell?": "یک هفته رویا - چه داستان‌هایی روایت کردند؟",
]
