// Turkish (tr)

let strings_tr: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "GİRİŞ YAP!",
    "SIGN UP!": "KAYIT OL!",
    "Account": "Hesap",
    "Email": "E-posta",
    "Password": "Şifre",
    "Profile": "Profil",
    "Age": "Yaş",
    "Timezone (e.g., %@)": "Saat dilimi (ör., %@)",
    "LOADING!": "YÜKLENİYOR!",
    "Log In": "Giriş Yap",
    "Create Account": "Hesap Oluştur",
    "Need an account?": "Hesabınız yok mu?",
    "Have an account?": "Hesabınız var mı?",
    "Sign Up": "Kayıt Ol",

    // MARK: - Content / Main
    "No dreams match your search": "Aramanızla eşleşen rüya bulunamadı",
    "Dreams": "Rüyalar",
    "Search dreams...": "Rüya ara...",
    "Welcome, Dreamer!": "Hoş geldin, Hayalperest!",
    "DREAM ON!": "HAYAL ET!",
    "Record your first dream to begin your comic journey!": "Çizgi roman yolculuğunuza başlamak için ilk rüyanızı kaydedin!",
    "Capture a Dream": "Bir Rüya Yakala",
    "DELETE": "SİL",

    // MARK: - New Dream
    "What did you dream?": "Ne rüyası gördün?",
    "Describe your dream or nightmare...": "Rüyanızı veya kabusunuzu anlatın...",
    "Stop Recording": "Kaydı Durdur",
    "Record Dream": "Rüya Kaydet",
    "Tap to stop voice recording": "Ses kaydını durdurmak için dokunun",
    "Tap to start describing your dream with your voice": "Rüyanızı sesinizle anlatmaya başlamak için dokunun",
    "Listening...": "Dinliyor...",
    "When did you see this dream?": "Bu rüyayı ne zaman gördünüz?",
    "Save Dream": "Rüyayı Kaydet",
    "New Dream": "Yeni Rüya",

    // MARK: - Common Actions
    "Cancel": "İptal",
    "Save": "Kaydet",
    "Edit": "Düzenle",
    "Delete": "Sil",
    "Done": "Tamam",
    "Try Again": "Tekrar Dene",
    "Retry": "Yeniden Dene",
    "Add": "Ekle",
    "View": "Görüntüle",

    // MARK: - Dream Detail
    "Dream date": "Rüya tarihi",
    "Original Dream": "Orijinal Rüya",
    "Dream Analysis": "Rüya Analizi",
    "ANALYZING!": "ANALİZ EDİLİYOR!",
    "Rewritten Dream (%@)": "Yeniden Yazılmış Rüya (%@)",
    "Stop": "Durdur",
    "Play Story": "Hikayeyi Oynat",
    "Tap to stop reading the story": "Hikaye okumayı durdurmak için dokunun",
    "Tap to hear the story read aloud": "Hikayeyi sesli dinlemek için dokunun",
    "Try a Different Tone?": "Farklı Bir Ton Deneyin?",
    "How Should This Dream Feel?": "Bu Rüya Nasıl Hissettirmeli?",
    "Narrating!": "Anlatılıyor!",
    "Narrate Again": "Tekrar Anlat",
    "Narrate": "Anlat",
    "Delete Dream": "Rüyayı Sil",
    "Dream": "Rüya",
    "Delete this dream?": "Bu rüyayı silmek istiyor musunuz?",
    "This will permanently remove this dream and all its content.": "Bu, rüyayı ve tüm içeriğini kalıcı olarak silecektir.",

    // MARK: - Tones
    "Happy": "Mutlu",
    "Funny": "Komik",
    "Hopeful": "Umut Dolu",
    "Calm": "Sakin",
    "Positive": "Olumlu",

    // MARK: - Dream Analysis
    "Time Period": "Zaman Aralığı",
    "Period": "Dönem",
    "Emotion Trends": "Duygu Eğilimleri",
    "Loading trends...": "Eğilimler yükleniyor...",
    "Loading summary...": "Özet yükleniyor...",
    "Summary": "Özet",
    "Most Common Feeling": "En Yaygın Duygu",
    "Average intensity: %.0f%%": "Ortalama yoğunluk: %.0f%%",
    "dreams": "rüyalar",
    "Suggested Moods": "Önerilen Ruh Halleri",
    "Activity": "Etkinlik",
    "Keep logging dreams to see trends": "Eğilimleri görmek için rüya kaydetmeye devam edin",
    "Record your first dream to start tracking your emotions": "Duygularınızı takip etmeye başlamak için ilk rüyanızı kaydedin",
    "ZAP!": "ÇAK!",
    "OOPS!": "HAY ALLAH!",

    // MARK: - Settings
    "Signed in": "Giriş yapıldı",
    "Cloud sync enabled": "Bulut senkronizasyonu etkin",
    "Sign In / Sign Up": "Giriş Yap / Kayıt Ol",
    "Create an account to sync dreams and AI content.": "Rüyaları ve AI içeriğini senkronize etmek için bir hesap oluşturun.",
    "Notifications": "Bildirimler",
    "Notification Settings": "Bildirim Ayarları",
    "Settings": "Ayarlar",
    "Dream Character": "Rüya Karakteri",
    "These details personalize your dream comics": "Bu bilgiler rüya çizgi romanlarınızı kişiselleştirir",
    "Sign Out": "Çıkış Yap",
    "Gender": "Cinsiyet",
    "Male": "Erkek",
    "Female": "Kadın",
    "Non-binary": "Non-binary",
    "Prefer not to say": "Belirtmek istemiyorum",
    "Language": "Dil",

    // MARK: - Dream Visualization
    "Dream Visualization": "Rüya Görselleştirme",
    "AI creates a comic page from your dream": "AI rüyanızdan bir çizgi roman sayfası oluşturur",
    "Include my likeness": "Benzerliğimi dahil et",
    "OFFLINE!": "ÇEVRİMDIŞI!",
    "Image generation requires Apple Silicon or sign-in.": "Görsel oluşturma Apple Silicon veya giriş yapılmasını gerektirir.",
    "Draw my dream!": "Rüyamı çiz!",
    "Redraw my dream!": "Rüyamı yeniden çiz!",
    "Regenerate as Comic Page": "Çizgi Roman Sayfası Olarak Yeniden Oluştur",
    "CREATING!": "OLUŞTURULUYOR!",
    "Painting your dream...": "Rüyanız çiziliyor...",
    "Add your details in Profile to appear in your dreams!": "Rüyalarınızda görünmek için Profil'e bilgilerinizi ekleyin!",
    "Scene %d": "Sahne %d",
    "Save your dreams!": "Rüyalarınızı kaydedin!",
    "Sign up to sync rewrites and comics across devices.": "Yeniden yazımları ve çizgi romanları cihazlar arası senkronize etmek için kayıt olun.",
    "Dream Sequence": "Rüya Dizisi",
    "Dream Comic Page": "Rüya Çizgi Roman Sayfası",

    // MARK: - Notifications
    "Notifications Enabled": "Bildirimler Etkin",
    "Enable Notifications": "Bildirimleri Etkinleştir",
    "Permission": "İzin",
    "Allow notifications to receive reminders and follow-ups.": "Hatırlatmalar ve takipler almak için bildirimlere izin verin.",
    "Notification Types": "Bildirim Türleri",
    "Configure each notification type independently with its own schedule.": "Her bildirim türünü kendi programıyla bağımsız olarak yapılandırın.",
    "Permission Required": "İzin Gerekli",
    "Open Settings": "Ayarları Aç",
    "Please enable notifications in Settings to receive reminders.": "Hatırlatmalar almak için lütfen Ayarlar'dan bildirimleri etkinleştirin.",
    "When to Notify": "Ne Zaman Bildirilsin",
    "Time of Day": "Günün Saati",
    "Day of Week": "Haftanın Günü",
    "Select Days": "Gün Seçin",
    "Preview": "Önizleme",
    "Frequency": "Sıklık",
    "Time": "Saat",
    "Day": "Gün",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Her gün saat %@ bildiri alacaksınız.",
    "You'll receive notifications Monday through Friday at %@.": "Pazartesiden Cumaya kadar saat %@ bildirim alacaksınız.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Cumartesi ve Pazar günleri saat %@ bildirim alacaksınız.",
    "You'll receive a notification every %@ at %@.": "Her %@ saat %@ bildirim alacaksınız.",
    "Select at least one day to receive notifications.": "Bildirim almak için en az bir gün seçin.",
    "You'll receive notifications on %@ at %@.": "%@ günleri saat %@ bildirim alacaksınız.",

    // MARK: - Dream Reminders
    "Reminders": "Hatırlatmalar",
    "No reminders set": "Hatırlatma ayarlanmadı",
    "Add a reminder to revisit this dream": "Bu rüyayı tekrar ziyaret etmek için hatırlatma ekleyin",
    "EXPIRED": "SÜRESİ DOLMUŞ",
    "REMINDER TYPE": "HATIRLATMA TÜRÜ",
    "WHEN": "NE ZAMAN",
    "PREVIEW": "ÖNİZLEME",
    "Custom": "Özel",
    "Add Reminder": "Hatırlatma Ekle",
    "Date & Time": "Tarih ve Saat",
    "1 hour": "1 saat",
    "6 hours": "6 saat",
    "Tomorrow": "Yarın",
    "2 days": "2 gün",
    "1 week": "1 hafta",
    "You'll receive a \"%@\" reminder on %@": "%@ tarihinde \"%@\" hatırlatması alacaksınız",

    // MARK: - Avatar
    "Use This Photo": "Bu Fotoğrafı Kullan",
    "Use Memoji": "Memoji Kullan",
    "Choose Photo": "Fotoğraf Seç",
    "Take Photo": "Fotoğraf Çek",
    "Remove Avatar": "Avatarı Kaldır",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Fotoğrafınız görünümünüzün metin açıklamasını oluşturur. Fotoğrafın kendisi AI hizmetleriyle paylaşılmaz.",
    "Profile Picture": "Profil Fotoğrafı",
    "Paste Your Memoji": "Memoji'nizi Yapıştırın",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Aşağıdaki metin alanına dokunun\n2. Memoji klavyesine geçin\n3. Favori Memoji çıkartmanıza dokunun",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Buraya dokunun, ardından Memoji yapıştırın...",
    "Uploading...": "Yükleniyor...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Bunu şu şekilde yeniden yazmayı öneriyoruz: ",
    " dream": " rüya",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Korku",
    "Sadness": "Hüzün",
    "Anger": "Öfke",
    "Anxiety": "Kaygı",
    "Stress": "Stres",
    "Loneliness": "Yalnızlık",
    "Helplessness": "Çaresizlik",
    "Shame": "Utanç",
    "Grief": "Yas",
    "Confusion": "Kafa karışıklığı",
    "Joy": "Sevinç",
    "Love": "Aşk",
    "Surprise": "Sürpriz",
    "Disgust": "Tiksinti",
    "Trust": "Güven",
    "Anticipation": "Beklenti",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Huzurlu",
    "Serene": "Sakin",
    "Humorous": "Esprili",
    "Lighthearted": "Neşeli",
    "Empowering": "Güçlendirici",
    "Confident": "Kendinden emin",
    "Optimistic": "İyimser",
    "Inspiring": "İlham verici",
    "Joyful": "Sevinçli",
    "Cheerful": "Şen",
    "Neutral": "Nötr",

    // MARK: - Trend Directions
    "Improving": "İyileşiyor",
    "Worsening": "Kötüleşiyor",
    "Stable": "Sabit",

    // MARK: - Analysis Periods
    "7 Days": "7 Gün",
    "30 Days": "30 Gün",
    "90 Days": "90 Gün",
    "All": "Tümü",

    // MARK: - Notification Categories
    "Daily Check-in": "Günlük Kontrol",
    "Dream Reflection": "Rüya Yansıması",
    "Nightmare Follow-up": "Kabus Takibi",
    "Weekly Digest": "Haftalık Özet",
    "Gentle reminder to log your dreams": "Rüyalarınızı kaydetmeniz için nazik bir hatırlatma",
    "Reflect on dreams you've recorded": "Kaydettiğiniz rüyalar üzerinde düşünün",
    "Check in after rewriting a nightmare": "Bir kabusu yeniden yazdıktan sonra kontrol edin",
    "Weekly summary of your dream journey": "Rüya yolculuğunuzun haftalık özeti",

    // MARK: - Notification Frequencies
    "Every Day": "Her Gün",
    "Weekdays Only": "Sadece Hafta İçi",
    "Weekends Only": "Sadece Hafta Sonu",
    "Once a Week": "Haftada Bir",
    "Custom Days": "Özel Günler",

    // MARK: - Day Names
    "Sun": "Paz",
    "Mon": "Pzt",
    "Tue": "Sal",
    "Wed": "Çar",
    "Thu": "Per",
    "Fri": "Cum",
    "Sat": "Cmt",

    // MARK: - Notification Templates
    "Good morning!": "Günaydın!",
    "Dream Journal Time": "Rüya Günlüğü Zamanı",
    "Remember Your Dreams?": "Rüyalarınızı Hatırlıyor musunuz?",
    "Start Your Day Mindfully": "Gününüze Bilinçli Başlayın",
    "Did you dream last night? Take a moment to record it.": "Dün gece rüya gördünüz mü? Bir dakikanızı ayırıp kaydedin.",
    "Your dreams are waiting to be captured.": "Rüyalarınız kaydedilmeyi bekliyor.",
    "A few minutes to log your dreams can make a big difference.": "Rüyalarınızı kaydetmek için birkaç dakika büyük fark yaratabilir.",
    "Dreams fade quickly - save yours now.": "Rüyalar çabuk solar - şimdi kaydedin.",
    "Time to Reflect": "Düşünme Zamanı",
    "Dream Insight": "Rüya İçgörüsü",
    "Look Back": "Geriye Bakın",
    "Your Dream Journey": "Rüya Yolculuğunuz",
    "Revisit a dream you recorded and see how it makes you feel now.": "Kaydettiğiniz bir rüyayı tekrar ziyaret edin ve şimdi size nasıl hissettirdiğini görün.",
    "Your past dreams might hold insights for today.": "Geçmiş rüyalarınız bugün için içgörüler barındırabilir.",
    "Take a moment to reflect on your dream patterns.": "Rüya kalıplarınız üzerinde düşünmek için bir dakikanızı ayırın.",
    "What have your dreams been telling you lately?": "Rüyalarınız son zamanlarda size ne anlatıyor?",
    "How Are You Feeling?": "Nasıl Hissediyorsunuz?",
    "Gentle Check-in": "Nazik Kontrol",
    "You're Doing Great": "Harika Gidiyorsunuz",
    "Healing Journey": "İyileşme Yolculuğu",
    "How did the rewritten dream make you feel? Consider reading it again.": "Yeniden yazılan rüya size nasıl hissettirdi? Tekrar okumayı düşünün.",
    "Remember, you have the power to reshape your dreams.": "Unutmayın, rüyalarınızı yeniden şekillendirme gücüne sahipsiniz.",
    "Take a moment to revisit your peaceful dream version.": "Huzurlu rüya versiyonunuzu tekrar ziyaret etmek için bir dakikanızı ayırın.",
    "Your healing journey continues. We're here for you.": "İyileşme yolculuğunuz devam ediyor. Yanınızdayız.",
    "Your Week in Dreams": "Rüyalarda Haftanız",
    "Weekly Reflection": "Haftalık Yansıma",
    "Dream Summary": "Rüya Özeti",
    "This Week's Journey": "Bu Haftanın Yolculuğu",
    "See how your dream patterns evolved this week.": "Rüya kalıplarınızın bu hafta nasıl geliştiğini görün.",
    "Time for your weekly dream check-in.": "Haftalık rüya kontrolünüzün zamanı geldi.",
    "Reflect on your dream journey this week.": "Bu haftaki rüya yolculuğunuz üzerinde düşünün.",
    "A week of dreams - what stories did they tell?": "Bir haftalık rüyalar - ne hikayeler anlattılar?",
]
