// Polish (pl)

let strings_pl: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "ZALOGUJ SIĘ!",
    "SIGN UP!": "ZAREJESTRUJ SIĘ!",
    "Account": "Konto",
    "Email": "E-mail",
    "Password": "Hasło",
    "Profile": "Profil",
    "Age": "Wiek",
    "Timezone (e.g., %@)": "Strefa czasowa (np. %@)",
    "LOADING!": "ŁADOWANIE!",
    "Log In": "Zaloguj się",
    "Create Account": "Utwórz konto",
    "Need an account?": "Potrzebujesz konta?",
    "Have an account?": "Masz już konto?",
    "Sign Up": "Zarejestruj się",

    // MARK: - Content / Main
    "No dreams match your search": "Żadne sny nie pasują do wyszukiwania",
    "Dreams": "Sny",
    "Search dreams...": "Szukaj snów...",
    "Welcome, Dreamer!": "Witaj, Śniaczu!",
    "DREAM ON!": "ŚNI DALEJ!",
    "Record your first dream to begin your comic journey!": "Zapisz swój pierwszy sen, aby rozpocząć komiksową podróż!",
    "Capture a Dream": "Zapisz sen",
    "DELETE": "USUŃ",

    // MARK: - New Dream
    "What did you dream?": "Co ci się śniło?",
    "Describe your dream or nightmare...": "Opisz swój sen lub koszmar...",
    "Stop Recording": "Zatrzymaj nagrywanie",
    "Record Dream": "Nagraj sen",
    "Tap to stop voice recording": "Stuknij, aby zatrzymać nagrywanie głosu",
    "Tap to start describing your dream with your voice": "Stuknij, aby zacząć opisywać sen głosem",
    "Listening...": "Słucham...",
    "When did you see this dream?": "Kiedy miałeś ten sen?",
    "Save Dream": "Zapisz sen",
    "New Dream": "Nowy sen",

    // MARK: - Common Actions
    "Cancel": "Anuluj",
    "Save": "Zapisz",
    "Edit": "Edytuj",
    "Delete": "Usuń",
    "Done": "Gotowe",
    "Try Again": "Spróbuj ponownie",
    "Retry": "Ponów",
    "Add": "Dodaj",
    "View": "Zobacz",

    // MARK: - Dream Detail
    "Dream date": "Data snu",
    "Original Dream": "Oryginalny sen",
    "Dream Analysis": "Analiza snu",
    "ANALYZING!": "ANALIZUJĘ!",
    "Rewritten Dream (%@)": "Przepisany sen (%@)",
    "Stop": "Zatrzymaj",
    "Play Story": "Odtwórz historię",
    "Tap to stop reading the story": "Stuknij, aby zatrzymać czytanie historii",
    "Tap to hear the story read aloud": "Stuknij, aby usłyszeć historię na głos",
    "Try a Different Tone?": "Spróbować innego tonu?",
    "How Should This Dream Feel?": "Jak powinien brzmieć ten sen?",
    "Narrating!": "Narruję!",
    "Narrate Again": "Narruj ponownie",
    "Narrate": "Narruj",
    "Delete Dream": "Usuń sen",
    "Dream": "Sen",
    "Delete this dream?": "Usunąć ten sen?",
    "This will permanently remove this dream and all its content.": "To trwale usunie ten sen i całą jego zawartość.",

    // MARK: - Tones
    "Happy": "Radosny",
    "Funny": "Zabawny",
    "Hopeful": "Pełen nadziei",
    "Calm": "Spokojny",
    "Positive": "Pozytywny",

    // MARK: - Dream Analysis
    "Time Period": "Okres czasu",
    "Period": "Okres",
    "Emotion Trends": "Trendy emocji",
    "Loading trends...": "Ładowanie trendów...",
    "Loading summary...": "Ładowanie podsumowania...",
    "Summary": "Podsumowanie",
    "Most Common Feeling": "Najczęstsze uczucie",
    "Average intensity: %.0f%%": "Średnia intensywność: %.0f%%",
    "dreams": "sny",
    "Suggested Moods": "Sugerowane nastroje",
    "Activity": "Aktywność",
    "Keep logging dreams to see trends": "Zapisuj sny, aby zobaczyć trendy",
    "Record your first dream to start tracking your emotions": "Zapisz swój pierwszy sen, aby śledzić emocje",
    "ZAP!": "ZAP!",
    "OOPS!": "UPS!",

    // MARK: - Settings
    "Signed in": "Zalogowano",
    "Cloud sync enabled": "Synchronizacja w chmurze włączona",
    "Sign In / Sign Up": "Zaloguj się / Zarejestruj się",
    "Create an account to sync dreams and AI content.": "Utwórz konto, aby synchronizować sny i treści AI.",
    "Notifications": "Powiadomienia",
    "Notification Settings": "Ustawienia powiadomień",
    "Settings": "Ustawienia",
    "Dream Character": "Postać ze snu",
    "These details personalize your dream comics": "Te szczegóły personalizują twoje komiksy ze snów",
    "Sign Out": "Wyloguj się",
    "Gender": "Płeć",
    "Male": "Mężczyzna",
    "Female": "Kobieta",
    "Non-binary": "Niebinarne",
    "Prefer not to say": "Wolę nie mówić",
    "Language": "Język",

    // MARK: - Dream Visualization
    "Dream Visualization": "Wizualizacja snu",
    "AI creates a comic page from your dream": "AI tworzy stronę komiksu z twojego snu",
    "Include my likeness": "Uwzględnij mój wizerunek",
    "OFFLINE!": "OFFLINE!",
    "Image generation requires Apple Silicon or sign-in.": "Generowanie obrazów wymaga Apple Silicon lub zalogowania.",
    "Draw my dream!": "Narysuj mój sen!",
    "Redraw my dream!": "Przerysuj mój sen!",
    "Regenerate as Comic Page": "Wygeneruj ponownie jako stronę komiksu",
    "CREATING!": "TWORZĘ!",
    "Painting your dream...": "Maluję twój sen...",
    "Add your details in Profile to appear in your dreams!": "Dodaj swoje dane w profilu, aby pojawiać się w snach!",
    "Scene %d": "Scena %d",
    "Save your dreams!": "Zapisz swoje sny!",
    "Sign up to sync rewrites and comics across devices.": "Zarejestruj się, aby synchronizować przepisane sny i komiksy na różnych urządzeniach.",
    "Dream Sequence": "Sekwencja snu",
    "Dream Comic Page": "Strona komiksu ze snu",

    // MARK: - Notifications
    "Notifications Enabled": "Powiadomienia włączone",
    "Enable Notifications": "Włącz powiadomienia",
    "Permission": "Uprawnienie",
    "Allow notifications to receive reminders and follow-ups.": "Zezwól na powiadomienia, aby otrzymywać przypomnienia i kontynuacje.",
    "Notification Types": "Typy powiadomień",
    "Configure each notification type independently with its own schedule.": "Skonfiguruj każdy typ powiadomienia niezależnie z własnym harmonogramem.",
    "Permission Required": "Wymagane uprawnienie",
    "Open Settings": "Otwórz ustawienia",
    "Please enable notifications in Settings to receive reminders.": "Włącz powiadomienia w ustawieniach, aby otrzymywać przypomnienia.",
    "When to Notify": "Kiedy powiadamiać",
    "Time of Day": "Pora dnia",
    "Day of Week": "Dzień tygodnia",
    "Select Days": "Wybierz dni",
    "Preview": "Podgląd",
    "Frequency": "Częstotliwość",
    "Time": "Godzina",
    "Day": "Dzień",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Będziesz otrzymywać powiadomienie codziennie o %@.",
    "You'll receive notifications Monday through Friday at %@.": "Będziesz otrzymywać powiadomienia od poniedziałku do piątku o %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Będziesz otrzymywać powiadomienia w sobotę i niedzielę o %@.",
    "You'll receive a notification every %@ at %@.": "Będziesz otrzymywać powiadomienie w każdy %@ o %@.",
    "Select at least one day to receive notifications.": "Wybierz przynajmniej jeden dzień, aby otrzymywać powiadomienia.",
    "You'll receive notifications on %@ at %@.": "Będziesz otrzymywać powiadomienia w %@ o %@.",

    // MARK: - Dream Reminders
    "Reminders": "Przypomnienia",
    "No reminders set": "Brak ustawionych przypomnień",
    "Add a reminder to revisit this dream": "Dodaj przypomnienie, aby wrócić do tego snu",
    "EXPIRED": "WYGASŁO",
    "REMINDER TYPE": "TYP PRZYPOMNIENIA",
    "WHEN": "KIEDY",
    "PREVIEW": "PODGLĄD",
    "Custom": "Własne",
    "Add Reminder": "Dodaj przypomnienie",
    "Date & Time": "Data i godzina",
    "1 hour": "1 godzina",
    "6 hours": "6 godzin",
    "Tomorrow": "Jutro",
    "2 days": "2 dni",
    "1 week": "1 tydzień",
    "You'll receive a \"%@\" reminder on %@": "Otrzymasz przypomnienie \"%@\" dnia %@",

    // MARK: - Avatar
    "Use This Photo": "Użyj tego zdjęcia",
    "Use Memoji": "Użyj Memoji",
    "Choose Photo": "Wybierz zdjęcie",
    "Take Photo": "Zrób zdjęcie",
    "Remove Avatar": "Usuń awatar",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Twoje zdjęcie tworzy tekstowy opis twojego wyglądu. Samo zdjęcie nie jest udostępniane usługom AI.",
    "Profile Picture": "Zdjęcie profilowe",
    "Paste Your Memoji": "Wklej swoje Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Stuknij pole tekstowe poniżej\n2. Przełącz na klawiaturę Memoji\n3. Stuknij ulubioną naklejkę Memoji",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Stuknij tutaj, a potem wklej Memoji...",
    "Uploading...": "Przesyłanie...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Sugerujemy przepisanie tego jako ",
    " dream": " sen",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Strach",
    "Sadness": "Smutek",
    "Anger": "Złość",
    "Anxiety": "Lęk",
    "Stress": "Stres",
    "Loneliness": "Samotność",
    "Helplessness": "Bezradność",
    "Shame": "Wstyd",
    "Grief": "Żałoba",
    "Confusion": "Dezorientacja",
    "Joy": "Radość",
    "Love": "Miłość",
    "Surprise": "Zaskoczenie",
    "Disgust": "Obrzydzenie",
    "Trust": "Zaufanie",
    "Anticipation": "Oczekiwanie",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Spokojny",
    "Serene": "Pogodny",
    "Humorous": "Humorystyczny",
    "Lighthearted": "Beztroski",
    "Empowering": "Wzmacniający",
    "Confident": "Pewny siebie",
    "Optimistic": "Optymistyczny",
    "Inspiring": "Inspirujący",
    "Joyful": "Radosny",
    "Cheerful": "Wesoły",
    "Neutral": "Neutralny",

    // MARK: - Trend Directions
    "Improving": "Poprawa",
    "Worsening": "Pogorszenie",
    "Stable": "Stabilny",

    // MARK: - Analysis Periods
    "7 Days": "7 dni",
    "30 Days": "30 dni",
    "90 Days": "90 dni",
    "All": "Wszystkie",

    // MARK: - Notification Categories
    "Daily Check-in": "Codzienna kontrola",
    "Dream Reflection": "Refleksja nad snem",
    "Nightmare Follow-up": "Kontynuacja po koszmarze",
    "Weekly Digest": "Tygodniowe podsumowanie",
    "Gentle reminder to log your dreams": "Delikatne przypomnienie o zapisaniu snów",
    "Reflect on dreams you've recorded": "Przemyśl sny, które zapisałeś",
    "Check in after rewriting a nightmare": "Sprawdź samopoczucie po przepisaniu koszmaru",
    "Weekly summary of your dream journey": "Tygodniowe podsumowanie twojej podróży ze snami",

    // MARK: - Notification Frequencies
    "Every Day": "Codziennie",
    "Weekdays Only": "Tylko dni robocze",
    "Weekends Only": "Tylko weekendy",
    "Once a Week": "Raz w tygodniu",
    "Custom Days": "Wybrane dni",

    // MARK: - Day Names
    "Sun": "Nd",
    "Mon": "Pn",
    "Tue": "Wt",
    "Wed": "Śr",
    "Thu": "Czw",
    "Fri": "Pt",
    "Sat": "Sob",

    // MARK: - Notification Templates
    "Good morning!": "Dzień dobry!",
    "Dream Journal Time": "Czas na dziennik snów",
    "Remember Your Dreams?": "Pamiętasz swoje sny?",
    "Start Your Day Mindfully": "Rozpocznij dzień uważnie",
    "Did you dream last night? Take a moment to record it.": "Śniło ci się coś w nocy? Poświęć chwilę, aby to zapisać.",
    "Your dreams are waiting to be captured.": "Twoje sny czekają, aby je zapisać.",
    "A few minutes to log your dreams can make a big difference.": "Kilka minut na zapisanie snów może zrobić wielką różnicę.",
    "Dreams fade quickly - save yours now.": "Sny szybko blakną - zapisz je teraz.",
    "Time to Reflect": "Czas na refleksję",
    "Dream Insight": "Wgląd w sny",
    "Look Back": "Spojrzenie wstecz",
    "Your Dream Journey": "Twoja podróż ze snami",
    "Revisit a dream you recorded and see how it makes you feel now.": "Wróć do zapisanego snu i zobacz, jak się teraz z nim czujesz.",
    "Your past dreams might hold insights for today.": "Twoje dawne sny mogą kryć wskazówki na dziś.",
    "Take a moment to reflect on your dream patterns.": "Poświęć chwilę na refleksję nad wzorcami swoich snów.",
    "What have your dreams been telling you lately?": "Co ostatnio mówią ci twoje sny?",
    "How Are You Feeling?": "Jak się czujesz?",
    "Gentle Check-in": "Delikatne sprawdzenie",
    "You're Doing Great": "Świetnie ci idzie",
    "Healing Journey": "Droga do uzdrowienia",
    "How did the rewritten dream make you feel? Consider reading it again.": "Jak się czułeś po przepisanym śnie? Rozważ ponowne przeczytanie.",
    "Remember, you have the power to reshape your dreams.": "Pamiętaj, masz moc, aby przekształcać swoje sny.",
    "Take a moment to revisit your peaceful dream version.": "Poświęć chwilę, aby wrócić do spokojnej wersji snu.",
    "Your healing journey continues. We're here for you.": "Twoja droga do uzdrowienia trwa. Jesteśmy tu dla ciebie.",
    "Your Week in Dreams": "Twój tydzień w snach",
    "Weekly Reflection": "Tygodniowa refleksja",
    "Dream Summary": "Podsumowanie snów",
    "This Week's Journey": "Podróż tego tygodnia",
    "See how your dream patterns evolved this week.": "Zobacz, jak zmieniały się wzorce twoich snów w tym tygodniu.",
    "Time for your weekly dream check-in.": "Czas na cotygodniową kontrolę snów.",
    "Reflect on your dream journey this week.": "Przemyśl swoją podróż ze snami w tym tygodniu.",
    "A week of dreams - what stories did they tell?": "Tydzień snów - jakie historie opowiedziały?",
]
