// Russian (ru)

let strings_ru: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "ВОЙТИ!",
    "SIGN UP!": "РЕГИСТРАЦИЯ!",
    "Account": "Аккаунт",
    "Email": "Электронная почта",
    "Password": "Пароль",
    "Profile": "Профиль",
    "Age": "Возраст",
    "Timezone (e.g., %@)": "Часовой пояс (напр., %@)",
    "LOADING!": "ЗАГРУЗКА!",
    "Log In": "Войти",
    "Create Account": "Создать аккаунт",
    "Need an account?": "Нужен аккаунт?",
    "Have an account?": "Уже есть аккаунт?",
    "Sign Up": "Зарегистрироваться",

    // MARK: - Content / Main
    "No dreams match your search": "Ни один сон не соответствует вашему поиску",
    "Dreams": "Сны",
    "Search dreams...": "Поиск снов...",
    "Welcome, Dreamer!": "Добро пожаловать, Мечтатель!",
    "DREAM ON!": "МЕЧТАЙ ДАЛЬШЕ!",
    "Record your first dream to begin your comic journey!": "Запишите свой первый сон, чтобы начать комиксовое путешествие!",
    "Capture a Dream": "Записать сон",
    "DELETE": "УДАЛИТЬ",

    // MARK: - New Dream
    "What did you dream?": "Что вам снилось?",
    "Describe your dream or nightmare...": "Опишите свой сон или кошмар...",
    "Stop Recording": "Остановить запись",
    "Record Dream": "Записать сон",
    "Tap to stop voice recording": "Нажмите, чтобы остановить голосовую запись",
    "Tap to start describing your dream with your voice": "Нажмите, чтобы описать сон голосом",
    "Listening...": "Слушаю...",
    "When did you see this dream?": "Когда вам приснился этот сон?",
    "Save Dream": "Сохранить сон",
    "New Dream": "Новый сон",

    // MARK: - Common Actions
    "Cancel": "Отмена",
    "Save": "Сохранить",
    "Edit": "Редактировать",
    "Delete": "Удалить",
    "Done": "Готово",
    "Try Again": "Попробовать снова",
    "Retry": "Повторить",
    "Add": "Добавить",
    "View": "Просмотр",

    // MARK: - Dream Detail
    "Dream date": "Дата сна",
    "Original Dream": "Оригинальный сон",
    "Dream Analysis": "Анализ сна",
    "ANALYZING!": "АНАЛИЗИРУЮ!",
    "Rewritten Dream (%@)": "Переписанный сон (%@)",
    "Stop": "Остановить",
    "Play Story": "Воспроизвести историю",
    "Tap to stop reading the story": "Нажмите, чтобы остановить чтение истории",
    "Tap to hear the story read aloud": "Нажмите, чтобы прослушать историю вслух",
    "Try a Different Tone?": "Попробовать другой тон?",
    "How Should This Dream Feel?": "Каким должен быть настрой этого сна?",
    "Narrating!": "Озвучиваю!",
    "Narrate Again": "Озвучить снова",
    "Narrate": "Озвучить",
    "Delete Dream": "Удалить сон",
    "Dream": "Сон",
    "Delete this dream?": "Удалить этот сон?",
    "This will permanently remove this dream and all its content.": "Это навсегда удалит этот сон и всё его содержимое.",

    // MARK: - Tones
    "Happy": "Радостный",
    "Funny": "Смешной",
    "Hopeful": "Обнадёживающий",
    "Calm": "Спокойный",
    "Positive": "Позитивный",

    // MARK: - Dream Analysis
    "Time Period": "Временной период",
    "Period": "Период",
    "Emotion Trends": "Тренды эмоций",
    "Loading trends...": "Загрузка трендов...",
    "Loading summary...": "Загрузка сводки...",
    "Summary": "Сводка",
    "Most Common Feeling": "Самое частое чувство",
    "Average intensity: %.0f%%": "Средняя интенсивность: %.0f%%",
    "dreams": "сны",
    "Suggested Moods": "Предложенные настроения",
    "Activity": "Активность",
    "Keep logging dreams to see trends": "Записывайте сны, чтобы видеть тренды",
    "Record your first dream to start tracking your emotions": "Запишите свой первый сон, чтобы начать отслеживать эмоции",
    "ZAP!": "ЗАП!",
    "OOPS!": "ОЙ!",

    // MARK: - Settings
    "Signed in": "Вы вошли",
    "Cloud sync enabled": "Облачная синхронизация включена",
    "Sign In / Sign Up": "Войти / Зарегистрироваться",
    "Create an account to sync dreams and AI content.": "Создайте аккаунт для синхронизации снов и AI-контента.",
    "Notifications": "Уведомления",
    "Notification Settings": "Настройки уведомлений",
    "Settings": "Настройки",
    "Dream Character": "Персонаж сна",
    "These details personalize your dream comics": "Эти данные персонализируют ваши комиксы из снов",
    "Sign Out": "Выйти",
    "Gender": "Пол",
    "Male": "Мужской",
    "Female": "Женский",
    "Non-binary": "Небинарный",
    "Prefer not to say": "Предпочитаю не указывать",
    "Language": "Язык",

    // MARK: - Dream Visualization
    "Dream Visualization": "Визуализация сна",
    "AI creates a comic page from your dream": "AI создаёт страницу комикса из вашего сна",
    "Include my likeness": "Включить моё изображение",
    "OFFLINE!": "ОФЛАЙН!",
    "Image generation requires Apple Silicon or sign-in.": "Генерация изображений требует Apple Silicon или входа в аккаунт.",
    "Draw my dream!": "Нарисуй мой сон!",
    "Redraw my dream!": "Перерисуй мой сон!",
    "Regenerate as Comic Page": "Перегенерировать как страницу комикса",
    "CREATING!": "СОЗДАЮ!",
    "Painting your dream...": "Рисую ваш сон...",
    "Add your details in Profile to appear in your dreams!": "Добавьте свои данные в профиле, чтобы появляться в своих снах!",
    "Scene %d": "Сцена %d",
    "Save your dreams!": "Сохраните свои сны!",
    "Sign up to sync rewrites and comics across devices.": "Зарегистрируйтесь для синхронизации переписанных снов и комиксов на разных устройствах.",
    "Dream Sequence": "Последовательность сна",
    "Dream Comic Page": "Страница комикса сна",

    // MARK: - Notifications
    "Notifications Enabled": "Уведомления включены",
    "Enable Notifications": "Включить уведомления",
    "Permission": "Разрешение",
    "Allow notifications to receive reminders and follow-ups.": "Разрешите уведомления для получения напоминаний и последующих сообщений.",
    "Notification Types": "Типы уведомлений",
    "Configure each notification type independently with its own schedule.": "Настройте каждый тип уведомления отдельно со своим расписанием.",
    "Permission Required": "Требуется разрешение",
    "Open Settings": "Открыть настройки",
    "Please enable notifications in Settings to receive reminders.": "Включите уведомления в настройках для получения напоминаний.",
    "When to Notify": "Когда уведомлять",
    "Time of Day": "Время суток",
    "Day of Week": "День недели",
    "Select Days": "Выбрать дни",
    "Preview": "Предпросмотр",
    "Frequency": "Частота",
    "Time": "Время",
    "Day": "День",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Вы будете получать уведомление каждый день в %@.",
    "You'll receive notifications Monday through Friday at %@.": "Вы будете получать уведомления с понедельника по пятницу в %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Вы будете получать уведомления в субботу и воскресенье в %@.",
    "You'll receive a notification every %@ at %@.": "Вы будете получать уведомление каждый %@ в %@.",
    "Select at least one day to receive notifications.": "Выберите хотя бы один день для получения уведомлений.",
    "You'll receive notifications on %@ at %@.": "Вы будете получать уведомления в %@ в %@.",

    // MARK: - Dream Reminders
    "Reminders": "Напоминания",
    "No reminders set": "Напоминания не установлены",
    "Add a reminder to revisit this dream": "Добавьте напоминание, чтобы вернуться к этому сну",
    "EXPIRED": "ИСТЕКЛО",
    "REMINDER TYPE": "ТИП НАПОМИНАНИЯ",
    "WHEN": "КОГДА",
    "PREVIEW": "ПРЕДПРОСМОТР",
    "Custom": "Пользовательский",
    "Add Reminder": "Добавить напоминание",
    "Date & Time": "Дата и время",
    "1 hour": "1 час",
    "6 hours": "6 часов",
    "Tomorrow": "Завтра",
    "2 days": "2 дня",
    "1 week": "1 неделя",
    "You'll receive a \"%@\" reminder on %@": "Вы получите напоминание \"%@\" %@",

    // MARK: - Avatar
    "Use This Photo": "Использовать это фото",
    "Use Memoji": "Использовать Memoji",
    "Choose Photo": "Выбрать фото",
    "Take Photo": "Сделать фото",
    "Remove Avatar": "Удалить аватар",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Ваше фото создаёт текстовое описание вашей внешности. Само фото не передаётся AI-сервисам.",
    "Profile Picture": "Фото профиля",
    "Paste Your Memoji": "Вставьте своё Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Нажмите на текстовое поле ниже\n2. Переключитесь на клавиатуру Memoji\n3. Нажмите на любимый стикер Memoji",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Нажмите здесь, затем вставьте Memoji...",
    "Uploading...": "Загрузка...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Мы предлагаем переписать это как ",
    " dream": " сон",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Страх",
    "Sadness": "Печаль",
    "Anger": "Гнев",
    "Anxiety": "Тревога",
    "Stress": "Стресс",
    "Loneliness": "Одиночество",
    "Helplessness": "Беспомощность",
    "Shame": "Стыд",
    "Grief": "Горе",
    "Confusion": "Замешательство",
    "Joy": "Радость",
    "Love": "Любовь",
    "Surprise": "Удивление",
    "Disgust": "Отвращение",
    "Trust": "Доверие",
    "Anticipation": "Предвкушение",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Умиротворённый",
    "Serene": "Безмятежный",
    "Humorous": "Юмористический",
    "Lighthearted": "Беззаботный",
    "Empowering": "Вдохновляющий",
    "Confident": "Уверенный",
    "Optimistic": "Оптимистичный",
    "Inspiring": "Воодушевляющий",
    "Joyful": "Радостный",
    "Cheerful": "Весёлый",
    "Neutral": "Нейтральный",

    // MARK: - Trend Directions
    "Improving": "Улучшается",
    "Worsening": "Ухудшается",
    "Stable": "Стабильный",

    // MARK: - Analysis Periods
    "7 Days": "7 дней",
    "30 Days": "30 дней",
    "90 Days": "90 дней",
    "All": "Все",

    // MARK: - Notification Categories
    "Daily Check-in": "Ежедневная проверка",
    "Dream Reflection": "Размышление о сне",
    "Nightmare Follow-up": "Продолжение после кошмара",
    "Weekly Digest": "Еженедельная сводка",
    "Gentle reminder to log your dreams": "Мягкое напоминание записать сны",
    "Reflect on dreams you've recorded": "Поразмышляйте над записанными снами",
    "Check in after rewriting a nightmare": "Проверьте самочувствие после переписывания кошмара",
    "Weekly summary of your dream journey": "Еженедельная сводка вашего путешествия со снами",

    // MARK: - Notification Frequencies
    "Every Day": "Каждый день",
    "Weekdays Only": "Только будни",
    "Weekends Only": "Только выходные",
    "Once a Week": "Раз в неделю",
    "Custom Days": "Выбранные дни",

    // MARK: - Day Names
    "Sun": "Вс",
    "Mon": "Пн",
    "Tue": "Вт",
    "Wed": "Ср",
    "Thu": "Чт",
    "Fri": "Пт",
    "Sat": "Сб",

    // MARK: - Notification Templates
    "Good morning!": "Доброе утро!",
    "Dream Journal Time": "Время для дневника снов",
    "Remember Your Dreams?": "Помните свои сны?",
    "Start Your Day Mindfully": "Начните день осознанно",
    "Did you dream last night? Take a moment to record it.": "Вам снилось что-нибудь ночью? Уделите минутку, чтобы это записать.",
    "Your dreams are waiting to be captured.": "Ваши сны ждут, чтобы их записали.",
    "A few minutes to log your dreams can make a big difference.": "Несколько минут на запись снов могут многое изменить.",
    "Dreams fade quickly - save yours now.": "Сны быстро забываются - сохраните свои сейчас.",
    "Time to Reflect": "Время для размышлений",
    "Dream Insight": "Прозрение из сна",
    "Look Back": "Взгляд назад",
    "Your Dream Journey": "Ваше путешествие со снами",
    "Revisit a dream you recorded and see how it makes you feel now.": "Вернитесь к записанному сну и посмотрите, как вы себя чувствуете сейчас.",
    "Your past dreams might hold insights for today.": "Ваши прошлые сны могут содержать подсказки на сегодня.",
    "Take a moment to reflect on your dream patterns.": "Уделите минутку размышлению о закономерностях ваших снов.",
    "What have your dreams been telling you lately?": "Что вам в последнее время говорят ваши сны?",
    "How Are You Feeling?": "Как вы себя чувствуете?",
    "Gentle Check-in": "Мягкая проверка",
    "You're Doing Great": "У вас отлично получается",
    "Healing Journey": "Путь к исцелению",
    "How did the rewritten dream make you feel? Consider reading it again.": "Как вы себя почувствовали после переписанного сна? Попробуйте перечитать его.",
    "Remember, you have the power to reshape your dreams.": "Помните, у вас есть сила изменять свои сны.",
    "Take a moment to revisit your peaceful dream version.": "Уделите минутку, чтобы вернуться к мирной версии сна.",
    "Your healing journey continues. We're here for you.": "Ваш путь к исцелению продолжается. Мы рядом с вами.",
    "Your Week in Dreams": "Ваша неделя в снах",
    "Weekly Reflection": "Еженедельное размышление",
    "Dream Summary": "Сводка снов",
    "This Week's Journey": "Путешествие этой недели",
    "See how your dream patterns evolved this week.": "Посмотрите, как менялись закономерности ваших снов на этой неделе.",
    "Time for your weekly dream check-in.": "Время для еженедельной проверки снов.",
    "Reflect on your dream journey this week.": "Поразмышляйте о вашем путешествии со снами на этой неделе.",
    "A week of dreams - what stories did they tell?": "Неделя снов - какие истории они рассказали?",
]
