// Greek (el)

let strings_el: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "ΣΥΝΔΕΣΗ!",
    "SIGN UP!": "ΕΓΓΡΑΦΗ!",
    "Account": "Λογαριασμός",
    "Email": "Email",
    "Password": "Κωδικός",
    "Profile": "Προφίλ",
    "Age": "Ηλικία",
    "Timezone (e.g., %@)": "Ζώνη ώρας (π.χ., %@)",
    "LOADING!": "ΦΟΡΤΩΣΗ!",
    "Log In": "Σύνδεση",
    "Create Account": "Δημιουργία Λογαριασμού",
    "Need an account?": "Χρειάζεστε λογαριασμό;",
    "Have an account?": "Έχετε λογαριασμό;",
    "Sign Up": "Εγγραφή",

    // MARK: - Content / Main
    "No dreams match your search": "Κανένα όνειρο δεν ταιριάζει με την αναζήτησή σας",
    "Dreams": "Όνειρα",
    "Search dreams...": "Αναζήτηση ονείρων...",
    "Welcome, Dreamer!": "Καλώς ήρθες, Ονειροπόλε!",
    "DREAM ON!": "ΟΝΕΙΡΕΨΟΥ!",
    "Record your first dream to begin your comic journey!": "Καταγράψτε το πρώτο σας όνειρο για να ξεκινήσετε το κόμικ ταξίδι σας!",
    "Capture a Dream": "Καταγράψτε ένα Όνειρο",
    "DELETE": "ΔΙΑΓΡΑΦΗ",

    // MARK: - New Dream
    "What did you dream?": "Τι ονειρεύτηκες;",
    "Describe your dream or nightmare...": "Περιγράψτε το όνειρο ή τον εφιάλτη σας...",
    "Stop Recording": "Διακοπή Εγγραφής",
    "Record Dream": "Εγγραφή Ονείρου",
    "Tap to stop voice recording": "Πατήστε για διακοπή ηχογράφησης",
    "Tap to start describing your dream with your voice": "Πατήστε για να περιγράψετε το όνειρό σας με τη φωνή σας",
    "Listening...": "Ακούω...",
    "When did you see this dream?": "Πότε είδατε αυτό το όνειρο;",
    "Save Dream": "Αποθήκευση Ονείρου",
    "New Dream": "Νέο Όνειρο",

    // MARK: - Common Actions
    "Cancel": "Ακύρωση",
    "Save": "Αποθήκευση",
    "Edit": "Επεξεργασία",
    "Delete": "Διαγραφή",
    "Done": "Τέλος",
    "Try Again": "Δοκιμάστε Ξανά",
    "Retry": "Επανάληψη",
    "Add": "Προσθήκη",
    "View": "Προβολή",

    // MARK: - Dream Detail
    "Dream date": "Ημερομηνία ονείρου",
    "Original Dream": "Αρχικό Όνειρο",
    "Dream Analysis": "Ανάλυση Ονείρου",
    "ANALYZING!": "ΑΝΑΛΥΣΗ!",
    "Rewritten Dream (%@)": "Ξαναγραμμένο Όνειρο (%@)",
    "Stop": "Διακοπή",
    "Play Story": "Αναπαραγωγή Ιστορίας",
    "Tap to stop reading the story": "Πατήστε για να σταματήσει η ανάγνωση",
    "Tap to hear the story read aloud": "Πατήστε για να ακούσετε την ιστορία δυνατά",
    "Try a Different Tone?": "Δοκιμάστε Διαφορετικό Τόνο;",
    "How Should This Dream Feel?": "Πώς Πρέπει να Αισθάνεται Αυτό το Όνειρο;",
    "Narrating!": "Αφήγηση!",
    "Narrate Again": "Αφήγηση Ξανά",
    "Narrate": "Αφήγηση",
    "Delete Dream": "Διαγραφή Ονείρου",
    "Dream": "Όνειρο",
    "Delete this dream?": "Διαγραφή αυτού του ονείρου;",
    "This will permanently remove this dream and all its content.": "Αυτό θα αφαιρέσει μόνιμα αυτό το όνειρο και όλο το περιεχόμενό του.",

    // MARK: - Tones
    "Happy": "Χαρούμενο",
    "Funny": "Αστείο",
    "Hopeful": "Αισιόδοξο",
    "Calm": "Ήρεμο",
    "Positive": "Θετικό",

    // MARK: - Dream Analysis
    "Time Period": "Χρονική Περίοδος",
    "Period": "Περίοδος",
    "Emotion Trends": "Τάσεις Συναισθημάτων",
    "Loading trends...": "Φόρτωση τάσεων...",
    "Loading summary...": "Φόρτωση σύνοψης...",
    "Summary": "Σύνοψη",
    "Most Common Feeling": "Πιο Συχνό Συναίσθημα",
    "Average intensity: %.0f%%": "Μέση ένταση: %.0f%%",
    "dreams": "όνειρα",
    "Suggested Moods": "Προτεινόμενες Διαθέσεις",
    "Activity": "Δραστηριότητα",
    "Keep logging dreams to see trends": "Συνεχίστε να καταγράφετε όνειρα για να δείτε τάσεις",
    "Record your first dream to start tracking your emotions": "Καταγράψτε το πρώτο σας όνειρο για να ξεκινήσετε την παρακολούθηση συναισθημάτων",
    "ZAP!": "ΖΑΠ!",
    "OOPS!": "ΩΧΟΥ!",

    // MARK: - Settings
    "Signed in": "Συνδεδεμένος",
    "Cloud sync enabled": "Συγχρονισμός cloud ενεργοποιημένος",
    "Sign In / Sign Up": "Σύνδεση / Εγγραφή",
    "Create an account to sync dreams and AI content.": "Δημιουργήστε λογαριασμό για συγχρονισμό ονείρων και περιεχομένου AI.",
    "Notifications": "Ειδοποιήσεις",
    "Notification Settings": "Ρυθμίσεις Ειδοποιήσεων",
    "Settings": "Ρυθμίσεις",
    "Dream Character": "Χαρακτήρας Ονείρου",
    "These details personalize your dream comics": "Αυτές οι λεπτομέρειες εξατομικεύουν τα κόμικ ονείρων σας",
    "Sign Out": "Αποσύνδεση",
    "Gender": "Φύλο",
    "Male": "Άνδρας",
    "Female": "Γυναίκα",
    "Non-binary": "Μη δυαδικό",
    "Prefer not to say": "Προτιμώ να μην απαντήσω",
    "Language": "Γλώσσα",

    // MARK: - Dream Visualization
    "Dream Visualization": "Οπτικοποίηση Ονείρου",
    "AI creates a comic page from your dream": "Η AI δημιουργεί μια σελίδα κόμικ από το όνειρό σας",
    "Include my likeness": "Να συμπεριληφθεί η ομοιότητά μου",
    "OFFLINE!": "ΕΚΤΟΣ ΣΥΝΔΕΣΗΣ!",
    "Image generation requires Apple Silicon or sign-in.": "Η δημιουργία εικόνων απαιτεί Apple Silicon ή σύνδεση.",
    "Draw my dream!": "Ζωγράφισε το όνειρό μου!",
    "Redraw my dream!": "Ξαναζωγράφισε το όνειρό μου!",
    "Regenerate as Comic Page": "Αναδημιουργία ως Σελίδα Κόμικ",
    "CREATING!": "ΔΗΜΙΟΥΡΓΙΑ!",
    "Painting your dream...": "Ζωγραφίζουμε το όνειρό σας...",
    "Add your details in Profile to appear in your dreams!": "Προσθέστε τα στοιχεία σας στο Προφίλ για να εμφανίζεστε στα όνειρά σας!",
    "Scene %d": "Σκηνή %d",
    "Save your dreams!": "Αποθηκεύστε τα όνειρά σας!",
    "Sign up to sync rewrites and comics across devices.": "Εγγραφείτε για συγχρονισμό αναδημιουργιών και κόμικ σε όλες τις συσκευές.",
    "Dream Sequence": "Ακολουθία Ονείρου",
    "Dream Comic Page": "Σελίδα Κόμικ Ονείρου",

    // MARK: - Notifications
    "Notifications Enabled": "Ειδοποιήσεις Ενεργοποιημένες",
    "Enable Notifications": "Ενεργοποίηση Ειδοποιήσεων",
    "Permission": "Άδεια",
    "Allow notifications to receive reminders and follow-ups.": "Επιτρέψτε ειδοποιήσεις για να λαμβάνετε υπενθυμίσεις και παρακολουθήσεις.",
    "Notification Types": "Τύποι Ειδοποιήσεων",
    "Configure each notification type independently with its own schedule.": "Ρυθμίστε κάθε τύπο ειδοποίησης ανεξάρτητα με το δικό του πρόγραμμα.",
    "Permission Required": "Απαιτείται Άδεια",
    "Open Settings": "Άνοιγμα Ρυθμίσεων",
    "Please enable notifications in Settings to receive reminders.": "Ενεργοποιήστε τις ειδοποιήσεις στις Ρυθμίσεις για να λαμβάνετε υπενθυμίσεις.",
    "When to Notify": "Πότε να Ειδοποιεί",
    "Time of Day": "Ώρα Ημέρας",
    "Day of Week": "Ημέρα Εβδομάδας",
    "Select Days": "Επιλογή Ημερών",
    "Preview": "Προεπισκόπηση",
    "Frequency": "Συχνότητα",
    "Time": "Ώρα",
    "Day": "Ημέρα",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Θα λαμβάνετε ειδοποίηση κάθε μέρα στις %@.",
    "You'll receive notifications Monday through Friday at %@.": "Θα λαμβάνετε ειδοποιήσεις Δευτέρα ως Παρασκευή στις %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Θα λαμβάνετε ειδοποιήσεις Σάββατο και Κυριακή στις %@.",
    "You'll receive a notification every %@ at %@.": "Θα λαμβάνετε ειδοποίηση κάθε %@ στις %@.",
    "Select at least one day to receive notifications.": "Επιλέξτε τουλάχιστον μία ημέρα για να λαμβάνετε ειδοποιήσεις.",
    "You'll receive notifications on %@ at %@.": "Θα λαμβάνετε ειδοποιήσεις %@ στις %@.",

    // MARK: - Dream Reminders
    "Reminders": "Υπενθυμίσεις",
    "No reminders set": "Δεν έχουν οριστεί υπενθυμίσεις",
    "Add a reminder to revisit this dream": "Προσθέστε υπενθύμιση για να ξαναδείτε αυτό το όνειρο",
    "EXPIRED": "ΕΛΗΞΕ",
    "REMINDER TYPE": "ΤΥΠΟΣ ΥΠΕΝΘΥΜΙΣΗΣ",
    "WHEN": "ΠΟΤΕ",
    "PREVIEW": "ΠΡΟΕΠΙΣΚΟΠΗΣΗ",
    "Custom": "Προσαρμοσμένο",
    "Add Reminder": "Προσθήκη Υπενθύμισης",
    "Date & Time": "Ημερομηνία & Ώρα",
    "1 hour": "1 ώρα",
    "6 hours": "6 ώρες",
    "Tomorrow": "Αύριο",
    "2 days": "2 ημέρες",
    "1 week": "1 εβδομάδα",
    "You'll receive a \"%@\" reminder on %@": "Θα λάβετε υπενθύμιση \"%@\" στις %@",

    // MARK: - Avatar
    "Use This Photo": "Χρήση Αυτής της Φωτογραφίας",
    "Use Memoji": "Χρήση Memoji",
    "Choose Photo": "Επιλογή Φωτογραφίας",
    "Take Photo": "Λήψη Φωτογραφίας",
    "Remove Avatar": "Αφαίρεση Άβαταρ",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Η φωτογραφία σας δημιουργεί μια περιγραφή κειμένου της εμφάνισής σας. Η ίδια η φωτογραφία δεν κοινοποιείται σε υπηρεσίες AI.",
    "Profile Picture": "Εικόνα Προφίλ",
    "Paste Your Memoji": "Επικολλήστε το Memoji σας",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Πατήστε το πεδίο κειμένου παρακάτω\n2. Μεταβείτε στο πληκτρολόγιο Memoji\n3. Πατήστε το αγαπημένο σας αυτοκόλλητο Memoji",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Πατήστε εδώ και επικολλήστε Memoji...",
    "Uploading...": "Μεταφόρτωση...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Προτείνουμε να ξαναγράψετε αυτό ως ",
    " dream": " όνειρο",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Φόβος",
    "Sadness": "Θλίψη",
    "Anger": "Θυμός",
    "Anxiety": "Άγχος",
    "Stress": "Στρες",
    "Loneliness": "Μοναξιά",
    "Helplessness": "Αδυναμία",
    "Shame": "Ντροπή",
    "Grief": "Πένθος",
    "Confusion": "Σύγχυση",
    "Joy": "Χαρά",
    "Love": "Αγάπη",
    "Surprise": "Έκπληξη",
    "Disgust": "Αηδία",
    "Trust": "Εμπιστοσύνη",
    "Anticipation": "Προσμονή",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Ειρηνικός",
    "Serene": "Γαλήνιος",
    "Humorous": "Χιουμοριστικός",
    "Lighthearted": "Ξέγνοιαστος",
    "Empowering": "Ενδυναμωτικός",
    "Confident": "Σίγουρος",
    "Optimistic": "Αισιόδοξος",
    "Inspiring": "Εμπνευστικός",
    "Joyful": "Χαρούμενος",
    "Cheerful": "Κεφάτος",
    "Neutral": "Ουδέτερος",

    // MARK: - Trend Directions
    "Improving": "Βελτιώνεται",
    "Worsening": "Επιδεινώνεται",
    "Stable": "Σταθερός",

    // MARK: - Analysis Periods
    "7 Days": "7 Ημέρες",
    "30 Days": "30 Ημέρες",
    "90 Days": "90 Ημέρες",
    "All": "Όλα",

    // MARK: - Notification Categories
    "Daily Check-in": "Καθημερινό Check-in",
    "Dream Reflection": "Αναστοχασμός Ονείρων",
    "Nightmare Follow-up": "Παρακολούθηση Εφιάλτη",
    "Weekly Digest": "Εβδομαδιαία Σύνοψη",
    "Gentle reminder to log your dreams": "Ευγενική υπενθύμιση να καταγράψετε τα όνειρά σας",
    "Reflect on dreams you've recorded": "Αναστοχαστείτε τα όνειρα που έχετε καταγράψει",
    "Check in after rewriting a nightmare": "Ελέγξτε μετά την αναδημιουργία ενός εφιάλτη",
    "Weekly summary of your dream journey": "Εβδομαδιαία σύνοψη του ταξιδιού ονείρων σας",

    // MARK: - Notification Frequencies
    "Every Day": "Κάθε Μέρα",
    "Weekdays Only": "Μόνο Καθημερινές",
    "Weekends Only": "Μόνο Σαββατοκύριακα",
    "Once a Week": "Μία Φορά την Εβδομάδα",
    "Custom Days": "Προσαρμοσμένες Ημέρες",

    // MARK: - Day Names
    "Sun": "Κυρ",
    "Mon": "Δευ",
    "Tue": "Τρί",
    "Wed": "Τετ",
    "Thu": "Πέμ",
    "Fri": "Παρ",
    "Sat": "Σάβ",

    // MARK: - Notification Templates
    "Good morning!": "Καλημέρα!",
    "Dream Journal Time": "Ώρα Ημερολογίου Ονείρων",
    "Remember Your Dreams?": "Θυμάστε τα Όνειρά σας;",
    "Start Your Day Mindfully": "Ξεκινήστε τη Μέρα σας με Επίγνωση",
    "Did you dream last night? Take a moment to record it.": "Ονειρευτήκατε χθες βράδυ; Αφιερώστε μια στιγμή για να το καταγράψετε.",
    "Your dreams are waiting to be captured.": "Τα όνειρά σας περιμένουν να καταγραφούν.",
    "A few minutes to log your dreams can make a big difference.": "Λίγα λεπτά για να καταγράψετε τα όνειρά σας μπορούν να κάνουν μεγάλη διαφορά.",
    "Dreams fade quickly - save yours now.": "Τα όνειρα ξεθωριάζουν γρήγορα - αποθηκεύστε τα τώρα.",
    "Time to Reflect": "Ώρα για Αναστοχασμό",
    "Dream Insight": "Ενόραση Ονείρου",
    "Look Back": "Κοιτάξτε Πίσω",
    "Your Dream Journey": "Το Ταξίδι Ονείρων σας",
    "Revisit a dream you recorded and see how it makes you feel now.": "Ξαναδείτε ένα όνειρο που καταγράψατε και δείτε πώς σας κάνει να αισθάνεστε τώρα.",
    "Your past dreams might hold insights for today.": "Τα παλιά σας όνειρα μπορεί να κρύβουν γνώσεις για σήμερα.",
    "Take a moment to reflect on your dream patterns.": "Αφιερώστε μια στιγμή για να σκεφτείτε τα μοτίβα ονείρων σας.",
    "What have your dreams been telling you lately?": "Τι σας λένε τα όνειρά σας τελευταία;",
    "How Are You Feeling?": "Πώς Αισθάνεστε;",
    "Gentle Check-in": "Ευγενικός Έλεγχος",
    "You're Doing Great": "Τα Πάτε Υπέροχα",
    "Healing Journey": "Ταξίδι Θεραπείας",
    "How did the rewritten dream make you feel? Consider reading it again.": "Πώς σας έκανε να αισθανθείτε το ξαναγραμμένο όνειρο; Σκεφτείτε να το ξαναδιαβάσετε.",
    "Remember, you have the power to reshape your dreams.": "Θυμηθείτε, έχετε τη δύναμη να αναδιαμορφώσετε τα όνειρά σας.",
    "Take a moment to revisit your peaceful dream version.": "Αφιερώστε μια στιγμή για να ξαναδείτε τη γαλήνια εκδοχή του ονείρου σας.",
    "Your healing journey continues. We're here for you.": "Το ταξίδι θεραπείας σας συνεχίζεται. Είμαστε εδώ για εσάς.",
    "Your Week in Dreams": "Η Εβδομάδα σας σε Όνειρα",
    "Weekly Reflection": "Εβδομαδιαίος Αναστοχασμός",
    "Dream Summary": "Σύνοψη Ονείρων",
    "This Week's Journey": "Το Ταξίδι αυτής της Εβδομάδας",
    "See how your dream patterns evolved this week.": "Δείτε πώς εξελίχθηκαν τα μοτίβα ονείρων σας αυτή την εβδομάδα.",
    "Time for your weekly dream check-in.": "Ώρα για τον εβδομαδιαίο έλεγχο ονείρων σας.",
    "Reflect on your dream journey this week.": "Αναστοχαστείτε το ταξίδι ονείρων σας αυτή την εβδομάδα.",
    "A week of dreams - what stories did they tell?": "Μια εβδομάδα ονείρων - τι ιστορίες είπαν;",
]
