// Italian (it)

let strings_it: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "ACCEDI!",
    "SIGN UP!": "REGISTRATI!",
    "Account": "Account",
    "Email": "Email",
    "Password": "Password",
    "Profile": "Profilo",
    "Age": "Età",
    "Timezone (e.g., %@)": "Fuso orario (es., %@)",
    "LOADING!": "CARICAMENTO!",
    "Log In": "Accedi",
    "Create Account": "Crea Account",
    "Need an account?": "Hai bisogno di un account?",
    "Have an account?": "Hai già un account?",
    "Sign Up": "Registrati",

    // MARK: - Content / Main
    "No dreams match your search": "Nessun sogno corrisponde alla tua ricerca",
    "Dreams": "Sogni",
    "Search dreams...": "Cerca sogni...",
    "Welcome, Dreamer!": "Benvenuto, Sognatore!",
    "DREAM ON!": "SOGNA!",
    "Record your first dream to begin your comic journey!": "Registra il tuo primo sogno per iniziare il tuo viaggio a fumetti!",
    "Capture a Dream": "Cattura un Sogno",
    "DELETE": "ELIMINA",

    // MARK: - New Dream
    "What did you dream?": "Cosa hai sognato?",
    "Describe your dream or nightmare...": "Descrivi il tuo sogno o incubo...",
    "Stop Recording": "Ferma Registrazione",
    "Record Dream": "Registra Sogno",
    "Tap to stop voice recording": "Tocca per fermare la registrazione vocale",
    "Tap to start describing your dream with your voice": "Tocca per iniziare a descrivere il tuo sogno con la voce",
    "Listening...": "In ascolto...",
    "When did you see this dream?": "Quando hai fatto questo sogno?",
    "Save Dream": "Salva Sogno",
    "New Dream": "Nuovo Sogno",

    // MARK: - Common Actions
    "Cancel": "Annulla",
    "Save": "Salva",
    "Edit": "Modifica",
    "Delete": "Elimina",
    "Done": "Fatto",
    "Try Again": "Riprova",
    "Retry": "Riprova",
    "Add": "Aggiungi",
    "View": "Visualizza",

    // MARK: - Dream Detail
    "Dream date": "Data del sogno",
    "Original Dream": "Sogno Originale",
    "Dream Analysis": "Analisi del Sogno",
    "ANALYZING!": "ANALISI!",
    "Rewritten Dream (%@)": "Sogno Riscritto (%@)",
    "Stop": "Ferma",
    "Play Story": "Ascolta Storia",
    "Tap to stop reading the story": "Tocca per fermare la lettura della storia",
    "Tap to hear the story read aloud": "Tocca per ascoltare la storia ad alta voce",
    "Try a Different Tone?": "Provare un Tono Diverso?",
    "How Should This Dream Feel?": "Come Dovrebbe Sembrare Questo Sogno?",
    "Narrating!": "Narrazione!",
    "Narrate Again": "Narra di Nuovo",
    "Narrate": "Narra",
    "Delete Dream": "Elimina Sogno",
    "Dream": "Sogno",
    "Delete this dream?": "Eliminare questo sogno?",
    "This will permanently remove this dream and all its content.": "Questo eliminerà permanentemente questo sogno e tutto il suo contenuto.",

    // MARK: - Tones
    "Happy": "Felice",
    "Funny": "Divertente",
    "Hopeful": "Speranzoso",
    "Calm": "Calmo",
    "Positive": "Positivo",

    // MARK: - Dream Analysis
    "Time Period": "Periodo di Tempo",
    "Period": "Periodo",
    "Emotion Trends": "Tendenze Emotive",
    "Loading trends...": "Caricamento tendenze...",
    "Loading summary...": "Caricamento riepilogo...",
    "Summary": "Riepilogo",
    "Most Common Feeling": "Emozione Più Comune",
    "Average intensity: %.0f%%": "Intensità media: %.0f%%",
    "dreams": "sogni",
    "Suggested Moods": "Umori Suggeriti",
    "Activity": "Attività",
    "Keep logging dreams to see trends": "Continua a registrare sogni per vedere le tendenze",
    "Record your first dream to start tracking your emotions": "Registra il tuo primo sogno per iniziare a monitorare le tue emozioni",
    "ZAP!": "ZAP!",
    "OOPS!": "OPS!",

    // MARK: - Settings
    "Signed in": "Connesso",
    "Cloud sync enabled": "Sincronizzazione cloud attivata",
    "Sign In / Sign Up": "Accedi / Registrati",
    "Create an account to sync dreams and AI content.": "Crea un account per sincronizzare sogni e contenuti AI.",
    "Notifications": "Notifiche",
    "Notification Settings": "Impostazioni Notifiche",
    "Settings": "Impostazioni",
    "Dream Character": "Personaggio del Sogno",
    "These details personalize your dream comics": "Questi dettagli personalizzano i tuoi fumetti dei sogni",
    "Sign Out": "Esci",
    "Gender": "Genere",
    "Male": "Maschio",
    "Female": "Femmina",
    "Non-binary": "Non binario",
    "Prefer not to say": "Preferisco non dire",
    "Language": "Lingua",

    // MARK: - Dream Visualization
    "Dream Visualization": "Visualizzazione del Sogno",
    "AI creates a comic page from your dream": "L'AI crea una pagina a fumetti dal tuo sogno",
    "Include my likeness": "Includi le mie sembianze",
    "OFFLINE!": "OFFLINE!",
    "Image generation requires Apple Silicon or sign-in.": "La generazione di immagini richiede Apple Silicon o l'accesso.",
    "Draw my dream!": "Disegna il mio sogno!",
    "Redraw my dream!": "Ridisegna il mio sogno!",
    "Regenerate as Comic Page": "Rigenera come Pagina a Fumetti",
    "CREATING!": "CREAZIONE!",
    "Painting your dream...": "Dipingendo il tuo sogno...",
    "Add your details in Profile to appear in your dreams!": "Aggiungi i tuoi dettagli nel Profilo per apparire nei tuoi sogni!",
    "Scene %d": "Scena %d",
    "Save your dreams!": "Salva i tuoi sogni!",
    "Sign up to sync rewrites and comics across devices.": "Registrati per sincronizzare riscritture e fumetti su tutti i dispositivi.",
    "Dream Sequence": "Sequenza del Sogno",
    "Dream Comic Page": "Pagina Fumetto del Sogno",

    // MARK: - Notifications
    "Notifications Enabled": "Notifiche Attivate",
    "Enable Notifications": "Attiva Notifiche",
    "Permission": "Permesso",
    "Allow notifications to receive reminders and follow-ups.": "Consenti le notifiche per ricevere promemoria e follow-up.",
    "Notification Types": "Tipi di Notifica",
    "Configure each notification type independently with its own schedule.": "Configura ogni tipo di notifica in modo indipendente con il proprio programma.",
    "Permission Required": "Permesso Richiesto",
    "Open Settings": "Apri Impostazioni",
    "Please enable notifications in Settings to receive reminders.": "Attiva le notifiche nelle Impostazioni per ricevere i promemoria.",
    "When to Notify": "Quando Notificare",
    "Time of Day": "Ora del Giorno",
    "Day of Week": "Giorno della Settimana",
    "Select Days": "Seleziona Giorni",
    "Preview": "Anteprima",
    "Frequency": "Frequenza",
    "Time": "Ora",
    "Day": "Giorno",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Riceverai una notifica ogni giorno alle %@.",
    "You'll receive notifications Monday through Friday at %@.": "Riceverai notifiche dal lunedì al venerdì alle %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Riceverai notifiche sabato e domenica alle %@.",
    "You'll receive a notification every %@ at %@.": "Riceverai una notifica ogni %@ alle %@.",
    "Select at least one day to receive notifications.": "Seleziona almeno un giorno per ricevere le notifiche.",
    "You'll receive notifications on %@ at %@.": "Riceverai notifiche il %@ alle %@.",

    // MARK: - Dream Reminders
    "Reminders": "Promemoria",
    "No reminders set": "Nessun promemoria impostato",
    "Add a reminder to revisit this dream": "Aggiungi un promemoria per rivisitare questo sogno",
    "EXPIRED": "SCADUTO",
    "REMINDER TYPE": "TIPO DI PROMEMORIA",
    "WHEN": "QUANDO",
    "PREVIEW": "ANTEPRIMA",
    "Custom": "Personalizzato",
    "Add Reminder": "Aggiungi Promemoria",
    "Date & Time": "Data e Ora",
    "1 hour": "1 ora",
    "6 hours": "6 ore",
    "Tomorrow": "Domani",
    "2 days": "2 giorni",
    "1 week": "1 settimana",
    "You'll receive a \"%@\" reminder on %@": "Riceverai un promemoria \"%@\" il %@",

    // MARK: - Avatar
    "Use This Photo": "Usa Questa Foto",
    "Use Memoji": "Usa Memoji",
    "Choose Photo": "Scegli Foto",
    "Take Photo": "Scatta Foto",
    "Remove Avatar": "Rimuovi Avatar",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "La tua foto crea una descrizione testuale del tuo aspetto. La foto stessa non viene condivisa con i servizi AI.",
    "Profile Picture": "Immagine del Profilo",
    "Paste Your Memoji": "Incolla il Tuo Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Tocca il campo di testo qui sotto\n2. Passa alla tastiera Memoji\n3. Tocca il tuo adesivo Memoji preferito",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Tocca qui, poi incolla Memoji...",
    "Uploading...": "Caricamento...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Suggeriamo di riscrivere questo come un sogno ",
    " dream": "",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Paura",
    "Sadness": "Tristezza",
    "Anger": "Rabbia",
    "Anxiety": "Ansia",
    "Stress": "Stress",
    "Loneliness": "Solitudine",
    "Helplessness": "Impotenza",
    "Shame": "Vergogna",
    "Grief": "Lutto",
    "Confusion": "Confusione",
    "Joy": "Gioia",
    "Love": "Amore",
    "Surprise": "Sorpresa",
    "Disgust": "Disgusto",
    "Trust": "Fiducia",
    "Anticipation": "Aspettativa",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Pacifico",
    "Serene": "Sereno",
    "Humorous": "Umoristico",
    "Lighthearted": "Spensierato",
    "Empowering": "Potenziante",
    "Confident": "Sicuro",
    "Optimistic": "Ottimista",
    "Inspiring": "Ispirante",
    "Joyful": "Gioioso",
    "Cheerful": "Allegro",
    "Neutral": "Neutro",

    // MARK: - Trend Directions
    "Improving": "In miglioramento",
    "Worsening": "In peggioramento",
    "Stable": "Stabile",

    // MARK: - Analysis Periods
    "7 Days": "7 Giorni",
    "30 Days": "30 Giorni",
    "90 Days": "90 Giorni",
    "All": "Tutti",

    // MARK: - Notification Categories
    "Daily Check-in": "Check-in Giornaliero",
    "Dream Reflection": "Riflessione sui Sogni",
    "Nightmare Follow-up": "Follow-up Incubi",
    "Weekly Digest": "Riepilogo Settimanale",
    "Gentle reminder to log your dreams": "Promemoria gentile per registrare i tuoi sogni",
    "Reflect on dreams you've recorded": "Rifletti sui sogni che hai registrato",
    "Check in after rewriting a nightmare": "Controlla dopo aver riscritto un incubo",
    "Weekly summary of your dream journey": "Riepilogo settimanale del tuo percorso onirico",

    // MARK: - Notification Frequencies
    "Every Day": "Ogni Giorno",
    "Weekdays Only": "Solo Giorni Feriali",
    "Weekends Only": "Solo Fine Settimana",
    "Once a Week": "Una Volta a Settimana",
    "Custom Days": "Giorni Personalizzati",

    // MARK: - Day Names
    "Sun": "Dom",
    "Mon": "Lun",
    "Tue": "Mar",
    "Wed": "Mer",
    "Thu": "Gio",
    "Fri": "Ven",
    "Sat": "Sab",

    // MARK: - Notification Templates
    "Good morning!": "Buongiorno!",
    "Dream Journal Time": "È Ora del Diario dei Sogni",
    "Remember Your Dreams?": "Ricordi i Tuoi Sogni?",
    "Start Your Day Mindfully": "Inizia la Giornata con Consapevolezza",
    "Did you dream last night? Take a moment to record it.": "Hai sognato la notte scorsa? Prenditi un momento per registrarlo.",
    "Your dreams are waiting to be captured.": "I tuoi sogni aspettano di essere catturati.",
    "A few minutes to log your dreams can make a big difference.": "Pochi minuti per registrare i tuoi sogni possono fare una grande differenza.",
    "Dreams fade quickly - save yours now.": "I sogni svaniscono in fretta - salva i tuoi adesso.",
    "Time to Reflect": "Tempo di Riflettere",
    "Dream Insight": "Intuizione Onirica",
    "Look Back": "Guarda Indietro",
    "Your Dream Journey": "Il Tuo Percorso Onirico",
    "Revisit a dream you recorded and see how it makes you feel now.": "Rivisita un sogno che hai registrato e scopri come ti fa sentire adesso.",
    "Your past dreams might hold insights for today.": "I tuoi sogni passati potrebbero avere intuizioni per oggi.",
    "Take a moment to reflect on your dream patterns.": "Prenditi un momento per riflettere sui tuoi schemi onirici.",
    "What have your dreams been telling you lately?": "Cosa ti hanno detto i tuoi sogni ultimamente?",
    "How Are You Feeling?": "Come Ti Senti?",
    "Gentle Check-in": "Controllo Gentile",
    "You're Doing Great": "Stai Andando Alla Grande",
    "Healing Journey": "Percorso di Guarigione",
    "How did the rewritten dream make you feel? Consider reading it again.": "Come ti ha fatto sentire il sogno riscritto? Considera di leggerlo di nuovo.",
    "Remember, you have the power to reshape your dreams.": "Ricorda, hai il potere di trasformare i tuoi sogni.",
    "Take a moment to revisit your peaceful dream version.": "Prenditi un momento per rivisitare la versione serena del tuo sogno.",
    "Your healing journey continues. We're here for you.": "Il tuo percorso di guarigione continua. Siamo qui per te.",
    "Your Week in Dreams": "La Tua Settimana nei Sogni",
    "Weekly Reflection": "Riflessione Settimanale",
    "Dream Summary": "Riepilogo dei Sogni",
    "This Week's Journey": "Il Percorso di Questa Settimana",
    "See how your dream patterns evolved this week.": "Scopri come i tuoi schemi onirici si sono evoluti questa settimana.",
    "Time for your weekly dream check-in.": "È ora del tuo check-in settimanale sui sogni.",
    "Reflect on your dream journey this week.": "Rifletti sul tuo percorso onirico di questa settimana.",
    "A week of dreams - what stories did they tell?": "Una settimana di sogni - quali storie hanno raccontato?",
]
