// Romanian (ro)

let strings_ro: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "CONECTARE!",
    "SIGN UP!": "\u{00CE}NREGISTRARE!",
    "Account": "Cont",
    "Email": "E-mail",
    "Password": "Parol\u{0103}",
    "Profile": "Profil",
    "Age": "V\u{00E2}rst\u{0103}",
    "Timezone (e.g., %@)": "Fus orar (de ex., %@)",
    "LOADING!": "SE \u{00CE}NCARC\u{0102}!",
    "Log In": "Conectare",
    "Create Account": "Creeaz\u{0103} cont",
    "Need an account?": "Ai nevoie de un cont?",
    "Have an account?": "Ai deja un cont?",
    "Sign Up": "\u{00CE}nregistrare",

    // MARK: - Content / Main
    "No dreams match your search": "Niciun vis nu corespunde c\u{0103}ut\u{0103}rii tale",
    "Dreams": "Vise",
    "Search dreams...": "Caut\u{0103} vise...",
    "Welcome, Dreamer!": "Bine ai venit, Vis\u{0103}tor!",
    "DREAM ON!": "VISEAZ\u{0102} \u{00CE}N CONTINUARE!",
    "Record your first dream to begin your comic journey!": "\u{00CE}nregistreaz\u{0103}-\u{021B}i primul vis pentru a \u{00EE}ncepe c\u{0103}l\u{0103}toria ta de benzi desenate!",
    "Capture a Dream": "Captureaz\u{0103} un vis",
    "DELETE": "\u{015E}TERGE",

    // MARK: - New Dream
    "What did you dream?": "Ce ai visat?",
    "Describe your dream or nightmare...": "Descrie-\u{021B}i visul sau co\u{015F}marul...",
    "Stop Recording": "Opre\u{015F}te \u{00EE}nregistrarea",
    "Record Dream": "\u{00CE}nregistreaz\u{0103} visul",
    "Tap to stop voice recording": "Apas\u{0103} pentru a opri \u{00EE}nregistrarea vocal\u{0103}",
    "Tap to start describing your dream with your voice": "Apas\u{0103} pentru a \u{00EE}ncepe s\u{0103}-\u{021B}i descrii visul cu vocea",
    "Listening...": "Ascult...",
    "When did you see this dream?": "C\u{00E2}nd ai avut acest vis?",
    "Save Dream": "Salveaz\u{0103} visul",
    "New Dream": "Vis nou",

    // MARK: - Common Actions
    "Cancel": "Anuleaz\u{0103}",
    "Save": "Salveaz\u{0103}",
    "Edit": "Editeaz\u{0103}",
    "Delete": "\u{015E}terge",
    "Done": "Gata",
    "Try Again": "\u{00CE}ncearc\u{0103} din nou",
    "Retry": "Re\u{00EE}ncearc\u{0103}",
    "Add": "Adaug\u{0103}",
    "View": "Vizualizeaz\u{0103}",

    // MARK: - Dream Detail
    "Dream date": "Data visului",
    "Original Dream": "Visul original",
    "Dream Analysis": "Analiza visului",
    "ANALYZING!": "SE ANALIZEAZ\u{0102}!",
    "Rewritten Dream (%@)": "Vis rescris (%@)",
    "Stop": "Stop",
    "Play Story": "Red\u{0103} povestea",
    "Tap to stop reading the story": "Apas\u{0103} pentru a opri citirea pove\u{015F}tii",
    "Tap to hear the story read aloud": "Apas\u{0103} pentru a auzi povestea citit\u{0103} cu voce tare",
    "Try a Different Tone?": "\u{00CE}ncerci un alt ton?",
    "How Should This Dream Feel?": "Cum ar trebui s\u{0103} se simt\u{0103} acest vis?",
    "Narrating!": "Se nareaz\u{0103}!",
    "Narrate Again": "Nareaz\u{0103} din nou",
    "Narrate": "Nareaz\u{0103}",
    "Delete Dream": "\u{015E}terge visul",
    "Dream": "Vis",
    "Delete this dream?": "\u{015E}tergi acest vis?",
    "This will permanently remove this dream and all its content.": "Aceasta va elimina permanent acest vis \u{015F}i tot con\u{021B}inutul s\u{0103}u.",

    // MARK: - Tones
    "Happy": "Fericit",
    "Funny": "Amuzant",
    "Hopeful": "Plin de speran\u{021B}\u{0103}",
    "Calm": "Calm",
    "Positive": "Pozitiv",

    // MARK: - Dream Analysis
    "Time Period": "Perioad\u{0103} de timp",
    "Period": "Perioad\u{0103}",
    "Emotion Trends": "Tendin\u{021B}e emo\u{021B}ionale",
    "Loading trends...": "Se \u{00EE}ncarc\u{0103} tendin\u{021B}ele...",
    "Loading summary...": "Se \u{00EE}ncarc\u{0103} rezumatul...",
    "Summary": "Rezumat",
    "Most Common Feeling": "Cel mai frecvent sentiment",
    "Average intensity: %.0f%%": "Intensitate medie: %.0f%%",
    "dreams": "vise",
    "Suggested Moods": "St\u{0103}ri sugerate",
    "Activity": "Activitate",
    "Keep logging dreams to see trends": "Continu\u{0103} s\u{0103} \u{00EE}nregistrezi vise pentru a vedea tendin\u{021B}ele",
    "Record your first dream to start tracking your emotions": "\u{00CE}nregistreaz\u{0103}-\u{021B}i primul vis pentru a \u{00EE}ncepe s\u{0103}-\u{021B}i urmezi emo\u{021B}iile",
    "ZAP!": "ZAP!",
    "OOPS!": "HOPA!",

    // MARK: - Settings
    "Signed in": "Conectat",
    "Cloud sync enabled": "Sincronizare cloud activat\u{0103}",
    "Sign In / Sign Up": "Conectare / \u{00CE}nregistrare",
    "Create an account to sync dreams and AI content.": "Creeaz\u{0103} un cont pentru a sincroniza visele \u{015F}i con\u{021B}inutul AI.",
    "Notifications": "Notific\u{0103}ri",
    "Notification Settings": "Set\u{0103}ri notific\u{0103}ri",
    "Settings": "Set\u{0103}ri",
    "Dream Character": "Personajul visului",
    "These details personalize your dream comics": "Aceste detalii personalizeaz\u{0103} benzile tale desenate de vise",
    "Sign Out": "Deconectare",
    "Gender": "Gen",
    "Male": "Masculin",
    "Female": "Feminin",
    "Non-binary": "Non-binar",
    "Prefer not to say": "Prefer s\u{0103} nu spun",
    "Language": "Limb\u{0103}",

    // MARK: - Dream Visualization
    "Dream Visualization": "Vizualizarea visului",
    "AI creates a comic page from your dream": "AI creeaz\u{0103} o pagin\u{0103} de band\u{0103} desenat\u{0103} din visul t\u{0103}u",
    "Include my likeness": "Include asem\u{0103}narea mea",
    "OFFLINE!": "OFFLINE!",
    "Image generation requires Apple Silicon or sign-in.": "Generarea de imagini necesit\u{0103} Apple Silicon sau conectare.",
    "Draw my dream!": "Deseneaz\u{0103}-mi visul!",
    "Redraw my dream!": "Redeseneaz\u{0103}-mi visul!",
    "Regenerate as Comic Page": "Regenereaz\u{0103} ca pagin\u{0103} de band\u{0103} desenat\u{0103}",
    "CREATING!": "SE CREEAZ\u{0102}!",
    "Painting your dream...": "Se picteaz\u{0103} visul t\u{0103}u...",
    "Add your details in Profile to appear in your dreams!": "Adaug\u{0103}-\u{021B}i detaliile \u{00EE}n Profil pentru a ap\u{0103}rea \u{00EE}n visele tale!",
    "Scene %d": "Scena %d",
    "Save your dreams!": "Salveaz\u{0103}-\u{021B}i visele!",
    "Sign up to sync rewrites and comics across devices.": "\u{00CE}nregistreaz\u{0103}-te pentru a sincroniza rescrierile \u{015F}i benzile desenate pe toate dispozitivele.",
    "Dream Sequence": "Secven\u{021B}\u{0103} de vis",
    "Dream Comic Page": "Pagin\u{0103} de band\u{0103} desenat\u{0103} de vis",

    // MARK: - Notifications
    "Notifications Enabled": "Notific\u{0103}ri activate",
    "Enable Notifications": "Activeaz\u{0103} notific\u{0103}rile",
    "Permission": "Permisiune",
    "Allow notifications to receive reminders and follow-ups.": "Permite notific\u{0103}rile pentru a primi memento-uri \u{015F}i urm\u{0103}riri.",
    "Notification Types": "Tipuri de notific\u{0103}ri",
    "Configure each notification type independently with its own schedule.": "Configureaz\u{0103} fiecare tip de notificare independent cu propriul program.",
    "Permission Required": "Permisiune necesar\u{0103}",
    "Open Settings": "Deschide set\u{0103}rile",
    "Please enable notifications in Settings to receive reminders.": "Te rug\u{0103}m s\u{0103} activezi notific\u{0103}rile \u{00EE}n Set\u{0103}ri pentru a primi memento-uri.",
    "When to Notify": "C\u{00E2}nd s\u{0103} notifice",
    "Time of Day": "Ora din zi",
    "Day of Week": "Ziua s\u{0103}pt\u{0103}m\u{00E2}nii",
    "Select Days": "Selecteaz\u{0103} zilele",
    "Preview": "Previzualizare",
    "Frequency": "Frecven\u{021B}\u{0103}",
    "Time": "Or\u{0103}",
    "Day": "Zi",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Vei primi o notificare \u{00EE}n fiecare zi la %@.",
    "You'll receive notifications Monday through Friday at %@.": "Vei primi notific\u{0103}ri de luni p\u{00E2}n\u{0103} vineri la %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Vei primi notific\u{0103}ri s\u{00E2}mb\u{0103}ta \u{015F}i duminica la %@.",
    "You'll receive a notification every %@ at %@.": "Vei primi o notificare \u{00EE}n fiecare %@ la %@.",
    "Select at least one day to receive notifications.": "Selecteaz\u{0103} cel pu\u{021B}in o zi pentru a primi notific\u{0103}ri.",
    "You'll receive notifications on %@ at %@.": "Vei primi notific\u{0103}ri pe %@ la %@.",

    // MARK: - Dream Reminders
    "Reminders": "Memento-uri",
    "No reminders set": "Niciun memento setat",
    "Add a reminder to revisit this dream": "Adaug\u{0103} un memento pentru a revizita acest vis",
    "EXPIRED": "EXPIRAT",
    "REMINDER TYPE": "TIP MEMENTO",
    "WHEN": "C\u{00C2}ND",
    "PREVIEW": "PREVIZUALIZARE",
    "Custom": "Personalizat",
    "Add Reminder": "Adaug\u{0103} memento",
    "Date & Time": "Data \u{015F}i ora",
    "1 hour": "1 or\u{0103}",
    "6 hours": "6 ore",
    "Tomorrow": "M\u{00E2}ine",
    "2 days": "2 zile",
    "1 week": "1 s\u{0103}pt\u{0103}m\u{00E2}n\u{0103}",
    "You'll receive a \"%@\" reminder on %@": "Vei primi un memento \"%@\" pe %@",

    // MARK: - Avatar
    "Use This Photo": "Folose\u{015F}te aceast\u{0103} fotografie",
    "Use Memoji": "Folose\u{015F}te Memoji",
    "Choose Photo": "Alege fotografie",
    "Take Photo": "F\u{0103} o fotografie",
    "Remove Avatar": "Elimin\u{0103} avatarul",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Fotografia ta creeaz\u{0103} o descriere text a aspectului t\u{0103}u. Fotografia \u{00EE}n sine nu este partajat\u{0103} cu serviciile AI.",
    "Profile Picture": "Fotografie de profil",
    "Paste Your Memoji": "Lipe\u{015F}te Memoji-ul t\u{0103}u",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Apas\u{0103} pe c\u{00E2}mpul de text de mai jos\n2. Comut\u{0103} la tastatura Memoji\n3. Apas\u{0103} pe stickerul Memoji preferat",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Apas\u{0103} aici, apoi lipe\u{015F}te Memoji...",
    "Uploading...": "Se \u{00EE}ncarc\u{0103}...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Suger\u{0103}m rescrierea acestuia ca un ",
    " dream": " vis",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Frică",
    "Sadness": "Tristețe",
    "Anger": "Furie",
    "Anxiety": "Anxietate",
    "Stress": "Stres",
    "Loneliness": "Singurătate",
    "Helplessness": "Neputință",
    "Shame": "Rușine",
    "Grief": "Doliu",
    "Confusion": "Confuzie",
    "Joy": "Bucurie",
    "Love": "Iubire",
    "Surprise": "Surpriză",
    "Disgust": "Dezgust",
    "Trust": "Încredere",
    "Anticipation": "Anticipare",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Pașnic",
    "Serene": "Senin",
    "Humorous": "Amuzant",
    "Lighthearted": "Ușor",
    "Empowering": "Împuternicitor",
    "Confident": "Încrezător",
    "Optimistic": "Optimist",
    "Inspiring": "Inspirațional",
    "Joyful": "Vesel",
    "Cheerful": "Voios",
    "Neutral": "Neutru",

    // MARK: - Trend Directions
    "Improving": "În îmbunătățire",
    "Worsening": "În deteriorare",
    "Stable": "Stabil",

    // MARK: - Analysis Periods
    "7 Days": "7 zile",
    "30 Days": "30 de zile",
    "90 Days": "90 de zile",
    "All": "Toate",

    // MARK: - Notification Categories
    "Daily Check-in": "Check-in zilnic",
    "Dream Reflection": "Reflec\u{021B}ia visului",
    "Nightmare Follow-up": "Urm\u{0103}rire co\u{015F}mar",
    "Weekly Digest": "Rezumat s\u{0103}pt\u{0103}m\u{00E2}nal",
    "Gentle reminder to log your dreams": "Memento delicat pentru a-\u{021B}i \u{00EE}nregistra visele",
    "Reflect on dreams you've recorded": "Reflect\u{0103} asupra viselor pe care le-ai \u{00EE}nregistrat",
    "Check in after rewriting a nightmare": "Verific\u{0103} dup\u{0103} rescrierea unui co\u{015F}mar",
    "Weekly summary of your dream journey": "Rezumatul s\u{0103}pt\u{0103}m\u{00E2}nal al c\u{0103}l\u{0103}toriei tale de vise",

    // MARK: - Notification Frequencies
    "Every Day": "\u{00CE}n fiecare zi",
    "Weekdays Only": "Doar \u{00EE}n zilele lucr\u{0103}toare",
    "Weekends Only": "Doar \u{00EE}n weekend",
    "Once a Week": "O dat\u{0103} pe s\u{0103}pt\u{0103}m\u{00E2}n\u{0103}",
    "Custom Days": "Zile personalizate",

    // MARK: - Day Names
    "Sun": "Dum",
    "Mon": "Lun",
    "Tue": "Mar",
    "Wed": "Mie",
    "Thu": "Joi",
    "Fri": "Vin",
    "Sat": "S\u{00E2}m",

    // MARK: - Notification Templates
    "Good morning!": "Bun\u{0103} diminea\u{021B}a!",
    "Dream Journal Time": "Timpul jurnalului de vise",
    "Remember Your Dreams?": "\u{00CE}\u{021B}i aminte\u{015F}ti visele?",
    "Start Your Day Mindfully": "\u{00CE}ncepe-\u{021B}i ziua con\u{015F}tient",
    "Did you dream last night? Take a moment to record it.": "Ai visat noaptea trecut\u{0103}? Ia un moment s\u{0103} \u{00EE}l \u{00EE}nregistrezi.",
    "Your dreams are waiting to be captured.": "Visele tale a\u{015F}teapt\u{0103} s\u{0103} fie capturate.",
    "A few minutes to log your dreams can make a big difference.": "C\u{00E2}teva minute pentru a-\u{021B}i nota visele pot face o mare diferen\u{021B}\u{0103}.",
    "Dreams fade quickly - save yours now.": "Visele se estompeaz\u{0103} repede \u{2013} salveaz\u{0103}-le acum.",
    "Time to Reflect": "Timpul s\u{0103} reflectezi",
    "Dream Insight": "Perspectiv\u{0103} asupra visului",
    "Look Back": "Privire \u{00EE}napoi",
    "Your Dream Journey": "C\u{0103}l\u{0103}toria ta de vise",
    "Revisit a dream you recorded and see how it makes you feel now.": "Reviziteaz\u{0103} un vis pe care l-ai \u{00EE}nregistrat \u{015F}i vezi cum te face s\u{0103} te sim\u{021B}i acum.",
    "Your past dreams might hold insights for today.": "Visele tale trecute ar putea con\u{021B}ine perspective pentru ast\u{0103}zi.",
    "Take a moment to reflect on your dream patterns.": "Ia un moment s\u{0103} reflectezi asupra tiparelor tale de vise.",
    "What have your dreams been telling you lately?": "Ce \u{021B}i-au spus visele \u{00EE}n ultimul timp?",
    "How Are You Feeling?": "Cum te sim\u{021B}i?",
    "Gentle Check-in": "Check-in delicat",
    "You're Doing Great": "Te descurci excelent",
    "Healing Journey": "C\u{0103}l\u{0103}torie de vindecare",
    "How did the rewritten dream make you feel? Consider reading it again.": "Cum te-a f\u{0103}cut s\u{0103} te sim\u{021B}i visul rescris? Consider\u{0103} s\u{0103}-l cite\u{015F}ti din nou.",
    "Remember, you have the power to reshape your dreams.": "Aminte\u{015F}te-\u{021B}i, ai puterea de a-\u{021B}i remodela visele.",
    "Take a moment to revisit your peaceful dream version.": "Ia un moment s\u{0103} revizitezi versiunea pa\u{015F}nic\u{0103} a visului t\u{0103}u.",
    "Your healing journey continues. We're here for you.": "C\u{0103}l\u{0103}toria ta de vindecare continu\u{0103}. Suntem aici pentru tine.",
    "Your Week in Dreams": "S\u{0103}pt\u{0103}m\u{00E2}na ta \u{00EE}n vise",
    "Weekly Reflection": "Reflec\u{021B}ie s\u{0103}pt\u{0103}m\u{00E2}nal\u{0103}",
    "Dream Summary": "Rezumatul visului",
    "This Week's Journey": "C\u{0103}l\u{0103}toria acestei s\u{0103}pt\u{0103}m\u{00E2}ni",
    "See how your dream patterns evolved this week.": "Vezi cum au evoluat tiparele tale de vise \u{00EE}n aceast\u{0103} s\u{0103}pt\u{0103}m\u{00E2}n\u{0103}.",
    "Time for your weekly dream check-in.": "E timpul pentru check-in-ul s\u{0103}pt\u{0103}m\u{00E2}nal al viselor.",
    "Reflect on your dream journey this week.": "Reflect\u{0103} asupra c\u{0103}l\u{0103}toriei tale de vise din aceast\u{0103} s\u{0103}pt\u{0103}m\u{00E2}n\u{0103}.",
    "A week of dreams - what stories did they tell?": "O s\u{0103}pt\u{0103}m\u{00E2}n\u{0103} de vise \u{2013} ce pove\u{015F}ti au spus?",
]
