// Czech (cs)

let strings_cs: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "PŘIHLÁSIT SE!",
    "SIGN UP!": "REGISTROVAT SE!",
    "Account": "Účet",
    "Email": "E-mail",
    "Password": "Heslo",
    "Profile": "Profil",
    "Age": "Věk",
    "Timezone (e.g., %@)": "Časové pásmo (např. %@)",
    "LOADING!": "NAČÍTÁNÍ!",
    "Log In": "Přihlásit se",
    "Create Account": "Vytvořit účet",
    "Need an account?": "Potřebujete účet?",
    "Have an account?": "Máte účet?",
    "Sign Up": "Registrovat se",

    // MARK: - Content / Main
    "No dreams match your search": "Žádné sny neodpovídají vašemu hledání",
    "Dreams": "Sny",
    "Search dreams...": "Hledat sny...",
    "Welcome, Dreamer!": "Vítej, Sníku!",
    "DREAM ON!": "SNI DÁL!",
    "Record your first dream to begin your comic journey!": "Zaznamenej svůj první sen a začni svou komiksovou cestu!",
    "Capture a Dream": "Zachyť sen",
    "DELETE": "SMAZAT",

    // MARK: - New Dream
    "What did you dream?": "Co se ti zdálo?",
    "Describe your dream or nightmare...": "Popiš svůj sen nebo noční můru...",
    "Stop Recording": "Zastavit nahrávání",
    "Record Dream": "Nahrát sen",
    "Tap to stop voice recording": "Klepni pro zastavení hlasového nahrávání",
    "Tap to start describing your dream with your voice": "Klepni pro popsání snu hlasem",
    "Listening...": "Poslouchám...",
    "When did you see this dream?": "Kdy se ti tento sen zdál?",
    "Save Dream": "Uložit sen",
    "New Dream": "Nový sen",

    // MARK: - Common Actions
    "Cancel": "Zrušit",
    "Save": "Uložit",
    "Edit": "Upravit",
    "Delete": "Smazat",
    "Done": "Hotovo",
    "Try Again": "Zkusit znovu",
    "Retry": "Opakovat",
    "Add": "Přidat",
    "View": "Zobrazit",

    // MARK: - Dream Detail
    "Dream date": "Datum snu",
    "Original Dream": "Původní sen",
    "Dream Analysis": "Analýza snu",
    "ANALYZING!": "ANALYZUJI!",
    "Rewritten Dream (%@)": "Přepsaný sen (%@)",
    "Stop": "Zastavit",
    "Play Story": "Přehrát příběh",
    "Tap to stop reading the story": "Klepni pro zastavení čtení příběhu",
    "Tap to hear the story read aloud": "Klepni pro poslech příběhu nahlas",
    "Try a Different Tone?": "Zkusit jiný tón?",
    "How Should This Dream Feel?": "Jak by měl tento sen působit?",
    "Narrating!": "Vyprávím!",
    "Narrate Again": "Vyprávět znovu",
    "Narrate": "Vyprávět",
    "Delete Dream": "Smazat sen",
    "Dream": "Sen",
    "Delete this dream?": "Smazat tento sen?",
    "This will permanently remove this dream and all its content.": "Tímto se trvale odstraní tento sen a veškerý jeho obsah.",

    // MARK: - Tones
    "Happy": "Veselý",
    "Funny": "Vtipný",
    "Hopeful": "Nadějný",
    "Calm": "Klidný",
    "Positive": "Pozitivní",

    // MARK: - Dream Analysis
    "Time Period": "Časové období",
    "Period": "Období",
    "Emotion Trends": "Trendy emocí",
    "Loading trends...": "Načítání trendů...",
    "Loading summary...": "Načítání souhrnu...",
    "Summary": "Souhrn",
    "Most Common Feeling": "Nejčastější pocit",
    "Average intensity: %.0f%%": "Průměrná intenzita: %.0f%%",
    "dreams": "sny",
    "Suggested Moods": "Navrhované nálady",
    "Activity": "Aktivita",
    "Keep logging dreams to see trends": "Zaznamenávej sny pro zobrazení trendů",
    "Record your first dream to start tracking your emotions": "Zaznamenej svůj první sen a začni sledovat své emoce",
    "ZAP!": "ZAP!",
    "OOPS!": "JEJDA!",

    // MARK: - Settings
    "Signed in": "Přihlášen",
    "Cloud sync enabled": "Synchronizace v cloudu zapnuta",
    "Sign In / Sign Up": "Přihlásit se / Registrovat se",
    "Create an account to sync dreams and AI content.": "Vytvoř si účet pro synchronizaci snů a AI obsahu.",
    "Notifications": "Oznámení",
    "Notification Settings": "Nastavení oznámení",
    "Settings": "Nastavení",
    "Dream Character": "Postava ze snu",
    "These details personalize your dream comics": "Tyto údaje personalizují tvé komiksové sny",
    "Sign Out": "Odhlásit se",
    "Gender": "Pohlaví",
    "Male": "Muž",
    "Female": "Žena",
    "Non-binary": "Nebinární",
    "Prefer not to say": "Nechci uvádět",
    "Language": "Jazyk",

    // MARK: - Dream Visualization
    "Dream Visualization": "Vizualizace snu",
    "AI creates a comic page from your dream": "AI vytvoří komiksovou stránku z tvého snu",
    "Include my likeness": "Zahrnout mou podobu",
    "OFFLINE!": "OFFLINE!",
    "Image generation requires Apple Silicon or sign-in.": "Generování obrázků vyžaduje Apple Silicon nebo přihlášení.",
    "Draw my dream!": "Nakresli můj sen!",
    "Redraw my dream!": "Překresli můj sen!",
    "Regenerate as Comic Page": "Přegenerovat jako komiksovou stránku",
    "CREATING!": "VYTVÁŘÍM!",
    "Painting your dream...": "Maluji tvůj sen...",
    "Add your details in Profile to appear in your dreams!": "Přidej své údaje v profilu, aby ses objevil ve svých snech!",
    "Scene %d": "Scéna %d",
    "Save your dreams!": "Ulož své sny!",
    "Sign up to sync rewrites and comics across devices.": "Zaregistruj se pro synchronizaci přepisů a komiksů napříč zařízeními.",
    "Dream Sequence": "Sekvence snu",
    "Dream Comic Page": "Komiksová stránka snu",

    // MARK: - Notifications
    "Notifications Enabled": "Oznámení zapnuta",
    "Enable Notifications": "Zapnout oznámení",
    "Permission": "Oprávnění",
    "Allow notifications to receive reminders and follow-ups.": "Povol oznámení pro příjem připomínek a následných zpráv.",
    "Notification Types": "Typy oznámení",
    "Configure each notification type independently with its own schedule.": "Nastav každý typ oznámení nezávisle s vlastním rozvrhem.",
    "Permission Required": "Vyžadováno oprávnění",
    "Open Settings": "Otevřít nastavení",
    "Please enable notifications in Settings to receive reminders.": "Povol oznámení v nastavení pro příjem připomínek.",
    "When to Notify": "Kdy upozornit",
    "Time of Day": "Denní doba",
    "Day of Week": "Den v týdnu",
    "Select Days": "Vybrat dny",
    "Preview": "Náhled",
    "Frequency": "Frekvence",
    "Time": "Čas",
    "Day": "Den",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Oznámení obdržíš každý den v %@.",
    "You'll receive notifications Monday through Friday at %@.": "Oznámení obdržíš od pondělí do pátku v %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Oznámení obdržíš v sobotu a v neděli v %@.",
    "You'll receive a notification every %@ at %@.": "Oznámení obdržíš každý %@ v %@.",
    "Select at least one day to receive notifications.": "Vyber alespoň jeden den pro příjem oznámení.",
    "You'll receive notifications on %@ at %@.": "Oznámení obdržíš v %@ v %@.",

    // MARK: - Dream Reminders
    "Reminders": "Připomínky",
    "No reminders set": "Žádné připomínky nenastaveny",
    "Add a reminder to revisit this dream": "Přidej připomínku pro návrat k tomuto snu",
    "EXPIRED": "VYPRŠELO",
    "REMINDER TYPE": "TYP PŘIPOMÍNKY",
    "WHEN": "KDY",
    "PREVIEW": "NÁHLED",
    "Custom": "Vlastní",
    "Add Reminder": "Přidat připomínku",
    "Date & Time": "Datum a čas",
    "1 hour": "1 hodina",
    "6 hours": "6 hodin",
    "Tomorrow": "Zítra",
    "2 days": "2 dny",
    "1 week": "1 týden",
    "You'll receive a \"%@\" reminder on %@": "Obdržíš připomínku \"%@\" dne %@",

    // MARK: - Avatar
    "Use This Photo": "Použít tuto fotku",
    "Use Memoji": "Použít Memoji",
    "Choose Photo": "Vybrat fotku",
    "Take Photo": "Vyfotit",
    "Remove Avatar": "Odstranit avatar",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Tvá fotka vytvoří textový popis tvého vzhledu. Samotná fotka není sdílena s AI službami.",
    "Profile Picture": "Profilový obrázek",
    "Paste Your Memoji": "Vlož své Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Klepni na textové pole níže\n2. Přepni na klávesnici Memoji\n3. Klepni na oblíbenou Memoji nálepku",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Klepni sem a vlož Memoji...",
    "Uploading...": "Nahrávání...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Navrhujeme přepsat tento sen jako ",
    " dream": " sen",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Strach",
    "Sadness": "Smutek",
    "Anger": "Hněv",
    "Anxiety": "Úzkost",
    "Stress": "Stres",
    "Loneliness": "Osamělost",
    "Helplessness": "Bezmocnost",
    "Shame": "Stud",
    "Grief": "Žal",
    "Confusion": "Zmatek",
    "Joy": "Radost",
    "Love": "Láska",
    "Surprise": "Překvapení",
    "Disgust": "Znechucení",
    "Trust": "Důvěra",
    "Anticipation": "Očekávání",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Klidný",
    "Serene": "Poklidný",
    "Humorous": "Humorný",
    "Lighthearted": "Bezstarostný",
    "Empowering": "Posilující",
    "Confident": "Sebejistý",
    "Optimistic": "Optimistický",
    "Inspiring": "Inspirativní",
    "Joyful": "Radostný",
    "Cheerful": "Veselý",
    "Neutral": "Neutrální",

    // MARK: - Trend Directions
    "Improving": "Zlepšující se",
    "Worsening": "Zhoršující se",
    "Stable": "Stabilní",

    // MARK: - Analysis Periods
    "7 Days": "7 dní",
    "30 Days": "30 dní",
    "90 Days": "90 dní",
    "All": "Vše",

    // MARK: - Notification Categories
    "Daily Check-in": "Denní kontrola",
    "Dream Reflection": "Zamyšlení nad snem",
    "Nightmare Follow-up": "Návaznost po noční můře",
    "Weekly Digest": "Týdenní souhrn",
    "Gentle reminder to log your dreams": "Jemná připomínka zaznamenat sny",
    "Reflect on dreams you've recorded": "Zamysli se nad sny, které jsi zaznamenal",
    "Check in after rewriting a nightmare": "Zkontroluj se po přepsání noční můry",
    "Weekly summary of your dream journey": "Týdenní shrnutí tvé cesty se sny",

    // MARK: - Notification Frequencies
    "Every Day": "Každý den",
    "Weekdays Only": "Pouze pracovní dny",
    "Weekends Only": "Pouze víkendy",
    "Once a Week": "Jednou týdně",
    "Custom Days": "Vlastní dny",

    // MARK: - Day Names
    "Sun": "Ne",
    "Mon": "Po",
    "Tue": "Út",
    "Wed": "St",
    "Thu": "Čt",
    "Fri": "Pá",
    "Sat": "So",

    // MARK: - Notification Templates
    "Good morning!": "Dobré ráno!",
    "Dream Journal Time": "Čas na deník snů",
    "Remember Your Dreams?": "Pamatuješ si své sny?",
    "Start Your Day Mindfully": "Začni den s rozmyslem",
    "Did you dream last night? Take a moment to record it.": "Zdálo se ti dnes v noci? Věnuj chvíli záznamu.",
    "Your dreams are waiting to be captured.": "Tvé sny čekají na zachycení.",
    "A few minutes to log your dreams can make a big difference.": "Pár minut na záznam snů může udělat velký rozdíl.",
    "Dreams fade quickly - save yours now.": "Sny rychle blednou - ulož je hned.",
    "Time to Reflect": "Čas na zamyšlení",
    "Dream Insight": "Vhled do snů",
    "Look Back": "Ohlédnutí",
    "Your Dream Journey": "Tvá cesta se sny",
    "Revisit a dream you recorded and see how it makes you feel now.": "Vrať se k zaznamenanému snu a zjisti, jak se teď cítíš.",
    "Your past dreams might hold insights for today.": "Tvé minulé sny mohou skrývat poznatky pro dnešek.",
    "Take a moment to reflect on your dream patterns.": "Věnuj chvíli zamyšlení nad vzorci svých snů.",
    "What have your dreams been telling you lately?": "Co ti v poslední době říkají tvé sny?",
    "How Are You Feeling?": "Jak se cítíš?",
    "Gentle Check-in": "Jemná kontrola",
    "You're Doing Great": "Jde ti to skvěle",
    "Healing Journey": "Cesta k uzdravení",
    "How did the rewritten dream make you feel? Consider reading it again.": "Jak ses cítil po přepsaném snu? Zvaž jeho opětovné přečtení.",
    "Remember, you have the power to reshape your dreams.": "Pamatuj, máš sílu přetvořit své sny.",
    "Take a moment to revisit your peaceful dream version.": "Věnuj chvíli klidné verzi svého snu.",
    "Your healing journey continues. We're here for you.": "Tvá cesta k uzdravení pokračuje. Jsme tu pro tebe.",
    "Your Week in Dreams": "Tvůj týden ve snech",
    "Weekly Reflection": "Týdenní zamyšlení",
    "Dream Summary": "Souhrn snů",
    "This Week's Journey": "Cesta tohoto týdne",
    "See how your dream patterns evolved this week.": "Podívej se, jak se tento týden vyvíjely vzorce tvých snů.",
    "Time for your weekly dream check-in.": "Čas na týdenní kontrolu snů.",
    "Reflect on your dream journey this week.": "Zamysli se nad svou cestou se sny tento týden.",
    "A week of dreams - what stories did they tell?": "Týden snů - jaké příběhy vyprávěly?",
]
