// Spanish (es)

let strings_es: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "¡INICIAR SESIÓN!",
    "SIGN UP!": "¡REGISTRARSE!",
    "Account": "Cuenta",
    "Email": "Correo electrónico",
    "Password": "Contraseña",
    "Profile": "Perfil",
    "Age": "Edad",
    "Timezone (e.g., %@)": "Zona horaria (ej., %@)",
    "LOADING!": "¡CARGANDO!",
    "Log In": "Iniciar Sesión",
    "Create Account": "Crear Cuenta",
    "Need an account?": "¿Necesitas una cuenta?",
    "Have an account?": "¿Ya tienes cuenta?",
    "Sign Up": "Registrarse",

    // MARK: - Content / Main
    "No dreams match your search": "Ningún sueño coincide con tu búsqueda",
    "Dreams": "Sueños",
    "Search dreams...": "Buscar sueños...",
    "Welcome, Dreamer!": "¡Bienvenido, Soñador!",
    "DREAM ON!": "¡A SOÑAR!",
    "Record your first dream to begin your comic journey!": "¡Registra tu primer sueño para comenzar tu aventura en cómic!",
    "Capture a Dream": "Capturar un Sueño",
    "DELETE": "ELIMINAR",

    // MARK: - New Dream
    "What did you dream?": "¿Qué soñaste?",
    "Describe your dream or nightmare...": "Describe tu sueño o pesadilla...",
    "Stop Recording": "Detener Grabación",
    "Record Dream": "Grabar Sueño",
    "Tap to stop voice recording": "Toca para detener la grabación de voz",
    "Tap to start describing your dream with your voice": "Toca para empezar a describir tu sueño con tu voz",
    "Listening...": "Escuchando...",
    "When did you see this dream?": "¿Cuándo tuviste este sueño?",
    "Save Dream": "Guardar Sueño",
    "New Dream": "Nuevo Sueño",

    // MARK: - Common Actions
    "Cancel": "Cancelar",
    "Save": "Guardar",
    "Edit": "Editar",
    "Delete": "Eliminar",
    "Done": "Listo",
    "Try Again": "Intentar de Nuevo",
    "Retry": "Reintentar",
    "Add": "Añadir",
    "View": "Ver",

    // MARK: - Dream Detail
    "Dream date": "Fecha del sueño",
    "Original Dream": "Sueño Original",
    "Dream Analysis": "Análisis del Sueño",
    "ANALYZING!": "¡ANALIZANDO!",
    "Rewritten Dream (%@)": "Sueño Reescrito (%@)",
    "Stop": "Detener",
    "Play Story": "Reproducir Historia",
    "Tap to stop reading the story": "Toca para detener la lectura de la historia",
    "Tap to hear the story read aloud": "Toca para escuchar la historia en voz alta",
    "Try a Different Tone?": "¿Probar un Tono Diferente?",
    "How Should This Dream Feel?": "¿Cómo Debería Sentirse Este Sueño?",
    "Narrating!": "¡Narrando!",
    "Narrate Again": "Narrar de Nuevo",
    "Narrate": "Narrar",
    "Delete Dream": "Eliminar Sueño",
    "Dream": "Sueño",
    "Delete this dream?": "¿Eliminar este sueño?",
    "This will permanently remove this dream and all its content.": "Esto eliminará permanentemente este sueño y todo su contenido.",

    // MARK: - Tones
    "Happy": "Feliz",
    "Funny": "Divertido",
    "Hopeful": "Esperanzador",
    "Calm": "Tranquilo",
    "Positive": "Positivo",

    // MARK: - Dream Analysis
    "Time Period": "Período de Tiempo",
    "Period": "Período",
    "Emotion Trends": "Tendencias Emocionales",
    "Loading trends...": "Cargando tendencias...",
    "Loading summary...": "Cargando resumen...",
    "Summary": "Resumen",
    "Most Common Feeling": "Emoción Más Común",
    "Average intensity: %.0f%%": "Intensidad promedio: %.0f%%",
    "dreams": "sueños",
    "Suggested Moods": "Estados de Ánimo Sugeridos",
    "Activity": "Actividad",
    "Keep logging dreams to see trends": "Sigue registrando sueños para ver tendencias",
    "Record your first dream to start tracking your emotions": "Registra tu primer sueño para empezar a rastrear tus emociones",
    "ZAP!": "¡ZAS!",
    "OOPS!": "¡UPS!",

    // MARK: - Settings
    "Signed in": "Sesión iniciada",
    "Cloud sync enabled": "Sincronización en la nube activada",
    "Sign In / Sign Up": "Iniciar Sesión / Registrarse",
    "Create an account to sync dreams and AI content.": "Crea una cuenta para sincronizar sueños y contenido de IA.",
    "Notifications": "Notificaciones",
    "Notification Settings": "Ajustes de Notificaciones",
    "Settings": "Ajustes",
    "Dream Character": "Personaje del Sueño",
    "These details personalize your dream comics": "Estos detalles personalizan tus cómics de sueños",
    "Sign Out": "Cerrar Sesión",
    "Gender": "Género",
    "Male": "Masculino",
    "Female": "Femenino",
    "Non-binary": "No binario",
    "Prefer not to say": "Prefiero no decir",
    "Language": "Idioma",

    // MARK: - Dream Visualization
    "Dream Visualization": "Visualización del Sueño",
    "AI creates a comic page from your dream": "La IA crea una página de cómic a partir de tu sueño",
    "Include my likeness": "Incluir mi apariencia",
    "OFFLINE!": "¡SIN CONEXIÓN!",
    "Image generation requires Apple Silicon or sign-in.": "La generación de imágenes requiere Apple Silicon o iniciar sesión.",
    "Draw my dream!": "¡Dibuja mi sueño!",
    "Redraw my dream!": "¡Redibuja mi sueño!",
    "Regenerate as Comic Page": "Regenerar como Página de Cómic",
    "CREATING!": "¡CREANDO!",
    "Painting your dream...": "Pintando tu sueño...",
    "Add your details in Profile to appear in your dreams!": "¡Añade tus datos en el Perfil para aparecer en tus sueños!",
    "Scene %d": "Escena %d",
    "Save your dreams!": "¡Guarda tus sueños!",
    "Sign up to sync rewrites and comics across devices.": "Regístrate para sincronizar reescrituras y cómics en todos tus dispositivos.",
    "Dream Sequence": "Secuencia del Sueño",
    "Dream Comic Page": "Página de Cómic del Sueño",

    // MARK: - Notifications
    "Notifications Enabled": "Notificaciones Activadas",
    "Enable Notifications": "Activar Notificaciones",
    "Permission": "Permiso",
    "Allow notifications to receive reminders and follow-ups.": "Permite las notificaciones para recibir recordatorios y seguimientos.",
    "Notification Types": "Tipos de Notificación",
    "Configure each notification type independently with its own schedule.": "Configura cada tipo de notificación de forma independiente con su propio horario.",
    "Permission Required": "Permiso Requerido",
    "Open Settings": "Abrir Ajustes",
    "Please enable notifications in Settings to receive reminders.": "Activa las notificaciones en Ajustes para recibir recordatorios.",
    "When to Notify": "Cuándo Notificar",
    "Time of Day": "Hora del Día",
    "Day of Week": "Día de la Semana",
    "Select Days": "Seleccionar Días",
    "Preview": "Vista Previa",
    "Frequency": "Frecuencia",
    "Time": "Hora",
    "Day": "Día",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Recibirás una notificación cada día a las %@.",
    "You'll receive notifications Monday through Friday at %@.": "Recibirás notificaciones de lunes a viernes a las %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Recibirás notificaciones los sábados y domingos a las %@.",
    "You'll receive a notification every %@ at %@.": "Recibirás una notificación cada %@ a las %@.",
    "Select at least one day to receive notifications.": "Selecciona al menos un día para recibir notificaciones.",
    "You'll receive notifications on %@ at %@.": "Recibirás notificaciones el %@ a las %@.",

    // MARK: - Dream Reminders
    "Reminders": "Recordatorios",
    "No reminders set": "Sin recordatorios establecidos",
    "Add a reminder to revisit this dream": "Añade un recordatorio para revisitar este sueño",
    "EXPIRED": "EXPIRADO",
    "REMINDER TYPE": "TIPO DE RECORDATORIO",
    "WHEN": "CUÁNDO",
    "PREVIEW": "VISTA PREVIA",
    "Custom": "Personalizado",
    "Add Reminder": "Añadir Recordatorio",
    "Date & Time": "Fecha y Hora",
    "1 hour": "1 hora",
    "6 hours": "6 horas",
    "Tomorrow": "Mañana",
    "2 days": "2 días",
    "1 week": "1 semana",
    "You'll receive a \"%@\" reminder on %@": "Recibirás un recordatorio \"%@\" el %@",

    // MARK: - Avatar
    "Use This Photo": "Usar Esta Foto",
    "Use Memoji": "Usar Memoji",
    "Choose Photo": "Elegir Foto",
    "Take Photo": "Tomar Foto",
    "Remove Avatar": "Eliminar Avatar",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Tu foto crea una descripción textual de tu apariencia. La foto en sí no se comparte con los servicios de IA.",
    "Profile Picture": "Foto de Perfil",
    "Paste Your Memoji": "Pega Tu Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Toca el campo de texto de abajo\n2. Cambia al teclado de Memoji\n3. Toca tu sticker de Memoji favorito",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Toca aquí, luego pega Memoji...",
    "Uploading...": "Subiendo...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Sugerimos reescribir esto como un sueño ",
    " dream": "",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Miedo",
    "Sadness": "Tristeza",
    "Anger": "Ira",
    "Anxiety": "Ansiedad",
    "Stress": "Estrés",
    "Loneliness": "Soledad",
    "Helplessness": "Impotencia",
    "Shame": "Vergüenza",
    "Grief": "Duelo",
    "Confusion": "Confusión",
    "Joy": "Alegría",
    "Love": "Amor",
    "Surprise": "Sorpresa",
    "Disgust": "Asco",
    "Trust": "Confianza",
    "Anticipation": "Anticipación",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Pacífico",
    "Serene": "Sereno",
    "Humorous": "Humorístico",
    "Lighthearted": "Despreocupado",
    "Empowering": "Empoderador",
    "Confident": "Seguro",
    "Optimistic": "Optimista",
    "Inspiring": "Inspirador",
    "Joyful": "Dichoso",
    "Cheerful": "Alegre",
    "Neutral": "Neutral",

    // MARK: - Trend Directions
    "Improving": "Mejorando",
    "Worsening": "Empeorando",
    "Stable": "Estable",

    // MARK: - Analysis Periods
    "7 Days": "7 Días",
    "30 Days": "30 Días",
    "90 Days": "90 Días",
    "All": "Todos",

    // MARK: - Notification Categories
    "Daily Check-in": "Control Diario",
    "Dream Reflection": "Reflexión de Sueños",
    "Nightmare Follow-up": "Seguimiento de Pesadillas",
    "Weekly Digest": "Resumen Semanal",
    "Gentle reminder to log your dreams": "Recordatorio amable para registrar tus sueños",
    "Reflect on dreams you've recorded": "Reflexiona sobre los sueños que has registrado",
    "Check in after rewriting a nightmare": "Haz seguimiento después de reescribir una pesadilla",
    "Weekly summary of your dream journey": "Resumen semanal de tu viaje onírico",

    // MARK: - Notification Frequencies
    "Every Day": "Cada Día",
    "Weekdays Only": "Solo Días Laborables",
    "Weekends Only": "Solo Fines de Semana",
    "Once a Week": "Una Vez por Semana",
    "Custom Days": "Días Personalizados",

    // MARK: - Day Names
    "Sun": "Dom",
    "Mon": "Lun",
    "Tue": "Mar",
    "Wed": "Mié",
    "Thu": "Jue",
    "Fri": "Vie",
    "Sat": "Sáb",

    // MARK: - Notification Templates
    "Good morning!": "¡Buenos días!",
    "Dream Journal Time": "Hora del Diario de Sueños",
    "Remember Your Dreams?": "¿Recuerdas Tus Sueños?",
    "Start Your Day Mindfully": "Comienza Tu Día con Atención Plena",
    "Did you dream last night? Take a moment to record it.": "¿Soñaste anoche? Tómate un momento para registrarlo.",
    "Your dreams are waiting to be captured.": "Tus sueños esperan ser capturados.",
    "A few minutes to log your dreams can make a big difference.": "Unos minutos para registrar tus sueños pueden hacer una gran diferencia.",
    "Dreams fade quickly - save yours now.": "Los sueños se desvanecen rápido - guarda los tuyos ahora.",
    "Time to Reflect": "Hora de Reflexionar",
    "Dream Insight": "Percepción Onírica",
    "Look Back": "Mirar Atrás",
    "Your Dream Journey": "Tu Viaje Onírico",
    "Revisit a dream you recorded and see how it makes you feel now.": "Revisita un sueño que registraste y mira cómo te hace sentir ahora.",
    "Your past dreams might hold insights for today.": "Tus sueños pasados podrían tener revelaciones para hoy.",
    "Take a moment to reflect on your dream patterns.": "Tómate un momento para reflexionar sobre tus patrones oníricos.",
    "What have your dreams been telling you lately?": "¿Qué te han estado diciendo tus sueños últimamente?",
    "How Are You Feeling?": "¿Cómo Te Sientes?",
    "Gentle Check-in": "Control Amable",
    "You're Doing Great": "Lo Estás Haciendo Muy Bien",
    "Healing Journey": "Viaje de Sanación",
    "How did the rewritten dream make you feel? Consider reading it again.": "¿Cómo te hizo sentir el sueño reescrito? Considera leerlo de nuevo.",
    "Remember, you have the power to reshape your dreams.": "Recuerda, tienes el poder de transformar tus sueños.",
    "Take a moment to revisit your peaceful dream version.": "Tómate un momento para revisitar la versión pacífica de tu sueño.",
    "Your healing journey continues. We're here for you.": "Tu viaje de sanación continúa. Estamos aquí para ti.",
    "Your Week in Dreams": "Tu Semana en Sueños",
    "Weekly Reflection": "Reflexión Semanal",
    "Dream Summary": "Resumen de Sueños",
    "This Week's Journey": "El Viaje de Esta Semana",
    "See how your dream patterns evolved this week.": "Mira cómo evolucionaron tus patrones oníricos esta semana.",
    "Time for your weekly dream check-in.": "Es hora de tu control semanal de sueños.",
    "Reflect on your dream journey this week.": "Reflexiona sobre tu viaje onírico esta semana.",
    "A week of dreams - what stories did they tell?": "Una semana de sueños - ¿qué historias contaron?",
]
