// German (de)

let strings_de: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "ANMELDEN!",
    "SIGN UP!": "REGISTRIEREN!",
    "Account": "Konto",
    "Email": "E-Mail",
    "Password": "Passwort",
    "Profile": "Profil",
    "Age": "Alter",
    "Timezone (e.g., %@)": "Zeitzone (z.B. %@)",
    "LOADING!": "LADEN!",
    "Log In": "Anmelden",
    "Create Account": "Konto erstellen",
    "Need an account?": "Noch kein Konto?",
    "Have an account?": "Bereits ein Konto?",
    "Sign Up": "Registrieren",

    // MARK: - Content / Main
    "No dreams match your search": "Keine Tr\u{00E4}ume entsprechen deiner Suche",
    "Dreams": "Tr\u{00E4}ume",
    "Search dreams...": "Tr\u{00E4}ume suchen...",
    "Welcome, Dreamer!": "Willkommen, Tr\u{00E4}umer!",
    "DREAM ON!": "TR\u{00C4}UM WEITER!",
    "Record your first dream to begin your comic journey!": "Nimm deinen ersten Traum auf, um deine Comic-Reise zu beginnen!",
    "Capture a Dream": "Einen Traum festhalten",
    "DELETE": "L\u{00D6}SCHEN",

    // MARK: - New Dream
    "What did you dream?": "Was hast du getr\u{00E4}umt?",
    "Describe your dream or nightmare...": "Beschreibe deinen Traum oder Albtraum...",
    "Stop Recording": "Aufnahme stoppen",
    "Record Dream": "Traum aufnehmen",
    "Tap to stop voice recording": "Tippen, um die Sprachaufnahme zu stoppen",
    "Tap to start describing your dream with your voice": "Tippen, um deinen Traum mit deiner Stimme zu beschreiben",
    "Listening...": "H\u{00F6}re zu...",
    "When did you see this dream?": "Wann hast du diesen Traum gehabt?",
    "Save Dream": "Traum speichern",
    "New Dream": "Neuer Traum",

    // MARK: - Common Actions
    "Cancel": "Abbrechen",
    "Save": "Speichern",
    "Edit": "Bearbeiten",
    "Delete": "L\u{00F6}schen",
    "Done": "Fertig",
    "Try Again": "Erneut versuchen",
    "Retry": "Wiederholen",
    "Add": "Hinzuf\u{00FC}gen",
    "View": "Ansehen",

    // MARK: - Dream Detail
    "Dream date": "Traumdatum",
    "Original Dream": "Urspr\u{00FC}nglicher Traum",
    "Dream Analysis": "Traumanalyse",
    "ANALYZING!": "ANALYSIERE!",
    "Rewritten Dream (%@)": "Umgeschriebener Traum (%@)",
    "Stop": "Stopp",
    "Play Story": "Geschichte abspielen",
    "Tap to stop reading the story": "Tippen, um das Vorlesen zu stoppen",
    "Tap to hear the story read aloud": "Tippen, um die Geschichte laut vorlesen zu lassen",
    "Try a Different Tone?": "Einen anderen Ton ausprobieren?",
    "How Should This Dream Feel?": "Wie soll sich dieser Traum anf\u{00FC}hlen?",
    "Narrating!": "Erz\u{00E4}hle!",
    "Narrate Again": "Erneut erz\u{00E4}hlen",
    "Narrate": "Erz\u{00E4}hlen",
    "Delete Dream": "Traum l\u{00F6}schen",
    "Dream": "Traum",
    "Delete this dream?": "Diesen Traum l\u{00F6}schen?",
    "This will permanently remove this dream and all its content.": "Dies wird diesen Traum und alle zugeh\u{00F6}rigen Inhalte dauerhaft entfernen.",

    // MARK: - Tones
    "Happy": "Fr\u{00F6}hlich",
    "Funny": "Lustig",
    "Hopeful": "Hoffnungsvoll",
    "Calm": "Ruhig",
    "Positive": "Positiv",

    // MARK: - Dream Analysis
    "Time Period": "Zeitraum",
    "Period": "Zeitraum",
    "Emotion Trends": "Emotionstrends",
    "Loading trends...": "Trends werden geladen...",
    "Loading summary...": "Zusammenfassung wird geladen...",
    "Summary": "Zusammenfassung",
    "Most Common Feeling": "H\u{00E4}ufigstes Gef\u{00FC}hl",
    "Average intensity: %.0f%%": "Durchschnittliche Intensit\u{00E4}t: %.0f%%",
    "dreams": "Tr\u{00E4}ume",
    "Suggested Moods": "Vorgeschlagene Stimmungen",
    "Activity": "Aktivit\u{00E4}t",
    "Keep logging dreams to see trends": "Tr\u{00E4}ume weiter aufzeichnen, um Trends zu sehen",
    "Record your first dream to start tracking your emotions": "Nimm deinen ersten Traum auf, um deine Emotionen zu verfolgen",
    "ZAP!": "ZAP!",
    "OOPS!": "HOPPLA!",

    // MARK: - Settings
    "Signed in": "Angemeldet",
    "Cloud sync enabled": "Cloud-Synchronisierung aktiviert",
    "Sign In / Sign Up": "Anmelden / Registrieren",
    "Create an account to sync dreams and AI content.": "Erstelle ein Konto, um Tr\u{00E4}ume und KI-Inhalte zu synchronisieren.",
    "Notifications": "Benachrichtigungen",
    "Notification Settings": "Benachrichtigungseinstellungen",
    "Settings": "Einstellungen",
    "Dream Character": "Traumcharakter",
    "These details personalize your dream comics": "Diese Details personalisieren deine Traum-Comics",
    "Sign Out": "Abmelden",
    "Gender": "Geschlecht",
    "Male": "M\u{00E4}nnlich",
    "Female": "Weiblich",
    "Non-binary": "Nicht-bin\u{00E4}r",
    "Prefer not to say": "Keine Angabe",
    "Language": "Sprache",

    // MARK: - Dream Visualization
    "Dream Visualization": "Traumvisualisierung",
    "AI creates a comic page from your dream": "KI erstellt eine Comic-Seite aus deinem Traum",
    "Include my likeness": "Mein Aussehen einbeziehen",
    "OFFLINE!": "OFFLINE!",
    "Image generation requires Apple Silicon or sign-in.": "Bilderzeugung erfordert Apple Silicon oder eine Anmeldung.",
    "Draw my dream!": "Zeichne meinen Traum!",
    "Redraw my dream!": "Zeichne meinen Traum neu!",
    "Regenerate as Comic Page": "Als Comic-Seite neu erstellen",
    "CREATING!": "ERSTELLE!",
    "Painting your dream...": "Dein Traum wird gemalt...",
    "Add your details in Profile to appear in your dreams!": "F\u{00FC}ge deine Details im Profil hinzu, um in deinen Tr\u{00E4}umen zu erscheinen!",
    "Scene %d": "Szene %d",
    "Save your dreams!": "Speichere deine Tr\u{00E4}ume!",
    "Sign up to sync rewrites and comics across devices.": "Registriere dich, um Umschreibungen und Comics ger\u{00E4}te\u{00FC}bergreifend zu synchronisieren.",
    "Dream Sequence": "Traumsequenz",
    "Dream Comic Page": "Traum-Comic-Seite",

    // MARK: - Notifications
    "Notifications Enabled": "Benachrichtigungen aktiviert",
    "Enable Notifications": "Benachrichtigungen aktivieren",
    "Permission": "Berechtigung",
    "Allow notifications to receive reminders and follow-ups.": "Erlaube Benachrichtigungen, um Erinnerungen und Nachfragen zu erhalten.",
    "Notification Types": "Benachrichtigungstypen",
    "Configure each notification type independently with its own schedule.": "Konfiguriere jeden Benachrichtigungstyp unabh\u{00E4}ngig mit eigenem Zeitplan.",
    "Permission Required": "Berechtigung erforderlich",
    "Open Settings": "Einstellungen \u{00F6}ffnen",
    "Please enable notifications in Settings to receive reminders.": "Bitte aktiviere Benachrichtigungen in den Einstellungen, um Erinnerungen zu erhalten.",
    "When to Notify": "Wann benachrichtigen",
    "Time of Day": "Tageszeit",
    "Day of Week": "Wochentag",
    "Select Days": "Tage ausw\u{00E4}hlen",
    "Preview": "Vorschau",
    "Frequency": "H\u{00E4}ufigkeit",
    "Time": "Uhrzeit",
    "Day": "Tag",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Du erh\u{00E4}ltst t\u{00E4}glich eine Benachrichtigung um %@.",
    "You'll receive notifications Monday through Friday at %@.": "Du erh\u{00E4}ltst Benachrichtigungen von Montag bis Freitag um %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Du erh\u{00E4}ltst Benachrichtigungen am Samstag und Sonntag um %@.",
    "You'll receive a notification every %@ at %@.": "Du erh\u{00E4}ltst jeden %@ eine Benachrichtigung um %@.",
    "Select at least one day to receive notifications.": "W\u{00E4}hle mindestens einen Tag aus, um Benachrichtigungen zu erhalten.",
    "You'll receive notifications on %@ at %@.": "Du erh\u{00E4}ltst Benachrichtigungen am %@ um %@.",

    // MARK: - Dream Reminders
    "Reminders": "Erinnerungen",
    "No reminders set": "Keine Erinnerungen gesetzt",
    "Add a reminder to revisit this dream": "F\u{00FC}ge eine Erinnerung hinzu, um diesen Traum erneut zu besuchen",
    "EXPIRED": "ABGELAUFEN",
    "REMINDER TYPE": "ERINNERUNGSTYP",
    "WHEN": "WANN",
    "PREVIEW": "VORSCHAU",
    "Custom": "Benutzerdefiniert",
    "Add Reminder": "Erinnerung hinzuf\u{00FC}gen",
    "Date & Time": "Datum & Uhrzeit",
    "1 hour": "1 Stunde",
    "6 hours": "6 Stunden",
    "Tomorrow": "Morgen",
    "2 days": "2 Tage",
    "1 week": "1 Woche",
    "You'll receive a \"%@\" reminder on %@": "Du erh\u{00E4}ltst eine \"%@\"-Erinnerung am %@",

    // MARK: - Avatar
    "Use This Photo": "Dieses Foto verwenden",
    "Use Memoji": "Memoji verwenden",
    "Choose Photo": "Foto ausw\u{00E4}hlen",
    "Take Photo": "Foto aufnehmen",
    "Remove Avatar": "Avatar entfernen",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Dein Foto erstellt eine Textbeschreibung deines Aussehens. Das Foto selbst wird nicht mit KI-Diensten geteilt.",
    "Profile Picture": "Profilbild",
    "Paste Your Memoji": "Dein Memoji einf\u{00FC}gen",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Tippe auf das Textfeld unten\n2. Wechsle zur Memoji-Tastatur\n3. Tippe auf deinen Lieblings-Memoji-Sticker",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Hier tippen, dann Memoji einf\u{00FC}gen...",
    "Uploading...": "Wird hochgeladen...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Wir empfehlen, dies umzuschreiben als einen ",
    " dream": " Traum",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Angst",
    "Sadness": "Traurigkeit",
    "Anger": "Wut",
    "Anxiety": "Ängstlichkeit",
    "Stress": "Stress",
    "Loneliness": "Einsamkeit",
    "Helplessness": "Hilflosigkeit",
    "Shame": "Scham",
    "Grief": "Trauer",
    "Confusion": "Verwirrung",
    "Joy": "Freude",
    "Love": "Liebe",
    "Surprise": "Überraschung",
    "Disgust": "Ekel",
    "Trust": "Vertrauen",
    "Anticipation": "Erwartung",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Friedlich",
    "Serene": "Gelassen",
    "Humorous": "Humorvoll",
    "Lighthearted": "Unbeschwert",
    "Empowering": "Stärkend",
    "Confident": "Selbstbewusst",
    "Optimistic": "Optimistisch",
    "Inspiring": "Inspirierend",
    "Joyful": "Freudig",
    "Cheerful": "Fröhlich",
    "Neutral": "Neutral",

    // MARK: - Trend Directions
    "Improving": "Verbessernd",
    "Worsening": "Verschlechternd",
    "Stable": "Stabil",

    // MARK: - Analysis Periods
    "7 Days": "7 Tage",
    "30 Days": "30 Tage",
    "90 Days": "90 Tage",
    "All": "Alle",

    // MARK: - Notification Categories
    "Daily Check-in": "T\u{00E4}glicher Check-in",
    "Dream Reflection": "Traumreflexion",
    "Nightmare Follow-up": "Albtraum-Nachsorge",
    "Weekly Digest": "W\u{00F6}chentliche \u{00DC}bersicht",
    "Gentle reminder to log your dreams": "Sanfte Erinnerung, deine Tr\u{00E4}ume aufzuzeichnen",
    "Reflect on dreams you've recorded": "Reflektiere \u{00FC}ber deine aufgezeichneten Tr\u{00E4}ume",
    "Check in after rewriting a nightmare": "Nachfrage nach dem Umschreiben eines Albtraums",
    "Weekly summary of your dream journey": "W\u{00F6}chentliche Zusammenfassung deiner Traumreise",

    // MARK: - Notification Frequencies
    "Every Day": "Jeden Tag",
    "Weekdays Only": "Nur Werktage",
    "Weekends Only": "Nur Wochenenden",
    "Once a Week": "Einmal pro Woche",
    "Custom Days": "Benutzerdefinierte Tage",

    // MARK: - Day Names
    "Sun": "So",
    "Mon": "Mo",
    "Tue": "Di",
    "Wed": "Mi",
    "Thu": "Do",
    "Fri": "Fr",
    "Sat": "Sa",

    // MARK: - Notification Templates
    "Good morning!": "Guten Morgen!",
    "Dream Journal Time": "Traumtagebuch-Zeit",
    "Remember Your Dreams?": "Erinnerst du dich an deine Tr\u{00E4}ume?",
    "Start Your Day Mindfully": "Starte deinen Tag achtsam",
    "Did you dream last night? Take a moment to record it.": "Hast du letzte Nacht getr\u{00E4}umt? Nimm dir einen Moment, um es aufzuzeichnen.",
    "Your dreams are waiting to be captured.": "Deine Tr\u{00E4}ume warten darauf, festgehalten zu werden.",
    "A few minutes to log your dreams can make a big difference.": "Ein paar Minuten zum Aufzeichnen deiner Tr\u{00E4}ume k\u{00F6}nnen einen gro\u{00DF}en Unterschied machen.",
    "Dreams fade quickly - save yours now.": "Tr\u{00E4}ume verblassen schnell \u{2013} speichere deine jetzt.",
    "Time to Reflect": "Zeit zum Reflektieren",
    "Dream Insight": "Traum-Einblick",
    "Look Back": "R\u{00FC}ckblick",
    "Your Dream Journey": "Deine Traumreise",
    "Revisit a dream you recorded and see how it makes you feel now.": "Besuche einen aufgezeichneten Traum erneut und sieh, wie er dich jetzt f\u{00FC}hlen l\u{00E4}sst.",
    "Your past dreams might hold insights for today.": "Deine vergangenen Tr\u{00E4}ume k\u{00F6}nnten Erkenntnisse f\u{00FC}r heute enthalten.",
    "Take a moment to reflect on your dream patterns.": "Nimm dir einen Moment, um \u{00FC}ber deine Traummuster nachzudenken.",
    "What have your dreams been telling you lately?": "Was haben dir deine Tr\u{00E4}ume in letzter Zeit erz\u{00E4}hlt?",
    "How Are You Feeling?": "Wie f\u{00FC}hlst du dich?",
    "Gentle Check-in": "Sanfte Nachfrage",
    "You're Doing Great": "Du machst das gro\u{00DF}artig",
    "Healing Journey": "Heilungsreise",
    "How did the rewritten dream make you feel? Consider reading it again.": "Wie hat dich der umgeschriebene Traum f\u{00FC}hlen lassen? Lies ihn gerne nochmal.",
    "Remember, you have the power to reshape your dreams.": "Denke daran, du hast die Kraft, deine Tr\u{00E4}ume umzugestalten.",
    "Take a moment to revisit your peaceful dream version.": "Nimm dir einen Moment, um deine friedliche Traumversion erneut zu lesen.",
    "Your healing journey continues. We're here for you.": "Deine Heilungsreise geht weiter. Wir sind f\u{00FC}r dich da.",
    "Your Week in Dreams": "Deine Woche in Tr\u{00E4}umen",
    "Weekly Reflection": "W\u{00F6}chentliche Reflexion",
    "Dream Summary": "Traum-Zusammenfassung",
    "This Week's Journey": "Die Reise dieser Woche",
    "See how your dream patterns evolved this week.": "Sieh, wie sich deine Traummuster diese Woche entwickelt haben.",
    "Time for your weekly dream check-in.": "Zeit f\u{00FC}r deinen w\u{00F6}chentlichen Traum-Check-in.",
    "Reflect on your dream journey this week.": "Reflektiere \u{00FC}ber deine Traumreise diese Woche.",
    "A week of dreams - what stories did they tell?": "Eine Woche voller Tr\u{00E4}ume \u{2013} welche Geschichten haben sie erz\u{00E4}hlt?",
]
