// Arabic (ar)

let strings_ar: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "تسجيل الدخول!",
    "SIGN UP!": "إنشاء حساب!",
    "Account": "الحساب",
    "Email": "البريد الإلكتروني",
    "Password": "كلمة المرور",
    "Profile": "الملف الشخصي",
    "Age": "العمر",
    "Timezone (e.g., %@)": "المنطقة الزمنية (مثال: %@)",
    "LOADING!": "جارٍ التحميل!",
    "Log In": "تسجيل الدخول",
    "Create Account": "إنشاء حساب",
    "Need an account?": "تحتاج إلى حساب؟",
    "Have an account?": "لديك حساب بالفعل؟",
    "Sign Up": "إنشاء حساب",

    // MARK: - Content / Main
    "No dreams match your search": "لا توجد أحلام تطابق بحثك",
    "Dreams": "الأحلام",
    "Search dreams...": "البحث في الأحلام...",
    "Welcome, Dreamer!": "مرحباً أيها الحالم!",
    "DREAM ON!": "واصل الحلم!",
    "Record your first dream to begin your comic journey!": "سجّل حلمك الأول لبدء رحلتك في عالم القصص المصورة!",
    "Capture a Dream": "التقاط حلم",
    "DELETE": "حذف",

    // MARK: - New Dream
    "What did you dream?": "ماذا حلمت؟",
    "Describe your dream or nightmare...": "صِف حلمك أو كابوسك...",
    "Stop Recording": "إيقاف التسجيل",
    "Record Dream": "تسجيل الحلم",
    "Tap to stop voice recording": "اضغط لإيقاف التسجيل الصوتي",
    "Tap to start describing your dream with your voice": "اضغط لبدء وصف حلمك بصوتك",
    "Listening...": "جارٍ الاستماع...",
    "When did you see this dream?": "متى رأيت هذا الحلم؟",
    "Save Dream": "حفظ الحلم",
    "New Dream": "حلم جديد",

    // MARK: - Common Actions
    "Cancel": "إلغاء",
    "Save": "حفظ",
    "Edit": "تعديل",
    "Delete": "حذف",
    "Done": "تم",
    "Try Again": "حاول مرة أخرى",
    "Retry": "إعادة المحاولة",
    "Add": "إضافة",
    "View": "عرض",

    // MARK: - Dream Detail
    "Dream date": "تاريخ الحلم",
    "Original Dream": "الحلم الأصلي",
    "Dream Analysis": "تحليل الحلم",
    "ANALYZING!": "جارٍ التحليل!",
    "Rewritten Dream (%@)": "الحلم المُعاد كتابته (%@)",
    "Stop": "إيقاف",
    "Play Story": "تشغيل القصة",
    "Tap to stop reading the story": "اضغط لإيقاف قراءة القصة",
    "Tap to hear the story read aloud": "اضغط لسماع القصة بصوت عالٍ",
    "Try a Different Tone?": "تريد تجربة نبرة مختلفة؟",
    "How Should This Dream Feel?": "كيف يجب أن يكون شعور هذا الحلم؟",
    "Narrating!": "جارٍ السرد!",
    "Narrate Again": "إعادة السرد",
    "Narrate": "سرد",
    "Delete Dream": "حذف الحلم",
    "Dream": "حلم",
    "Delete this dream?": "هل تريد حذف هذا الحلم؟",
    "This will permanently remove this dream and all its content.": "سيؤدي هذا إلى حذف هذا الحلم وجميع محتوياته نهائياً.",

    // MARK: - Tones
    "Happy": "سعيد",
    "Funny": "مضحك",
    "Hopeful": "مفعم بالأمل",
    "Calm": "هادئ",
    "Positive": "إيجابي",

    // MARK: - Dream Analysis
    "Time Period": "الفترة الزمنية",
    "Period": "الفترة",
    "Emotion Trends": "اتجاهات المشاعر",
    "Loading trends...": "جارٍ تحميل الاتجاهات...",
    "Loading summary...": "جارٍ تحميل الملخص...",
    "Summary": "الملخص",
    "Most Common Feeling": "الشعور الأكثر شيوعاً",
    "Average intensity: %.0f%%": "متوسط الشدة: %.0f%%",
    "dreams": "أحلام",
    "Suggested Moods": "الحالات المزاجية المقترحة",
    "Activity": "النشاط",
    "Keep logging dreams to see trends": "استمر في تسجيل الأحلام لرؤية الاتجاهات",
    "Record your first dream to start tracking your emotions": "سجّل حلمك الأول لبدء تتبع مشاعرك",
    "ZAP!": "زاب!",
    "OOPS!": "عذراً!",

    // MARK: - Settings
    "Signed in": "تم تسجيل الدخول",
    "Cloud sync enabled": "المزامنة السحابية مفعّلة",
    "Sign In / Sign Up": "تسجيل الدخول / إنشاء حساب",
    "Create an account to sync dreams and AI content.": "أنشئ حساباً لمزامنة الأحلام ومحتوى الذكاء الاصطناعي.",
    "Notifications": "الإشعارات",
    "Notification Settings": "إعدادات الإشعارات",
    "Settings": "الإعدادات",
    "Dream Character": "شخصية الحلم",
    "These details personalize your dream comics": "هذه التفاصيل تُخصّص قصصك المصورة عن الأحلام",
    "Sign Out": "تسجيل الخروج",
    "Gender": "الجنس",
    "Male": "ذكر",
    "Female": "أنثى",
    "Non-binary": "غير ثنائي",
    "Prefer not to say": "أفضّل عدم الإفصاح",
    "Language": "اللغة",

    // MARK: - Dream Visualization
    "Dream Visualization": "تصوير الحلم",
    "AI creates a comic page from your dream": "يُنشئ الذكاء الاصطناعي صفحة قصة مصورة من حلمك",
    "Include my likeness": "تضمين ملامحي",
    "OFFLINE!": "غير متصل!",
    "Image generation requires Apple Silicon or sign-in.": "يتطلب إنشاء الصور معالج Apple Silicon أو تسجيل الدخول.",
    "Draw my dream!": "ارسم حلمي!",
    "Redraw my dream!": "أعد رسم حلمي!",
    "Regenerate as Comic Page": "إعادة إنشاء كصفحة مصورة",
    "CREATING!": "جارٍ الإنشاء!",
    "Painting your dream...": "جارٍ رسم حلمك...",
    "Add your details in Profile to appear in your dreams!": "أضف تفاصيلك في الملف الشخصي لتظهر في أحلامك!",
    "Scene %d": "المشهد %d",
    "Save your dreams!": "احفظ أحلامك!",
    "Sign up to sync rewrites and comics across devices.": "أنشئ حساباً لمزامنة إعادة الكتابة والقصص المصورة عبر الأجهزة.",
    "Dream Sequence": "تسلسل الحلم",
    "Dream Comic Page": "صفحة الحلم المصورة",

    // MARK: - Notifications
    "Notifications Enabled": "الإشعارات مفعّلة",
    "Enable Notifications": "تفعيل الإشعارات",
    "Permission": "الإذن",
    "Allow notifications to receive reminders and follow-ups.": "اسمح بالإشعارات لتلقي التذكيرات والمتابعات.",
    "Notification Types": "أنواع الإشعارات",
    "Configure each notification type independently with its own schedule.": "قم بتهيئة كل نوع من الإشعارات بشكل مستقل بجدوله الخاص.",
    "Permission Required": "الإذن مطلوب",
    "Open Settings": "فتح الإعدادات",
    "Please enable notifications in Settings to receive reminders.": "يرجى تفعيل الإشعارات في الإعدادات لتلقي التذكيرات.",
    "When to Notify": "متى يتم الإشعار",
    "Time of Day": "وقت اليوم",
    "Day of Week": "يوم الأسبوع",
    "Select Days": "اختيار الأيام",
    "Preview": "معاينة",
    "Frequency": "التكرار",
    "Time": "الوقت",
    "Day": "اليوم",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "ستتلقى إشعاراً كل يوم في الساعة %@.",
    "You'll receive notifications Monday through Friday at %@.": "ستتلقى إشعارات من الاثنين إلى الجمعة في الساعة %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "ستتلقى إشعارات يومي السبت والأحد في الساعة %@.",
    "You'll receive a notification every %@ at %@.": "ستتلقى إشعاراً كل %@ في الساعة %@.",
    "Select at least one day to receive notifications.": "اختر يوماً واحداً على الأقل لتلقي الإشعارات.",
    "You'll receive notifications on %@ at %@.": "ستتلقى إشعارات يوم %@ في الساعة %@.",

    // MARK: - Dream Reminders
    "Reminders": "التذكيرات",
    "No reminders set": "لا توجد تذكيرات",
    "Add a reminder to revisit this dream": "أضف تذكيراً لإعادة زيارة هذا الحلم",
    "EXPIRED": "منتهي الصلاحية",
    "REMINDER TYPE": "نوع التذكير",
    "WHEN": "متى",
    "PREVIEW": "معاينة",
    "Custom": "مخصص",
    "Add Reminder": "إضافة تذكير",
    "Date & Time": "التاريخ والوقت",
    "1 hour": "ساعة واحدة",
    "6 hours": "٦ ساعات",
    "Tomorrow": "غداً",
    "2 days": "يومان",
    "1 week": "أسبوع واحد",
    "You'll receive a \"%@\" reminder on %@": "ستتلقى تذكير \"%@\" في %@",

    // MARK: - Avatar
    "Use This Photo": "استخدام هذه الصورة",
    "Use Memoji": "استخدام Memoji",
    "Choose Photo": "اختيار صورة",
    "Take Photo": "التقاط صورة",
    "Remove Avatar": "إزالة الصورة الرمزية",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "تُنشئ صورتك وصفاً نصياً لمظهرك. لا تتم مشاركة الصورة نفسها مع خدمات الذكاء الاصطناعي.",
    "Profile Picture": "صورة الملف الشخصي",
    "Paste Your Memoji": "الصق Memoji الخاص بك",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. اضغط على حقل النص أدناه\n2. انتقل إلى لوحة مفاتيح Memoji\n3. اضغط على ملصق Memoji المفضل لديك",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "اضغط هنا، ثم الصق Memoji...",
    "Uploading...": "جارٍ الرفع...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "نقترح إعادة كتابة هذا كحلم ",
    " dream": "",

    // MARK: - Emotions (from backend analysis)
    "Fear": "خوف",
    "Sadness": "حزن",
    "Anger": "غضب",
    "Anxiety": "قلق",
    "Stress": "توتر",
    "Loneliness": "وحدة",
    "Helplessness": "عجز",
    "Shame": "خجل",
    "Grief": "حداد",
    "Confusion": "ارتباك",
    "Joy": "فرح",
    "Love": "حب",
    "Surprise": "مفاجأة",
    "Disgust": "اشمئزاز",
    "Trust": "ثقة",
    "Anticipation": "ترقب",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "هادئ",
    "Serene": "صافٍ",
    "Humorous": "فكاهي",
    "Lighthearted": "مرح",
    "Empowering": "تمكيني",
    "Confident": "واثق",
    "Optimistic": "متفائل",
    "Inspiring": "مُلهم",
    "Joyful": "بهيج",
    "Cheerful": "مبتهج",
    "Neutral": "محايد",

    // MARK: - Trend Directions
    "Improving": "يتحسن",
    "Worsening": "يتدهور",
    "Stable": "مستقر",

    // MARK: - Analysis Periods
    "7 Days": "٧ أيام",
    "30 Days": "٣٠ يوماً",
    "90 Days": "٩٠ يوماً",
    "All": "الكل",

    // MARK: - Notification Categories
    "Daily Check-in": "التسجيل اليومي",
    "Dream Reflection": "التأمل في الأحلام",
    "Nightmare Follow-up": "متابعة الكوابيس",
    "Weekly Digest": "الملخص الأسبوعي",
    "Gentle reminder to log your dreams": "تذكير لطيف لتسجيل أحلامك",
    "Reflect on dreams you've recorded": "تأمل في الأحلام التي سجلتها",
    "Check in after rewriting a nightmare": "تحقق بعد إعادة كتابة كابوس",
    "Weekly summary of your dream journey": "ملخص أسبوعي لرحلتك في عالم الأحلام",

    // MARK: - Notification Frequencies
    "Every Day": "كل يوم",
    "Weekdays Only": "أيام العمل فقط",
    "Weekends Only": "عطلة نهاية الأسبوع فقط",
    "Once a Week": "مرة في الأسبوع",
    "Custom Days": "أيام مخصصة",

    // MARK: - Day Names
    "Sun": "أحد",
    "Mon": "اثن",
    "Tue": "ثلا",
    "Wed": "أرب",
    "Thu": "خمي",
    "Fri": "جمع",
    "Sat": "سبت",

    // MARK: - Notification Templates
    "Good morning!": "صباح الخير!",
    "Dream Journal Time": "وقت يوميات الأحلام",
    "Remember Your Dreams?": "هل تتذكر أحلامك؟",
    "Start Your Day Mindfully": "ابدأ يومك بوعي",
    "Did you dream last night? Take a moment to record it.": "هل حلمت الليلة الماضية؟ خذ لحظة لتسجيل حلمك.",
    "Your dreams are waiting to be captured.": "أحلامك بانتظار أن يتم التقاطها.",
    "A few minutes to log your dreams can make a big difference.": "بضع دقائق لتسجيل أحلامك يمكن أن تُحدث فرقاً كبيراً.",
    "Dreams fade quickly - save yours now.": "الأحلام تتلاشى بسرعة - احفظ أحلامك الآن.",
    "Time to Reflect": "وقت التأمل",
    "Dream Insight": "رؤية الحلم",
    "Look Back": "نظرة إلى الوراء",
    "Your Dream Journey": "رحلتك في عالم الأحلام",
    "Revisit a dream you recorded and see how it makes you feel now.": "أعد زيارة حلم سجلته وانظر كيف يُشعرك الآن.",
    "Your past dreams might hold insights for today.": "أحلامك السابقة قد تحمل رؤى لليوم.",
    "Take a moment to reflect on your dream patterns.": "خذ لحظة للتأمل في أنماط أحلامك.",
    "What have your dreams been telling you lately?": "ماذا كانت أحلامك تخبرك مؤخراً؟",
    "How Are You Feeling?": "كيف تشعر؟",
    "Gentle Check-in": "تحقق لطيف",
    "You're Doing Great": "أنت تبلي حسناً",
    "Healing Journey": "رحلة التعافي",
    "How did the rewritten dream make you feel? Consider reading it again.": "كيف أشعرك الحلم المُعاد كتابته؟ فكّر في قراءته مرة أخرى.",
    "Remember, you have the power to reshape your dreams.": "تذكّر، لديك القدرة على إعادة تشكيل أحلامك.",
    "Take a moment to revisit your peaceful dream version.": "خذ لحظة لإعادة زيارة نسختك الهادئة من الحلم.",
    "Your healing journey continues. We're here for you.": "رحلة تعافيك مستمرة. نحن هنا من أجلك.",
    "Your Week in Dreams": "أسبوعك في الأحلام",
    "Weekly Reflection": "التأمل الأسبوعي",
    "Dream Summary": "ملخص الأحلام",
    "This Week's Journey": "رحلة هذا الأسبوع",
    "See how your dream patterns evolved this week.": "شاهد كيف تطورت أنماط أحلامك هذا الأسبوع.",
    "Time for your weekly dream check-in.": "حان وقت مراجعتك الأسبوعية للأحلام.",
    "Reflect on your dream journey this week.": "تأمل في رحلتك في عالم الأحلام هذا الأسبوع.",
    "A week of dreams - what stories did they tell?": "أسبوع من الأحلام - أي قصص رَوَت؟",
]
