// English (en-US) — Source of truth for all localization keys

let strings_en: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "LOG IN!",
    "SIGN UP!": "SIGN UP!",
    "Account": "Account",
    "Email": "Email",
    "Password": "Password",
    "Profile": "Profile",
    "Age": "Age",
    "Timezone (e.g., %@)": "Timezone (e.g., %@)",
    "LOADING!": "LOADING!",
    "Log In": "Log In",
    "Create Account": "Create Account",
    "Need an account?": "Need an account?",
    "Have an account?": "Have an account?",
    "Sign Up": "Sign Up",

    // MARK: - Content / Main
    "No dreams match your search": "No dreams match your search",
    "Dreams": "Dreams",
    "Search dreams...": "Search dreams...",
    "Welcome, Dreamer!": "Welcome, Dreamer!",
    "DREAM ON!": "DREAM ON!",
    "Record your first dream to begin your comic journey!": "Record your first dream to begin your comic journey!",
    "Capture a Dream": "Capture a Dream",
    "DELETE": "DELETE",

    // MARK: - New Dream
    "What did you dream?": "What did you dream?",
    "Describe your dream or nightmare...": "Describe your dream or nightmare...",
    "Stop Recording": "Stop Recording",
    "Record Dream": "Record Dream",
    "Tap to stop voice recording": "Tap to stop voice recording",
    "Tap to start describing your dream with your voice": "Tap to start describing your dream with your voice",
    "Listening...": "Listening...",
    "When did you see this dream?": "When did you see this dream?",
    "Save Dream": "Save Dream",
    "New Dream": "New Dream",

    // MARK: - Common Actions
    "Cancel": "Cancel",
    "Save": "Save",
    "Edit": "Edit",
    "Delete": "Delete",
    "Done": "Done",
    "Try Again": "Try Again",
    "Retry": "Retry",
    "Add": "Add",
    "View": "View",

    // MARK: - Dream Detail
    "Dream date": "Dream date",
    "Original Dream": "Original Dream",
    "Dream Analysis": "Dream Analysis",
    "ANALYZING!": "ANALYZING!",
    "Rewritten Dream (%@)": "Rewritten Dream (%@)",
    "Stop": "Stop",
    "Play Story": "Play Story",
    "Tap to stop reading the story": "Tap to stop reading the story",
    "Tap to hear the story read aloud": "Tap to hear the story read aloud",
    "Try a Different Tone?": "Try a Different Tone?",
    "How Should This Dream Feel?": "How Should This Dream Feel?",
    "Narrating!": "Narrating!",
    "Narrate Again": "Narrate Again",
    "Narrate": "Narrate",
    "Delete Dream": "Delete Dream",
    "Dream": "Dream",
    "Delete this dream?": "Delete this dream?",
    "This will permanently remove this dream and all its content.": "This will permanently remove this dream and all its content.",

    // MARK: - Tones
    "Happy": "Happy",
    "Funny": "Funny",
    "Hopeful": "Hopeful",
    "Calm": "Calm",
    "Positive": "Positive",

    // MARK: - Dream Analysis
    "Time Period": "Time Period",
    "Period": "Period",
    "Emotion Trends": "Emotion Trends",
    "Loading trends...": "Loading trends...",
    "Loading summary...": "Loading summary...",
    "Summary": "Summary",
    "Most Common Feeling": "Most Common Feeling",
    "Average intensity: %.0f%%": "Average intensity: %.0f%%",
    "dreams": "dreams",
    "Suggested Moods": "Suggested Moods",
    "Activity": "Activity",
    "Keep logging dreams to see trends": "Keep logging dreams to see trends",
    "Record your first dream to start tracking your emotions": "Record your first dream to start tracking your emotions",
    "ZAP!": "ZAP!",
    "OOPS!": "OOPS!",

    // MARK: - Settings
    "Signed in": "Signed in",
    "Cloud sync enabled": "Cloud sync enabled",
    "Sign In / Sign Up": "Sign In / Sign Up",
    "Create an account to sync dreams and AI content.": "Create an account to sync dreams and AI content.",
    "Notifications": "Notifications",
    "Notification Settings": "Notification Settings",
    "Settings": "Settings",
    "Dream Character": "Dream Character",
    "These details personalize your dream comics": "These details personalize your dream comics",
    "Sign Out": "Sign Out",
    "Gender": "Gender",
    "Male": "Male",
    "Female": "Female",
    "Non-binary": "Non-binary",
    "Prefer not to say": "Prefer not to say",
    "Language": "Language",

    // MARK: - Dream Visualization
    "Dream Visualization": "Dream Visualization",
    "AI creates a comic page from your dream": "AI creates a comic page from your dream",
    "Include my likeness": "Include my likeness",
    "OFFLINE!": "OFFLINE!",
    "Image generation requires Apple Silicon or sign-in.": "Image generation requires Apple Silicon or sign-in.",
    "Draw my dream!": "Draw my dream!",
    "Redraw my dream!": "Redraw my dream!",
    "Regenerate as Comic Page": "Regenerate as Comic Page",
    "CREATING!": "CREATING!",
    "Painting your dream...": "Painting your dream...",
    "Add your details in Profile to appear in your dreams!": "Add your details in Profile to appear in your dreams!",
    "Scene %d": "Scene %d",
    "Save your dreams!": "Save your dreams!",
    "Sign up to sync rewrites and comics across devices.": "Sign up to sync rewrites and comics across devices.",
    "Dream Sequence": "Dream Sequence",
    "Dream Comic Page": "Dream Comic Page",

    // MARK: - Notifications
    "Notifications Enabled": "Notifications Enabled",
    "Enable Notifications": "Enable Notifications",
    "Permission": "Permission",
    "Allow notifications to receive reminders and follow-ups.": "Allow notifications to receive reminders and follow-ups.",
    "Notification Types": "Notification Types",
    "Configure each notification type independently with its own schedule.": "Configure each notification type independently with its own schedule.",
    "Permission Required": "Permission Required",
    "Open Settings": "Open Settings",
    "Please enable notifications in Settings to receive reminders.": "Please enable notifications in Settings to receive reminders.",
    "When to Notify": "When to Notify",
    "Time of Day": "Time of Day",
    "Day of Week": "Day of Week",
    "Select Days": "Select Days",
    "Preview": "Preview",
    "Frequency": "Frequency",
    "Time": "Time",
    "Day": "Day",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "You'll receive a notification every day at %@.",
    "You'll receive notifications Monday through Friday at %@.": "You'll receive notifications Monday through Friday at %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "You'll receive notifications on Saturday and Sunday at %@.",
    "You'll receive a notification every %@ at %@.": "You'll receive a notification every %@ at %@.",
    "Select at least one day to receive notifications.": "Select at least one day to receive notifications.",
    "You'll receive notifications on %@ at %@.": "You'll receive notifications on %@ at %@.",

    // MARK: - Dream Reminders
    "Reminders": "Reminders",
    "No reminders set": "No reminders set",
    "Add a reminder to revisit this dream": "Add a reminder to revisit this dream",
    "EXPIRED": "EXPIRED",
    "REMINDER TYPE": "REMINDER TYPE",
    "WHEN": "WHEN",
    "PREVIEW": "PREVIEW",
    "Custom": "Custom",
    "Add Reminder": "Add Reminder",
    "Date & Time": "Date & Time",
    "1 hour": "1 hour",
    "6 hours": "6 hours",
    "Tomorrow": "Tomorrow",
    "2 days": "2 days",
    "1 week": "1 week",
    "You'll receive a \"%@\" reminder on %@": "You'll receive a \"%@\" reminder on %@",

    // MARK: - Avatar
    "Use This Photo": "Use This Photo",
    "Use Memoji": "Use Memoji",
    "Choose Photo": "Choose Photo",
    "Take Photo": "Take Photo",
    "Remove Avatar": "Remove Avatar",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.",
    "Profile Picture": "Profile Picture",
    "Paste Your Memoji": "Paste Your Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Tap here, then paste Memoji...",
    "Uploading...": "Uploading...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "We suggest rewriting this as a ",
    " dream": " dream",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Fear",
    "Sadness": "Sadness",
    "Anger": "Anger",
    "Anxiety": "Anxiety",
    "Stress": "Stress",
    "Loneliness": "Loneliness",
    "Helplessness": "Helplessness",
    "Shame": "Shame",
    "Grief": "Grief",
    "Confusion": "Confusion",
    "Joy": "Joy",
    "Love": "Love",
    "Surprise": "Surprise",
    "Disgust": "Disgust",
    "Trust": "Trust",
    "Anticipation": "Anticipation",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Peaceful",
    "Serene": "Serene",
    "Humorous": "Humorous",
    "Lighthearted": "Lighthearted",
    "Empowering": "Empowering",
    "Confident": "Confident",
    "Optimistic": "Optimistic",
    "Inspiring": "Inspiring",
    "Joyful": "Joyful",
    "Cheerful": "Cheerful",
    "Neutral": "Neutral",

    // MARK: - Trend Directions
    "Improving": "Improving",
    "Worsening": "Worsening",
    "Stable": "Stable",

    // MARK: - Analysis Periods
    "7 Days": "7 Days",
    "30 Days": "30 Days",
    "90 Days": "90 Days",
    "All": "All",

    // MARK: - Notification Categories
    "Daily Check-in": "Daily Check-in",
    "Dream Reflection": "Dream Reflection",
    "Nightmare Follow-up": "Nightmare Follow-up",
    "Weekly Digest": "Weekly Digest",
    "Gentle reminder to log your dreams": "Gentle reminder to log your dreams",
    "Reflect on dreams you've recorded": "Reflect on dreams you've recorded",
    "Check in after rewriting a nightmare": "Check in after rewriting a nightmare",
    "Weekly summary of your dream journey": "Weekly summary of your dream journey",

    // MARK: - Notification Frequencies
    "Every Day": "Every Day",
    "Weekdays Only": "Weekdays Only",
    "Weekends Only": "Weekends Only",
    "Once a Week": "Once a Week",
    "Custom Days": "Custom Days",

    // MARK: - Day Names
    "Sun": "Sun",
    "Mon": "Mon",
    "Tue": "Tue",
    "Wed": "Wed",
    "Thu": "Thu",
    "Fri": "Fri",
    "Sat": "Sat",

    // MARK: - Notification Templates
    "Good morning!": "Good morning!",
    "Dream Journal Time": "Dream Journal Time",
    "Remember Your Dreams?": "Remember Your Dreams?",
    "Start Your Day Mindfully": "Start Your Day Mindfully",
    "Did you dream last night? Take a moment to record it.": "Did you dream last night? Take a moment to record it.",
    "Your dreams are waiting to be captured.": "Your dreams are waiting to be captured.",
    "A few minutes to log your dreams can make a big difference.": "A few minutes to log your dreams can make a big difference.",
    "Dreams fade quickly - save yours now.": "Dreams fade quickly - save yours now.",
    "Time to Reflect": "Time to Reflect",
    "Dream Insight": "Dream Insight",
    "Look Back": "Look Back",
    "Your Dream Journey": "Your Dream Journey",
    "Revisit a dream you recorded and see how it makes you feel now.": "Revisit a dream you recorded and see how it makes you feel now.",
    "Your past dreams might hold insights for today.": "Your past dreams might hold insights for today.",
    "Take a moment to reflect on your dream patterns.": "Take a moment to reflect on your dream patterns.",
    "What have your dreams been telling you lately?": "What have your dreams been telling you lately?",
    "How Are You Feeling?": "How Are You Feeling?",
    "Gentle Check-in": "Gentle Check-in",
    "You're Doing Great": "You're Doing Great",
    "Healing Journey": "Healing Journey",
    "How did the rewritten dream make you feel? Consider reading it again.": "How did the rewritten dream make you feel? Consider reading it again.",
    "Remember, you have the power to reshape your dreams.": "Remember, you have the power to reshape your dreams.",
    "Take a moment to revisit your peaceful dream version.": "Take a moment to revisit your peaceful dream version.",
    "Your healing journey continues. We're here for you.": "Your healing journey continues. We're here for you.",
    "Your Week in Dreams": "Your Week in Dreams",
    "Weekly Reflection": "Weekly Reflection",
    "Dream Summary": "Dream Summary",
    "This Week's Journey": "This Week's Journey",
    "See how your dream patterns evolved this week.": "See how your dream patterns evolved this week.",
    "Time for your weekly dream check-in.": "Time for your weekly dream check-in.",
    "Reflect on your dream journey this week.": "Reflect on your dream journey this week.",
    "A week of dreams - what stories did they tell?": "A week of dreams - what stories did they tell?",
]
