// Ukrainian (uk)

let strings_uk: [String: String] = [
    // MARK: - Auth
    "LOG IN!": "УВІЙТИ!",
    "SIGN UP!": "ЗАРЕЄСТРУВАТИСЯ!",
    "Account": "Акаунт",
    "Email": "Електронна пошта",
    "Password": "Пароль",
    "Profile": "Профіль",
    "Age": "Вік",
    "Timezone (e.g., %@)": "Часовий пояс (напр., %@)",
    "LOADING!": "ЗАВАНТАЖЕННЯ!",
    "Log In": "Увійти",
    "Create Account": "Створити акаунт",
    "Need an account?": "Потрібен акаунт?",
    "Have an account?": "Вже є акаунт?",
    "Sign Up": "Зареєструватися",

    // MARK: - Content / Main
    "No dreams match your search": "Жодні сни не відповідають вашому пошуку",
    "Dreams": "Сни",
    "Search dreams...": "Шукати сни...",
    "Welcome, Dreamer!": "Ласкаво просимо, Мрійнику!",
    "DREAM ON!": "МРІЙ ДАЛІ!",
    "Record your first dream to begin your comic journey!": "Запишіть свій перший сон, щоб розпочати кomiксову подорож!",
    "Capture a Dream": "Записати сон",
    "DELETE": "ВИДАЛИТИ",

    // MARK: - New Dream
    "What did you dream?": "Що вам снилося?",
    "Describe your dream or nightmare...": "Опишіть свій сон або кошмар...",
    "Stop Recording": "Зупинити запис",
    "Record Dream": "Записати сон",
    "Tap to stop voice recording": "Торкніться, щоб зупинити голосовий запис",
    "Tap to start describing your dream with your voice": "Торкніться, щоб почати описувати сон голосом",
    "Listening...": "Слухаю...",
    "When did you see this dream?": "Коли вам наснився цей сон?",
    "Save Dream": "Зберегти сон",
    "New Dream": "Новий сон",

    // MARK: - Common Actions
    "Cancel": "Скасувати",
    "Save": "Зберегти",
    "Edit": "Редагувати",
    "Delete": "Видалити",
    "Done": "Готово",
    "Try Again": "Спробувати ще раз",
    "Retry": "Повторити",
    "Add": "Додати",
    "View": "Переглянути",

    // MARK: - Dream Detail
    "Dream date": "Дата сну",
    "Original Dream": "Оригінальний сон",
    "Dream Analysis": "Аналіз сну",
    "ANALYZING!": "АНАЛІЗУЮ!",
    "Rewritten Dream (%@)": "Переписаний сон (%@)",
    "Stop": "Зупинити",
    "Play Story": "Відтворити історію",
    "Tap to stop reading the story": "Торкніться, щоб зупинити читання історії",
    "Tap to hear the story read aloud": "Торкніться, щоб прослухати історію вголос",
    "Try a Different Tone?": "Спробувати інший тон?",
    "How Should This Dream Feel?": "Яким має бути настрій цього сну?",
    "Narrating!": "Озвучую!",
    "Narrate Again": "Озвучити знову",
    "Narrate": "Озвучити",
    "Delete Dream": "Видалити сон",
    "Dream": "Сон",
    "Delete this dream?": "Видалити цей сон?",
    "This will permanently remove this dream and all its content.": "Це назавжди видалить цей сон і весь його вміст.",

    // MARK: - Tones
    "Happy": "Радісний",
    "Funny": "Смішний",
    "Hopeful": "Сповнений надії",
    "Calm": "Спокійний",
    "Positive": "Позитивний",

    // MARK: - Dream Analysis
    "Time Period": "Часовий період",
    "Period": "Період",
    "Emotion Trends": "Тренди емоцій",
    "Loading trends...": "Завантаження трендів...",
    "Loading summary...": "Завантаження підсумку...",
    "Summary": "Підсумок",
    "Most Common Feeling": "Найпоширеніше почуття",
    "Average intensity: %.0f%%": "Середня інтенсивність: %.0f%%",
    "dreams": "сни",
    "Suggested Moods": "Запропоновані настрої",
    "Activity": "Активність",
    "Keep logging dreams to see trends": "Продовжуйте записувати сни, щоб бачити тренди",
    "Record your first dream to start tracking your emotions": "Запишіть свій перший сон, щоб почати відстежувати емоції",
    "ZAP!": "ЗАП!",
    "OOPS!": "ОТАКОЇ!",

    // MARK: - Settings
    "Signed in": "Увійшли",
    "Cloud sync enabled": "Хмарну синхронізацію увімкнено",
    "Sign In / Sign Up": "Увійти / Зареєструватися",
    "Create an account to sync dreams and AI content.": "Створіть акаунт для синхронізації снів і AI-контенту.",
    "Notifications": "Сповіщення",
    "Notification Settings": "Налаштування сповіщень",
    "Settings": "Налаштування",
    "Dream Character": "Персонаж сну",
    "These details personalize your dream comics": "Ці дані персоналізують ваші комікси зі снів",
    "Sign Out": "Вийти",
    "Gender": "Стать",
    "Male": "Чоловіча",
    "Female": "Жіноча",
    "Non-binary": "Небінарна",
    "Prefer not to say": "Не бажаю вказувати",
    "Language": "Мова",

    // MARK: - Dream Visualization
    "Dream Visualization": "Візуалізація сну",
    "AI creates a comic page from your dream": "AI створює сторінку коміксу з вашого сну",
    "Include my likeness": "Включити мою зовнішність",
    "OFFLINE!": "ОФЛАЙН!",
    "Image generation requires Apple Silicon or sign-in.": "Генерація зображень потребує Apple Silicon або входу в акаунт.",
    "Draw my dream!": "Намалюй мій сон!",
    "Redraw my dream!": "Перемалюй мій сон!",
    "Regenerate as Comic Page": "Перегенерувати як сторінку коміксу",
    "CREATING!": "СТВОРЮЮ!",
    "Painting your dream...": "Малюю ваш сон...",
    "Add your details in Profile to appear in your dreams!": "Додайте свої дані в профілі, щоб з'являтися у своїх снах!",
    "Scene %d": "Сцена %d",
    "Save your dreams!": "Збережіть свої сни!",
    "Sign up to sync rewrites and comics across devices.": "Зареєструйтесь для синхронізації переписаних снів і коміксів між пристроями.",
    "Dream Sequence": "Послідовність сну",
    "Dream Comic Page": "Сторінка коміксу сну",

    // MARK: - Notifications
    "Notifications Enabled": "Сповіщення увімкнено",
    "Enable Notifications": "Увімкнути сповіщення",
    "Permission": "Дозвіл",
    "Allow notifications to receive reminders and follow-ups.": "Дозвольте сповіщення для отримання нагадувань та подальших повідомлень.",
    "Notification Types": "Типи сповіщень",
    "Configure each notification type independently with its own schedule.": "Налаштуйте кожен тип сповіщення окремо з власним розкладом.",
    "Permission Required": "Потрібен дозвіл",
    "Open Settings": "Відкрити налаштування",
    "Please enable notifications in Settings to receive reminders.": "Увімкніть сповіщення в налаштуваннях для отримання нагадувань.",
    "When to Notify": "Коли сповіщати",
    "Time of Day": "Час доби",
    "Day of Week": "День тижня",
    "Select Days": "Обрати дні",
    "Preview": "Попередній перегляд",
    "Frequency": "Частота",
    "Time": "Час",
    "Day": "День",

    // MARK: - Notification Preview Strings
    "You'll receive a notification every day at %@.": "Ви отримуватимете сповіщення щодня о %@.",
    "You'll receive notifications Monday through Friday at %@.": "Ви отримуватимете сповіщення з понеділка по п'ятницю о %@.",
    "You'll receive notifications on Saturday and Sunday at %@.": "Ви отримуватимете сповіщення в суботу та неділю о %@.",
    "You'll receive a notification every %@ at %@.": "Ви отримуватимете сповіщення щокожного %@ о %@.",
    "Select at least one day to receive notifications.": "Оберіть щонайменше один день для отримання сповіщень.",
    "You'll receive notifications on %@ at %@.": "Ви отримуватимете сповіщення у %@ о %@.",

    // MARK: - Dream Reminders
    "Reminders": "Нагадування",
    "No reminders set": "Нагадувань не встановлено",
    "Add a reminder to revisit this dream": "Додайте нагадування, щоб повернутися до цього сну",
    "EXPIRED": "ЗАКІНЧИЛОСЬ",
    "REMINDER TYPE": "ТИП НАГАДУВАННЯ",
    "WHEN": "КОЛИ",
    "PREVIEW": "ПЕРЕГЛЯД",
    "Custom": "Власний",
    "Add Reminder": "Додати нагадування",
    "Date & Time": "Дата і час",
    "1 hour": "1 година",
    "6 hours": "6 годин",
    "Tomorrow": "Завтра",
    "2 days": "2 дні",
    "1 week": "1 тиждень",
    "You'll receive a \"%@\" reminder on %@": "Ви отримаєте нагадування \"%@\" о %@",

    // MARK: - Avatar
    "Use This Photo": "Використати це фото",
    "Use Memoji": "Використати Memoji",
    "Choose Photo": "Обрати фото",
    "Take Photo": "Зробити фото",
    "Remove Avatar": "Видалити аватар",
    "Your photo creates a text description of your appearance. The photo itself is not shared with AI services.": "Ваше фото створює текстовий опис вашої зовнішності. Саме фото не передається AI-сервісам.",
    "Profile Picture": "Фото профілю",
    "Paste Your Memoji": "Вставте своє Memoji",
    "1. Tap the text field below\n2. Switch to the Memoji keyboard\n3. Tap your favorite Memoji sticker": "1. Торкніться текстового поля нижче\n2. Перемкніться на клавіатуру Memoji\n3. Торкніться улюбленого стікера Memoji",
    "Memoji": "Memoji",
    "Tap here, then paste Memoji...": "Торкніться тут, потім вставте Memoji...",
    "Uploading...": "Завантаження...",

    // MARK: - Mood Suggestion
    "We suggest rewriting this as a ": "Ми пропонуємо переписати це як ",
    " dream": " сон",

    // MARK: - Emotions (from backend analysis)
    "Fear": "Страх",
    "Sadness": "Смуток",
    "Anger": "Гнів",
    "Anxiety": "Тривога",
    "Stress": "Стрес",
    "Loneliness": "Самотність",
    "Helplessness": "Безпорадність",
    "Shame": "Сором",
    "Grief": "Горе",
    "Confusion": "Розгубленість",
    "Joy": "Радість",
    "Love": "Любов",
    "Surprise": "Здивування",
    "Disgust": "Огида",
    "Trust": "Довіра",
    "Anticipation": "Передчуття",

    // MARK: - Moods (from backend suggested mood)
    "Peaceful": "Мирний",
    "Serene": "Безтурботний",
    "Humorous": "Гумористичний",
    "Lighthearted": "Легкий",
    "Empowering": "Надихаючий",
    "Confident": "Впевнений",
    "Optimistic": "Оптимістичний",
    "Inspiring": "Натхненний",
    "Joyful": "Радісний",
    "Cheerful": "Веселий",
    "Neutral": "Нейтральний",

    // MARK: - Trend Directions
    "Improving": "Покращується",
    "Worsening": "Погіршується",
    "Stable": "Стабільний",

    // MARK: - Analysis Periods
    "7 Days": "7 днів",
    "30 Days": "30 днів",
    "90 Days": "90 днів",
    "All": "Усі",

    // MARK: - Notification Categories
    "Daily Check-in": "Щоденна перевірка",
    "Dream Reflection": "Роздуми про сон",
    "Nightmare Follow-up": "Продовження після кошмару",
    "Weekly Digest": "Тижневий підсумок",
    "Gentle reminder to log your dreams": "Лагідне нагадування записати сни",
    "Reflect on dreams you've recorded": "Поміркуйте над записаними снами",
    "Check in after rewriting a nightmare": "Перевірте самопочуття після переписування кошмару",
    "Weekly summary of your dream journey": "Тижневий підсумок вашої подорожі зі снами",

    // MARK: - Notification Frequencies
    "Every Day": "Щодня",
    "Weekdays Only": "Тільки будні",
    "Weekends Only": "Тільки вихідні",
    "Once a Week": "Раз на тиждень",
    "Custom Days": "Обрані дні",

    // MARK: - Day Names
    "Sun": "Нд",
    "Mon": "Пн",
    "Tue": "Вт",
    "Wed": "Ср",
    "Thu": "Чт",
    "Fri": "Пт",
    "Sat": "Сб",

    // MARK: - Notification Templates
    "Good morning!": "Доброго ранку!",
    "Dream Journal Time": "Час для щоденника снів",
    "Remember Your Dreams?": "Пам'ятаєте свої сни?",
    "Start Your Day Mindfully": "Почніть день усвідомлено",
    "Did you dream last night? Take a moment to record it.": "Вам снилося щось вночі? Знайдіть хвилинку, щоб це записати.",
    "Your dreams are waiting to be captured.": "Ваші сни чекають, щоб їх записали.",
    "A few minutes to log your dreams can make a big difference.": "Кілька хвилин на запис снів можуть змінити багато.",
    "Dreams fade quickly - save yours now.": "Сни швидко зникають - збережіть свої зараз.",
    "Time to Reflect": "Час для роздумів",
    "Dream Insight": "Осяяння зі сну",
    "Look Back": "Погляд назад",
    "Your Dream Journey": "Ваша подорож зі снами",
    "Revisit a dream you recorded and see how it makes you feel now.": "Поверніться до записаного сну і подивіться, як ви почуваєтесь зараз.",
    "Your past dreams might hold insights for today.": "Ваші минулі сни можуть містити підказки на сьогодні.",
    "Take a moment to reflect on your dream patterns.": "Знайдіть хвилинку, щоб поміркувати над закономірностями своїх снів.",
    "What have your dreams been telling you lately?": "Що вам останнім часом розповідають ваші сни?",
    "How Are You Feeling?": "Як ви почуваєтесь?",
    "Gentle Check-in": "Лагідна перевірка",
    "You're Doing Great": "У вас чудово виходить",
    "Healing Journey": "Шлях до зцілення",
    "How did the rewritten dream make you feel? Consider reading it again.": "Як ви почувалися після переписаного сну? Спробуйте перечитати його.",
    "Remember, you have the power to reshape your dreams.": "Пам'ятайте, у вас є сила змінювати свої сни.",
    "Take a moment to revisit your peaceful dream version.": "Знайдіть хвилинку, щоб повернутися до мирної версії сну.",
    "Your healing journey continues. We're here for you.": "Ваш шлях до зцілення продовжується. Ми поруч з вами.",
    "Your Week in Dreams": "Ваш тиждень у снах",
    "Weekly Reflection": "Тижневі роздуми",
    "Dream Summary": "Підсумок снів",
    "This Week's Journey": "Подорож цього тижня",
    "See how your dream patterns evolved this week.": "Подивіться, як змінювалися закономірності ваших снів цього тижня.",
    "Time for your weekly dream check-in.": "Час для щотижневої перевірки снів.",
    "Reflect on your dream journey this week.": "Поміркуйте над своєю подорожжю зі снами цього тижня.",
    "A week of dreams - what stories did they tell?": "Тиждень снів - які історії вони розповіли?",
]
